ilios/common

addon/routes/weeklyevents.js
This prevents creating history entries for every click. If we don't do
this then a user has to go 'back' through every single click to return
to the dashboard.
=> Replace state for expanded weeks

addon/models/session.js
This isn't useful anymore since status is no longer provided by
PublisableModel. We need to construct the search string in the calling
component instead where we will have access to i18n.
=> Remove searchString CP from session

addon/components/dashboard-week.js, addon/components/week-glance.js, addon/templates/components/dashboard-week.hbs, tests/integration/components/dashboard-week-test.js, tests/integration/components/week-glance-test.js
1 . Switches the week to start on Sunday in week at a glance
2. When a user follows the 'all weeks' link this opens not just the current week, but also the previous and next week.
=> Week starts on Sunday

addon/components/week-glance.js
Once moment has created an instance changes to the global locale do not
effect it anymore. So we need to ensure our instance is re-computed each
time the user changes their language.
Refs ilios/frontend#3136
=> Recompute date formats when the locale changes

addon/components/ilios-calendar-multiday-event.js, addon/components/ilios-calendar-multiday-events.js, addon/templates/components/ilios-calendar-multiday-event.hbs, addon/templates/components/ilios-calendar-multiday-events.hbs, addon/templates/components/ilios-calendar-week.hbs, tests/integration/components/ilios-calendar-multiday-event-test.js
This status is used to determine if click actions are available and
should be the same for a single event on a day and a multi day event.
=> Pass selectable status down to multiday events

addon/templates/components/dashboard-calendar.hbs
=> display external course id in dashboard calendar filters.

addon/adapters/ilios.js, addon/components/dashboard-calendar.js, addon/components/single-event.js, addon/models/school.js
These limits were being used to ensure that we got all data when the API
had a default limit of 20 items. They are no longer necessary since the
API now returns all data starting in v1.23.
Fixes #40
=> Remove limits that were not real

addon/mixins/categorizable-model.js, addon/models/competency.js
These make it easier to display relationship data without loading the
entire set.
Extracted from ilios/frontend#2774
=> Add some convenience relationship counters

addon/templates/components/week-glance.hbs, app/styles/ilios-common/components/week-glance.scss, tests/integration/components/week-glance-test.js
These materials carry the same startDate and endDate as other materials
and may be blank so we need to include release info in this view.
=> Add timed release info to week-glance materials

addon/templates/components/pulse-loader.hbs, app/styles/ilios-common/components/pulse-loader.scss
There was a lot of unused space in the box for this SVG so it was
difficult to use it in smaller areas. I constrained the viewBox to the proportions needed by the animation.  I also removed some CSS we were no longer using and text-align centered the loader which looks nicer.
=> Correct the proportions of the pulse-loader SVG

package.json, tests/dummy/config/environment.js, yarn.lock
The latest ember-cli doesn't work with ember-cli-dotenv, but we can just
use this node component directly.
=> Fix dotenv usage

addon/models/learner-group.js, tests/unit/models/learner-group-test.js
- `availableUsers`
- `childrenUserCounts`
- `childrenUsersTotal`
- `childUserLengths`
- `childUsers`
- `childUsersTotal`
- `usersCount`
- `destroyChilden()`
- `filterTitle`
- `topLevelGroup`
- `allInstructors`
- `allParentTitles`
- `allParentsTitle`
- `sortTitle`
=> Async/await syntax in Learner-Group model

addon/services/ilios-config.js
These are already provided by the endpoint, they were just missing from
the service.
=> Add missing login properties to iliosConfig

tests/dummy/app/index.html
So we're not calling every tester a dummy.
=> Fix the dummy app's title

addon/services/current-user.js, addon/utils/jwt-decode.js, app/utils/jwt-decode.js, package.json, tests/unit/utils/jwt-decode-test.js, yarn.lock
This shim probably isn't going to be maintained for ember 2.17+ as it doesn't
seem to work. We can replace it with a simple implementation of our own.
This unlocks #123
=> Remove jwt-decode shim

addon/models/user.js
This is mainly a fix so that mirage will correctly understand that there
is no inverse property for this relationship on the cohort model.
=> Cohorts do not keep track of primary users

addon/models/learner-group.js, tests/unit/models/learner-group-test.js
Tacking .toArray() onto a promise in an await call doesn't call
`toArray` on the result of the promise. It calls it on the promise
itself and doesn't work.
=> Convert promise result to array

package.json, yarn.lock
Frontend has been updated to handle this update so now we can unblock ember-concurrency and use the latest version.
WIP, needs:
https://github.com/ilios/frontend/pull/3437
=> Unblock ember-concurrency update

addon/adapters/ilios.js
Pulling this from Ember.String is deprecated.
=> Import pluralize from ember-inflector directly

addon/models/session.js, tests/unit/models/session-test.js
refs #79.
this also contains a bugfix to the `tmaxSingleOfferingDuration` CP, which is used in the frontend in various places (I can file individual tickets there for reference if need be).
=> Converted Session model to async/await syntax

addon/components/dashboard-calendar.js, addon/components/selected-term-tree.js, addon/locales/en/translations.js, addon/locales/es/translations.js, addon/locales/fr/translations.js, addon/templates/components/dashboard-calendar.hbs, addon/templates/components/selected-term-tree.hbs, app/components/selected-term-tree.js, app/styles/ilios-common/components/dashboard-calendar.scss, app/styles/ilios-common/components/selected-term-tree.scss, app/styles/ilios-common/styles.scss, tests/integration/components/selected-term-tree-test.js
=> Filter events on the calendar by a vocabulary term

addon/components/dashboard-calendar.js
When we're serving the frontend from an API server we don't actually
send and apiHost because it is just /. We need to handle this as a case
here otherwise the ICS feed URL won't be an absolute path.
Fixes ilios/frontend#3485
=> If no apiHost is configured use the current URL

package.json, yarn.lock
follow-up item to ilios/frontend#3466
do not merge until that issue has been fully resolved.
=> replaced dependency on ember-one-way-controls with ember-one-way-select.

addon/components/ics-feed.js, addon/locales/en/translations.js, addon/locales/es/translations.js, addon/locales/fr/translations.js, addon/templates/components/ics-feed.hbs, app/styles/ilios-common/components/ilios-calendar.scss, tests/integration/components/ics-feed-test.js
Displaying the link makes it too easy to partially copy, the button
takes away that chance.
Fixes ilios/frontend#3237
wip:
=> Copy ICS feed url instead of displaying it

addon/models/session.js, tests/unit/models/session-test.js
These are not integers, they are fractional hours and need to be parsed
as floats when summing them.
Fixes ilios/frontend#3636
=> Parse offering and ILM times correctly

addon/models/instructor-group.js, addon/models/learner-group.js, addon/models/user.js, addon/services/current-user.js, addon/services/permission-checker.js, addon/services/permission-matrix.js, tests/unit/models/instructor-group-test.js, tests/unit/models/learner-group-test.js, tests/unit/models/user-test.js
This allows us to check everything that can be checked on the API. We
probably don't need all of this, but it is easier to do it all at once.
=> Add remaining capabilities to permission-checker

.travis.yml
Until a new version of ember-tether is published this test is going to
continue failing so let's ignore that failure for now
=> Allow ember-beta to fail tests

addon/components/single-event.js, addon/templates/components/single-event.hbs, tests/integration/components/single-event-test.js
Students don't have access to offering or ilmSession and we need to get
all event data from public endpoints.
=> Refactor single-event to only use public data

addon/services/permission-checker.js
This is needed to validate if a cohort can be attached to a course in
the frontend.
Refs ilios/frontend#3756
=> Add canUpdateAllCoursesInSchool to permissionCheccker

addon/components/dashboard-calendar.js
This determines if we should show a dropdown school selector and needs
to look at the updated allSchools property.
Refs ilios/ilios#1511
=> Fix hasMoreThanOneSchool property in calendar

addon/adapters/ilios.js
When we call store.findAll we don't want the cached results, we want all
the records. This ensures we will get them.
=> Reload by default

addon/services/current-user.js
When someone is teaching in a session they get SESSION_INSTRUCTOR not
COURSE_INSTRUCTOR.  So it is written... so it must be done.
Fixes ilios/frontend#3780
=> Fix role given to session instructors

addon/services/current-user.js, addon/services/permission-checker.js, addon/services/permission-matrix.js
By pre-selecting which roles we are actually searching for we can avoid
loading data that we don't need. This can speed up checking
significantly in some situations.
=> Avoid loading unnecessary data

addon/templates/components/ilios-calendar-event-month.hbs, addon/templates/components/ilios-calendar-event.hbs, package.json, yarn.lock
Tooltips is in transition and having trouble staying up to date. It is
kicking out a lot of warnings right now. Since ember-attachment does
everything we need we can just use it.
=> Replace ember-tooltips with ember-attachment

package.json
Prevents publishing things we don't really want to expose to the world
or things that just bloat the package.
=> Specify which files to publish

addon/models/offering.js
We need to specifically track this second level array, it works
correctly in ember data 3.2+ and the old definition did not.
=> Better definition for computed property

addon/adapters/ilios.js, addon/services/ajax.js, package.json, yarn.lock
Update the esa-token plugin and remove or replace deprecated authorize
method.
Fixes #272 
Closes #249
=> Remove deprecated authorize

addon/models/session.js
This is available in the API at version 1.34 .
=> Add pre/post requisite to session model

app/styles/ilios-common/mixins/ilios-input.scss
The 100 value makes inputs cut through modals. They are important, but
not that important. Set it to 5 instead.
Fixes ilios/frontend#4021
=> Make z-index reasonable

package.json, yarn.lock
The dependencies that we pass up to consumer apps should be floated so
that their lock file will reflect any minor changes. This makes it
easier to track down issues.
Closes #316
=> Float dependencies

index.js
When this was included in ilios/frontend this hook gets called with no
tree, since we wouldn't actually want to modify the tree in that case we
can just move on.
=> Fix the rebuilding of the addon-test-support directory

addon/breakpoints.js, addon/components/removable-row.js, app/components/removable-row.js, package.json, yarn.lock
We were only using this for light table and we're not using that
anymore.
=> Remove light table dependencies

.travis.yml
Ember Canary tests are slowing down our builds right now, they run
forever and don't pass.  Let's skip them for now.
=> Skip canary tests

package.json
When we updated ember-cli it changed the dependency from ember-cli-qunit
to ember-qunit, but this lock didn't get changed at the same time.
Refs #342
=> Don't greenkeeper ember-qunit

index.js, package.json
Mirage removed the config.js file in the app in production environments,
but in 'preview' it isn't removed and the import fails because the
setup.js file doesn't exist. This created a minimal fake setup.js file
that can be imported, but does nothing.
=> Add a noop import for mirage config

addon/services/ilios-config.js
This is provided in the index.html file by server variables, but is
accessed through the IliosConfig like all other configuration.
=> Extract error capture configuration into config

addon/helpers/remove-html-tags.js, package.json, yarn.lock
Ember is on a quest to remove jQuery, the less we do with it the better.
=> Stop using jQuery to strip HTML tags

tests/unit/helpers/remove-html-tags-test.js
the helper is in common now, but the corresponding test was still hanging around in frontend. 
move it here, where it belongs.
=> moved remove-html-tags helper unit test from frontend.

.travis.yml, README.md, package.json
Making a move to dependabot which has a better build server and
configuration system so I'm removing GK first to avoid double dependency
management hell.
=> Remove greenkeeper

addon/components/ilios-calendar-day.js, addon/components/ilios-calendar-month.js, addon/components/ilios-calendar-week.js, addon/components/week-glance.js
Bad && here, was filtering out both events with no postreqs as well as
all ILMs instead of just Ilms with postreqs.
There is testing which covers this, but the PR that broke did not rebase with those tests :(
=> Filter events correctly

addon/mixins/events.js, addon/services/school-events.js, addon/services/user-events.js, tests/integration/services/school-events-test.js, tests/integration/services/user-events-test.js, tests/unit/mixins/events-test.js
we need those slug-generating functions in the mixin since we want to splash it into other components, like the user-profile-calendar in frontend.
refs ilios/frontend#4290
=> move slug generation functionality into mixin.

addon/templates/components/week-glance-event.hbs, tests/integration/components/week-glance-event-test.js
Requested by users, makes the list much more useful without the course
LMs which are still available on the single event view.
Fixes ilios/frontend#4320
=> Skip course LMs in Week at a Glance

addon/templates/components/single-event.hbs
Ordinals were probably never a good idea here as it implies a ranking.
Let's use bullets!
Fixes ilios/frontend#4315
=> Switch from ordinals to bullets

config/environment.js
For now I just enabled it by default, we'll want to pull out the flag
code itself once it has been released.
=> Enable session linking

.travis.yml
This allows us to push tags and then not worry about the publish step.
=> Automatically Publish Tags to NPM

addon/services/ajax.js
When JWT wasn't set (the user was logged out) this would die horribly.
Instead we need to do some validation steps and get the property in a
better way.
Fixes ilios/frontend#4291
=> Reorganize the way the JWT is found

addon/components/ilios-calendar-day.js, addon/components/ilios-calendar-week.js
Removes the jQuery dependency and also ensures that the calendar hasn't
already been remove from the page before it is scrolled which can happen
when users flip back and forth to another view.
Fixes ilios/frontend#4292
=> Improve calendar loading

addon/utils/escape-reg-exp.js, tests/unit/utils/escape-reg-exp-test.js
So we don't have to put a guard on every invocation of this.
=> Add a null check when escaping regex

addon/services/current-user.js
If a user has timed out they will have a sessions still, but no
authentication object so we need to protect that as well. Consolidating
all of the checks into a single statement. I thought `.get()` did this for us, but it doesn't seem to.
Fixes ilios/frontend#4406
=> Protect against empty objects in the session

addon-test-support/ilios-common/page-objects/components/learning-materials.js, addon-test-support/ilios-common/page-objects/components/learningmaterial-search.js, addon/components/learningmaterial-search.js, tests/acceptance/course/learningmaterials-test.js, tests/acceptance/course/session/learningmaterials-test.js, tests/integration/components/learningmaterial-search-test.js
Adding a test for this change might have gotten a bit too involved :) I
moved the component into a page object and then also removed the legacy
collections from the page object component.
=> Don't use jQuery to trim LM search

addon/templates/components/dashboard-week.hbs, tests/integration/components/dashboard-week-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
**Summary:**
Updated `weeklyevents` link text from `Last Week / Next Week / All Weeks` to `All Weeks`.
**UI:**
Fixes https://github.com/ilios/frontend/issues/3980
=> update All Weeks link title

addon/components/offering-form.js, addon/templates/components/offering-form.hbs, app/styles/ilios-common/components/offering-form.scss
**Summary:**
Fixed buggy time inputs.
- Added `timeout` for better user experience; users would expect to be able to delete the 0
- `<input type="number>` is supported by all browsers (see [here](https://www.w3schools.com/tags/att_input_type_number.asp))
- All values entered are valid so no need for additional validations (non-number are automatically considered 0)
**GIF:**
Fixes https://github.com/ilios/frontend/issues/2049
=> fixed buggy time inputs

addon/templates/components/leadership-search.hbs, app/styles/ilios-common/mixins/user-search.scss, tests/integration/components/leadership-search-test.js
fixes #635
affects leadership search in courses, sessions, programs, schools, and curriculum inventory.
=> rm double-indent, correct color overrides.

addon/components/detail-objectives.js, addon/templates/components/detail-objectives.hbs, addon/templates/components/objective-manage-descriptors.hbs, app/styles/ilios-common/components/detail-objectives.scss
**Summary:**
This PR improves two areas when adding new Mesh terms.
- Smooth slower transition to let users know that the UI is changing
- Shows objective description when users add new terms 
**GIF:**
Fixes https://github.com/ilios/frontend/issues/2551
Fixes https://github.com/ilios/frontend/issues/4512
=> smoother comprehensive transition when adding new MeSH terms

addon/templates/components/learnergroup-selection-manager.hbs, app/styles/ilios-common/components/learnergroup-selection-manager.scss, app/styles/ilios-common/components/offering-form.scss
**Summary:**
Fixes two issue outlined in the ticket:
- Over extending search input for instructors
- Mispositioned available learner groups filter search input
**UI:**
Fixes https://github.com/ilios/common/issues/421
=> offerings UI style fixes

addon/templates/components/course-objective-list.hbs, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
**Summary:**
If the course objective is associated as parent to any session objectives, users will receive a better warning removal message.
**UI:**
Fixes https://github.com/ilios/frontend/issues/2125
=> better course objective removal warning message

addon/components/common-dashboard.js, addon/components/dashboard-calendar.js, addon/mixins/dashboard-controller.js, addon/templates/components/common-dashboard.hbs, addon/templates/components/dashboard-calendar.hbs, tests/acceptance/dashboard/calendar-test.js, tests/dummy/app/templates/dashboard.hbs
**Summary:**
Enabled query params on five checkbox filters for the calendar.
- Courses: `?courses=1%2C2`
- Session Types: `?sessionTypes=1%2C2`
- Terms: `?terms=1%2C2`
- Course Levels: `?courseLevels=1%2C2`
- Program/Cohort: `?cohorts=1%2C2`
**UI:**
_Course / Type_
_Detail_
Accompanies https://github.com/ilios/frontend/pull/4500
Fixes https://github.com/ilios/frontend/issues/3061
=> added query params for all 5 additional checkbox-filters

addon-test-support/ilios-common/page-objects/components/objectives.js, addon-test-support/ilios-common/page-objects/course.js, addon-test-support/ilios-common/page-objects/session.js, addon/components/big-text.js, addon/components/editable-field.js, addon/templates/components/big-text.hbs, addon/templates/components/editable-field.hbs, tests/integration/components/course-objective-list-item-test.js, tests/integration/components/course-overview-test.js, tests/integration/components/editable-field-test.js, tests/integration/components/session-objective-list-item-test.js
**Summary:**
The ellipses icon which normally expands the display text doesn't work because it's embedded in a element which also has a click event trigger and the `edit` task function gets hit first before bubbling the action down to the ellipses icon. The parent click event trigger is removed and moved to `big-text` component.
Fixes https://github.com/ilios/frontend/issues/2519
=> fixed expand text bug

addon/components/course-publicationcheck.js, addon/components/publish-all-sessions.js, addon/components/publish-menu.js, addon/components/session-publicationcheck.js, addon/models/session.js, addon/templates/components/course-publicationcheck.hbs, addon/templates/components/publish-all-sessions.hbs, addon/templates/components/publish-menu.hbs, addon/templates/components/session-publicationcheck.hbs, app/styles/ilios-common/components/course-publicationcheck.scss, app/styles/ilios-common/components/publish-all-sessions.scss, app/styles/ilios-common/components/session-publicationcheck.scss, config/icons.js, tests/acceptance/course/session/publish-test.js, tests/integration/components/publish-menu-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
**Summary:**
- Added scroll functionality to be directed to course/session missing items review when users click on the `Review Missing Items` dropdown option.
- Course Missing Items Review - checks if any of the course objectives do not have parents. If so, unlink icon will show up and transition the user to `/courses/course_id?courseObjectiveDetails=true&details=true`.
- Session Missing Items Review - checks if any of the session objectives do not have parents. If so, unlink icon will show up and transition the user to `/courses/course_id/sessions/session_id?sessionObjectiveDetails=true`.
- Publish All Review Page
- There is a warning (in yellow) if the any one of the course objectives do not have parents, along with an unlink icon and chart icon, which takes users to course objective …
=> scroll for missing items & unlinked objectives warnings

app/styles/ilios-common/components/learnergroup-selection-manager.scss
**Summary:**
Top level learner groups in the list should be bold.
**UI:**
Fixes https://github.com/ilios/frontend/issues/4538
=> higher level learner group list header is bold

addon/components/my-materials.js, addon/controllers/mymaterials.js, addon/routes/mymaterials.js, addon/templates/components/my-materials.hbs, addon/templates/mymaterials.hbs, app/styles/ilios-common/components/my-materials.scss, tests/integration/components/my-materials-test.js
**Summary:**
`/mymaterials` route displays a loading spinner for better communication to users.
**UI:**
Fixes https://github.com/ilios/frontend/issues/4539
=> better loading state display for mymaterials route

addon/services/api-version.js, app/services/api-version.js, config/api-version.js, config/environment.js, tests/unit/services/api-version-test.js
It makes sense to have this in common as that is where the models go
that actually bump the version. We also need this information in the
course manager API to prevent writes there when the version does not
match.
=> Provide API version as a service

package-lock.json, package.json
The latest 1.0.8 pacakge ember-cli-update as a dependency which makes
npm audit very sad as there are several outdated and vulnerable
libraries there. We'll stick with 1.0.6 until this is fixed.
=> Lock ember-promise-helpers version

addon/components/week-glance.js, addon/helpers/lm-type.js, addon/services/permission-matrix.js, index.js
This is now considered to be a bad idea and ESLint 6+ adds it to their
default rules. It's a bit more verbose, but the new syntax looks ok to
me and we can just go with the flow here.
Refs #736
=> Refactor usage of hasOwnProperty from object prototype

addon/components/detail-cohort-manager.js, addon/components/detail-mesh.js, addon/components/instructor-selection-manager.js, addon/components/session-offerings.js, addon/templates/components/instructor-selection-manager.hbs
This import is deprecated, but it turns out every usage of it was a
vestige of old code and this is done in templates now.
=> Remove unnecessary calls to translationMacro

addon/components/visualizer-course-vocabulary.js, addon/templates/components/visualizer-course-vocabulary.hbs
Using a non-async reduce here is better than putting a += into a for
loops with async side effects. The later has the potential to clobber
it's own data and fails linting in Eslint 6+.
Refs #736
=> Refactor data structure

addon/services/search.js, tests/unit/services/search-test.js
When this is passed to the search API it returns autocomplete options
only instead of running a full search.
=> Add onlySuggest option to the search service

addon/components/lm-type-icon.js, addon/templates/components/lm-type-icon.hbs
Usually too fast for the eye to see, but this can render without a
correct type which shows up as errors in our tests. Making this a
computed property with a default prevents this.
=> Guard against empty type in icon

addon-test-support/ilios-common/page-objects/components/api-version-notice.js, addon/components/api-version-notice.js, addon/templates/components/api-version-notice.hbs, app/components/api-version-notice.js, app/styles/ilios-common/components.scss, app/styles/ilios-common/components/api-version-notice.scss, app/styles/ilios-common/mixins.scss, app/styles/ilios-common/mixins/critical-notice.scss, tests/integration/components/api-version-notice-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
When the API version here doesn't match the one on the API the app goes
into read-only mode. This notice should appear at the top to let users
know what is going on.
WIP:
Example:
=> Add Improved API Version Notice Component

addon/components/new-learningmaterial.js, package-lock.json
Adding a computed property onto a validator breaks starting with ember
3.13.
=> Replace computed props with plain functions

addon/components/new-objective.js
...and also remove some of the error checking and safety by assuming the
save is going to fire correctly. This is the same pattern we have almost
everywhere though so I'm going with it plus this code is 4 years old so it's hard to say why it was written this way.
=> Modernize save action

.travis.yml
As with beta before it we're waiting for a release of
ember-cp-validations that is compatible with Ember 3.13 until then we
don't need to hold up merging other things.
=> Temporarily allow failures on ember-release

addon/templates/components/week-glance-event.hbs, package-lock.json, package.json, tests/dummy/config/environment.js
Many learning materials and events have identical titles. For example 'slides'. When these all appear on the same page it is difficult for those using assistive technologies to figure out which one is correct. aria labels allow us to add more context to each link.
This also adds the `a11y-testing` library so we can start automating these tests, but there is a lot left to do on WAAG so I have not added those tests here.
=> Add more descriptive information to links

app/styles/ilios-common/mixins/ilios-form.scss
New dark green color can make active buttons difficult to read, they
probably always should have had this style applied, but it's critical
now.
=> Fix text buttons

testem.js
This is no longer needed or recommended by ember-cli.
=> Remove gpu flag for chrome

addon/components/html-editor.js, addon/templates/components/html-editor.hbs
We removed this button, but it was still possible to underline using the
keyboard. This shouldn't be allowed as the `u` element is not
accessible.
Refs: https://github.com/ilios/ilios/pull/2658
=> Prevent adding `u` underline using keyboard shortcut

addon/mixins/events.js, tests/acceptance/dashboard/calendar-test.js, tests/unit/mixins/events-test.js
The session is not available for students to access, but we have access
to the course ID here, we can just use that. This allows students to use
the course filtering options on the calendar.
Fixes #649
=> Get course from the event

addon/authenticators/ilios-jwt.js, tests/dummy/config/environment.js
Using commonAjax brings in ember-ajax which is jQuery based, but
injecting the config here we can read the hostname information we needed
and then go back to using more of what is provided upstream.
=> Remove jQuery from auth flow

addon/components/course-rollover.js, addon/components/dashboard-materials.js, addon/components/offering-calendar.js, addon/routes/mymaterials.js, addon/services/fetch.js, addon/services/ilios-config.js, addon/services/school-events.js, addon/services/user-events.js, app/services/fetch.js, package-lock.json, package.json, tests/integration/components/course-rollover-test.js, tests/integration/components/dashboard-materials-test.js, tests/integration/services/school-events-test.js, tests/integration/services/user-events-test.js, tests/unit/services/fetch-test.js
`ember-ajax` is jQuery based so this moves our network requests over to use `fetch` instead. I've moved us to a more explicit API for this so it's easier to inject the needed headers and return good data.
=> Use fetch API in place of ember-ajax

config/icons.js
This is needed on the course header, but wasn't included.
=> Add missing lock icon

app/serializers/application.js, package-lock.json
New deprecation warning in Ember Data 3.14 that we need to provide this
as it will no longer be automatically selected in a future version. Details at https://deprecations.emberjs.com/ember-data/v3.x/#toc_ember-data:default-serializers
=> Provide default serializer

.ember-cli.js, package.json, tests/dummy/config/optional-features.json
This really only matters for the dummy app. With this edition activated
it can consume other Octane addons and use Octane features and
blueprints.
=> Activate Octane Edition

addon/components/dashboard-materials.hbs, addon/components/editable-field.hbs, addon/components/my-materials.hbs, addon/components/objective-sort-manager.hbs, addon/components/truncate-text.hbs, addon/components/truncate-text.js, addon/components/week-glance-event.hbs, app/components/truncate-text.js, app/styles/ilios-common/components.scss, app/styles/ilios-common/components/editinplace.scss, app/styles/ilios-common/components/truncate-text.scss, index.js, package.json, tests/integration/components/truncate-text-test.js
Meant to be a more functional replacement for `<BigText>` with better a11y
and improved ability to use it inside of `<EditableField>`.
Improved fix for ilios/frontend#2519
=> Add and use new TruncateText component

app/styles/ilios-common/components/body.scss, app/styles/ilios-common/variables.scss, index.js, package-lock.json, package.json
We use normalize.css on the frontend which causes some issues
particularly around line-height and alignment. To ensure that this is
easier to see I'm adding normalize.css here and ensuring that the line
height gets set specifically.
=> Align common with frontend styles

index.js
When this addon is used in another addon (or engine) it needs to to a
bit more work to find the current environment.
=> Use the correct app when deeply nested

addon/adapters/ilios.js
There are several ways this can be turned off in Ember, so we should use
the import instead for maximum reliability.
=> Don't rely on extending the string prototype

addon/services/api-version.js, addon/services/current-user.js, addon/services/ilios-config.js, addon/services/permission-matrix.js
We're going to want to remove these async computeds when converting
these service Objects to ES Classes. First step in this transition is to
rely on async methods in each service.
=> Add methods to mirror service computed properties

addon/services/ilios-config.js
We don't want to fetch this every time we look up a new value so this
adds a local cache. It's temporary and can be removed once we move to an
ES Class for this service and then we can just set `config` on the
class.
=> Cache config from API server

addon/services/ilios-config.js
Waiting on the fetch doesn't work here because each subsequent call
doesn't set _config until the fetch returns. Instead we have to store
the promise and wait for it to be settled.
=> Only fetch configuration once

addon-test-support/ilios-common/page-objects/components/course-header.js, addon-test-support/ilios-common/page-objects/components/course/publication-menu.js, addon/components/course-header.hbs, addon/components/course-header.js, addon/components/course/publication-menu.hbs, addon/components/course/publication-menu.js, addon/decorators/validation.js, addon/decorators/validation/length.js, addon/decorators/validation/not-blank.js, app/components/course/publication-menu.js, app/styles/ilios-common/components/course-header.scss, app/styles/ilios-common/components/publish-menu.scss, tests/acceptance/course/publish-test.js, tests/integration/components/course-header-test.js, tests/integration/components/course/publication-menu-test.js
Unwraps some previously shared publish menu functionality in order to avoid a mixin and creates a publish course component instead. Also fixes some layout problems with locked courses.
It turns out our existing brown scheduled course color doesn't have enough contrast, but I've allowed that to pass here anyway.
=> Glimmer <CourseHeader>

addon/services/current-user.js, tests/integration/services/current-user-test.js
To avoid duplicating network requests we cache the results of the user
model lookup.
Fixes #1054
=> Cache current user model

app/styles/ilios-common/components/learning-material-uploader.scss
Added padding to make it look like other buttons.
The label was squished into the button because the button isn't real,
it's a span.
=> Fix file upload button display

app/styles/ilios-common/components/dashboard-view-picker.scss, app/styles/ilios-common/components/single-event-objective-list.scss
This is important for a11y keyboard navigation.
=> Stop removing focus outline from buttons

index.js, tests/dummy/app/index.html
This ensures that all of our apps have a working initial title tag.
=> Add <title> of ilios to index.html

addon/components/week-glance-event.hbs, tests/integration/components/week-glance-event-test.js
Having the download label be on the icon was causing some errors in
tests, this resolves it and still results in the same label for the
link.
=> Clean up label on download links

addon/components/dashboard-calendar.js
Depending on async speed this value might not have been set byt the
setup task so we need to wait for it to exist.
Fixes #1100
=> Ensure school is set before accessing it

addon/components/single-event-learningmaterial-list.hbs, addon/components/single-event-learningmaterial-list.js, tests/integration/components/single-event-learningmaterial-list-test.js, tests/integration/components/single-event-test.js
Modifies the LM downloads so that the screen reader title combines the
name of the file as well as the word download this matches the same
setup we use on week at a glance materials.
=> Fix a11y issue with download icons

package.json
We're using this in a few places, but we were getting it from somewhere
else and needed to install it directly.
=> Add ember-ref-modifier as dependency

addon/components/expand-collapse-button.hbs
Now consumer can attach these labels to make button accessible.
=> Add labels to expand / collapse buttons

addon/components/sessions-grid.js
This protects the scroll method when it is called after the component is
destroyed (or in the case of tests after the entire container is
destroyed).
=> Prevent scroll issues

.travis.yml
These are filing due to an unknown condition in ember beta/canary.
Disabling them while we track that down.
Refs #1123
=> Temporarily disable tests

.travis.yml
These are failing so we shouldn't upgrade, but we're ok to keep building
on our version of ember and unblock this.
=> Temporarily disable ember-release tests

addon/components/single-event-learningmaterial-list.hbs, addon/components/week-glance-event.hbs
While this is semantically OK, it messes with our Siteimprove a11y
checks so I think living with the long lines is a better choice
=> Remove lint breaks in aria-labelledby

tests/dummy/config/deprecation-workflow.js
This is getting thrown from <LearnerergroupTree> using isVisible, but
we'll refactor that out when we octanify that component so I'm just
silencing it for now.
=> Silence is-visible deprecation

addon/components/dashboard-calendar.js, tests/acceptance/dashboard/calendar-test.js
When the page was loaded directly with the detail filter open the
cohortProxies property was not yet set. Since the template looks for
this.cohorts to be an array adding an option chain here returns
undefined until the cohortProxies is set and then returns the array as
intended.
Fixes ilios/frontend#5098
=> Fix detail filter on calendar

addon-test-support/ilios-common/page-objects/components/offering-form.js, addon-test-support/ilios-common/page-objects/session.js, addon/components/offering-form.hbs, addon/components/session-overview.hbs, addon/components/session-overview.js, addon/components/toggle-yesno.hbs, tests/integration/components/offering-form-test.js
In Ember 3.16 the computed property in the session model isn't getting
re-computed when an ILM is added / removed from the session. Instead of
delegating that to the model we can just track it in session-overview
directly.
=> Keep track of ILM status in component

index.js
In order to allow for parallel babel builds this pre-processor was
changed upstream, to get these changes, and any future ones I modified
this according to a code sample to ensure we call the upstream method,
but only when not working in, or testing this addon directly.
=> Change the way we register the ember-cp-validations preprocessor

addon/components/not-found.hbs
May help with an issue where sometimes this produced a link with query
params included.
=> Link to dashboard

addon/components/week-glance.js
The boolean expression checks .midnightAtTheStartOfThisWeek twice. One of
them was meant to be .midnightAtTheEndOfThisWeek instead.
Boolean OR was used where Boolean AND was meant. (If it is not midnight
at the begining of the week OR it is not midnight at the end of the
week, then the expression will always be TRUE. If AND is used instead, it excludes
midnight at the start or end of the week.)
=> Fix boolean expression in week-glance.js

addon/decorators/validation/not-blank.js
Boolean OR was used where AND was intended. As previously written, the
expression will always evaluate to TRUE.
=> Fix boolean expression in not-blank validation decorator

addon/adapters/ilios.js
Limit the unnecessary network traffic of sending the JWT and other
cookies over and over to the API server when the only thing we require
is the JWT that is getting sent as a header anyway.
There is a bug in FF dev tools that indicated to me that we were sendning 1.5mb of cookies with each request, turns out to be 1.5kb, so this change is trivial, but I don't see any reason not to include it and our CAS authentication will benefit as it would end up sending triple JWT data.
For some testing reference the netlify build currently doesn't send any cookies because it isn't on the same server as the API and it works well. So the session cookies are already not expected to be sent, this just guarantees that they never are.
=> Don't send cookies with API requests

ember-cli-build.js
This flag ensures we don't include anything that won't build quickly
using all available processors.
This will fail until we get new versions of `ember-simple-set-helper` and `ember-page-title` addons which fix issues that stop parallel builds from working. Opening it anyway as a reminder and to track progress.
=> Force babel to only work with parallel builds

addon/components/print-course.js, addon/mixins/course/index-route.js, addon/mixins/print-course-route.js, addon/utils/preload-course.js, app/utils/preload-course.js, tests/acceptance/course/printcourse-test.js
Some larger courses were making 300+ network requests to load
the print view. This change optimizes the network loading in the same
way it is improved for the course editor and brings the number of
requests down into the 20-30 range.
I extracted this loading work into a utility so it's now shared between
these two routes.
=> Improve loading of course print view

addon/components/editable-field.hbs
This allows properties to be passed in from the calling side, like
data-test- or additional classes. Used in the frontend [instructorgroup-header](https://github.com/ilios/frontend/blob/7e070fa61d70a7b6525e4db649a5882d655104ed/app/components/instructorgroup-header.hbs#L9).
=> Add splatributes to editable field

addon/components/sessions-grid-offering.hbs, addon/components/sessions-grid-offering.js
this is an un-ticketed regression that i found when working on something else.
in the sessions list, when you close the embedded offering form, you end up with this dreadful error message:
```
Uncaught Error: You attempted to access the 'element' property on a Glimmer Component, but that property does not exist in Ember.js applications, it only exists in Glimmer.js apps. You define a class field with the same name on your component class and it will overwrite this error message, but it will not be used by the framework.
```
this was an oversight during glimmerization of this component, using a ref-modifier fixes that issue.
=> fixes scroll into view upon offering form closing.

addon/adapters/ilios.js
When the API is load balanced it needs a cookie to know where to send
requests. LMs files are uploaded temporarily in the first request and then
attached to an LM in a second request, right now both of those requests
have to go to the same server.
=> Temporary re-enable all cookies again

.github/workflows/future-ci.yaml, .github/workflows/release.yaml
The latest update to ember-cli added way more tests to the basic npm
test command. We need to specify only the ember tests, otherwise we're
testing a lot more than we meant to.
=> Run the correct tests

addon/components/publish-all-sessions.hbs, app/styles/ilios-common/components/publish-all-sessions.scss
Instead of using the span as a button this just uses the HTML label to
do the same thing.
Fixes #1265
=> Fix checkbox style in PublishAllSessions component

addon-test-support/ilios-common/page-objects/components/learning-materials.js, addon/components/new-learningmaterial.hbs, addon/components/new-learningmaterial.js, addon/decorators/validation.js, addon/decorators/validation/is-true.js, tests/acceptance/course/learningmaterials-test.js, tests/acceptance/course/session/learningmaterials-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
Adds validation and error messaging when either the rationale or the
agreement are not provided for new file learning materials.
Fixes #1204
=> Validate copyright on LMs

app/styles/ilios-common/components/ilios-tooltip.scss
This allows them to clear the navigation bar and anything else in their
way.
Fixes #1275
=> Give tooltips some z-index love

addon/models/objective.js, tests/unit/models/objective-test.js
Oversight here, these should always have been marked active, there is no
reason to create a new inactive objective.
=> Make new objectives active by default

addon/components/session-overview.hbs, addon/components/session-overview.js
All of the individual promises getting read in the load method was
causing a significant rendering delay as each one moved in and out of
the main thread. This appeared as a jump in the screen when a session was first loaded as the overview just didn't display at all for a few seconds.
Loading them all at the same time solves that issue. As
long as the load has run at least once we should display the data. Also
moved one method from a task to a plain async method which it seems to
be.
=> Improve Session Overview Loading

addon/services/api-version.js, addon/services/current-user.js, addon/services/ilios-config.js, addon/services/permission-matrix.js
There are method replacements for each of these, deprecate them so we
can find any remaining usages and remove them.
=> Add deprecation message for async computed properties

tests/dummy/config/deprecation-workflow.js
This is our own deprecation, but it's very noisy in tests so I've
silenced it until we can fix.
=> Silence common.async-computed deprecation

.eslintrc.js, addon/adapters/ilios.js, package-lock.json, package.json, tests/dummy/config/optional-features.json
We don't need it anymore here so we can remove it and save some space plus ensure we don't add back any dependencies accidentally.
=> Remove jQuery

addon/services/permission-matrix.js
When a user without high level permissions visits a course the matrix
can be loaded many times while checking permissions. This causes the
schools to be fetched each time and the array re-built. Instead we can
cache this mostly static value.
=> Cache the permission matrix

addon-test-support/ilios-common/helpers/date-picker.js
Tests can get flakey when multiple inputs are modified on the same page.
Closing in between ensures this doesn't happen.
=> Close Pikaday in tests

addon/components/course-rollover.hbs, addon/components/course-rollover.js, tests/integration/components/course-rollover-test.js
When the title was changed the available years were not being
re-calculated. I've adjusted this to make it more synchronous by
pre-loading all courses in the school and then letting everything else
be tracked.
Fixes #1342
=> Respond to title change in course rollover

addon/components/session-overview.hbs, package-lock.json, package.json
add those as dev-dependencies in frontend's `package.json` with next common release bump there:
- `"@ember-intl/cp-validations": "^4.0.1",`
- `"ember-cp-validations": "^4.0.0-beta.9",`
=> [Breaking] rm old validation libraries

addon/components/offering-manager.hbs, addon/components/sessions-grid-offering.hbs, app/styles/ilios-common/components/offering-manager.scss, app/styles/ilios-common/components/sessions-grid-offering-table.scss
When links are placed in location it was breaking the offering manager
and session offerings grid's. When possible we can truncate this text
and wherever it is we can overflow it so it doesn't blow out the
available space.
Fixes #1347
=> Improve display of long offering location values

addon/components/offering-form.hbs, addon/components/offering-form.js, addon/components/publish-all-sessions.hbs, addon/components/publish-all-sessions.js, addon/components/save-button.hbs, app/components/save-button.js, tests/integration/components/save-button-test.js
Because WaitSaving uses a modal dialog that gets wormholed out to a
different location in the DOM it is susceptible to missing it's queue to
be destroyed when the component containing it is removed. Instead of a
modal this makes the button into their own live saving state with a
spinner, percentage, and check mark when complete.
Fixes #1345
=> Replace save status modal with a live button

addon/components/common-dashboard.hbs
This isn't a semantic use of section as it encompasses many things, we
could add a label to it, but since all the elements in the tree are
actually labeled with good headers it makes more sense to switch this to
a semantically meaningless div that contains other content.
=> Switch from section to div on dashboard

addon-mirage-support/factories/objective.js, addon/components/course/manage-objective-parents.hbs, addon/components/course/objective-list.js, tests/acceptance/course/objectiveparents-inactive-test.js, tests/integration/components/course/manage-objective-parents-test.js
When a program year objective is marked as inactive it can not be
selected as a parent, if it has already been selected as the parent it
will continue to show up.
Refs: ilios/frontend#3003
Requires:
=> Hide inactive objective parents

addon/components/dashboard-materials.hbs, app/styles/ilios-common/components/dashboard-materials.scss, tests/integration/components/dashboard-materials-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
When browsing the materials view on the dashboard it's not intuitive to
go to the user profile dropdown to navigate to My Materials, instead
this adds a link in the same place as WaaG to get to that view.
=> Add My Materials link to the dashboard

addon/components/daily-calendar-event.hbs, addon/components/detail-terms-list-item.hbs, addon/components/ilios-calendar-event-month.hbs, addon/components/ilios-tooltip.hbs, addon/components/offering-manager.hbs, addon/components/offering-manager.js, addon/components/selectable-terms-list-item.hbs, addon/components/weekly-calendar-event.hbs, addon/modifiers/mouse-hover-toggle.js, app/modifiers/mouse-hover-toggle.js, app/styles/ilios-common/components/ilios-calendar.scss, package-lock.json, package.json, tests/acceptance/dashboard/calendar-test.js, tests/integration/modifiers/mouse-hover-toggle-test.js
Removes our dependency on Ember Attacher and allows us more control over the style and content of tooltips.
=> [breaking] Use Ilios Tooltips Everywhere

addon/components/detail-learning-materials.hbs, app/styles/ilios-common/components/detail-learningmaterials.scss
Does the same thing as clicking the LM title, but might be a little bit
more obvious for users who don't want to unintentionally download the
LM file itself.
Fixes #1374
=> Add edit button to learning material list

addon/components/course/manage-objective-parents.hbs, addon/components/course/objective-list.js, tests/acceptance/course/objectiveparents-allow-multiple-test.js
This configuration option wasn't being passed through correctly after
the refactor to Octane objectives. Fixed and added a test.
Fixes #1392
=> Allow course object to have multiple parents when configured

addon/utils/load-polyfills.js, index.js, package-lock.json, package.json, tests/dummy/app/routes/application.js, tests/dummy/config/targets.js, tests/unit/utils/load-polyfills-test.js
This version, which is still in active use, doesn't have the Intl libs
we need. ~Using the polyfill.io service creates a script that uses the
browser agent to decide what data to send so users of more modern
browsers won't need to download and execute this.~
Instead of relying on a third party service which may block loading
indefinitely if it is down and which we'll need to remember to keep
updated this loads the polyfills we need for Safari 12 by doing feature
detection and then async loading each script.
Fixes #1412
=> Add polyfill for safari 12

package-lock.json, package.json
There is a bug in 4.1.0 that prevents sending a resolved promise as an
array to sort-by. For now we'll stick with 4.0
=> Lock ember-composable-helpers at 4.0.0

package-lock.json, package.json
intl-utils 3.3.0 doesn't work in browsers (only in node). In order to
avoid that release in our code I had to pin all of this stuff
temporarily.
=> Pin @formatjs intl libraries

addon/components/detail-mesh.hbs
They don't have a title, so that doesn't really work!
=> Sort mesh decriptors by name

addon/templates/mymaterials.hbs
{{title}} has been deprecated by ember-page-title in favor of
{{page-title}}.
=> Replace title with page-title

addon/components/session-details.hbs, addon/modifiers/scroll-into-view.js, addon/templates/session/index.hbs
When clicking on a session further down the list of sessions in a course
users were being left somewhere in the middle of the session instead of
at the top. This seems to be caused by the scroll working while the page
is still building. Waiting until the next tick of the runloop results in
the desired position of the screen.
I also moved this up a level because I think it gives a better user
experience to retain the return to session link.
=> Improve screen position when visiting session

addon/components/sessions-grid.hbs, addon/components/sessions-grid.js, addon/routes/course/index.js, addon/services/preserve-scroll.js, package-lock.json, package.json, tests/unit/services/preserve-scroll-test.js
The preserveScroll service is used here and on the DashboardMyReports component on the frontend, but in a confusing way. I touched up the API and also yanked the scroll event binding as it wasn't needed to record the position when a session is clicked. 
Refs ilios/frontend#2977
=> [breaking] Improve Scroll Position Handling

.github/workflows/automerge.yml
Removed many of the workflow events that we don't use. Since this
workflow isn't fun against the master branch we can't use check_suite
which is causing our PRs to not merge since tests take longer that the
retry time. Instead we can sleep for longer.
=> Adjust automerge settings

addon/services/data-loader.js
These are needed at the top level of courses and learner groups to load
the data for those lists in one request instead of many.
=> Add new data loaders

addon-test-support/ilios-common/page-objects/components/leadership-list.js, addon-test-support/ilios-common/page-objects/components/leadership-manager.js, addon-test-support/ilios-common/page-objects/components/session-leadership-expanded.js, addon-test-support/ilios-common/page-objects/session.js, addon/components/course-editing.hbs, addon/components/course-leadership-expanded.hbs, addon/components/course-leadership-expanded.js, addon/components/leadership-collapsed.hbs, addon/components/leadership-list.hbs, addon/components/leadership-manager.hbs, addon/components/session-details.hbs, addon/components/session-leadership-expanded.hbs, addon/components/session-leadership-expanded.js, addon/models/course.js, addon/models/session.js, addon/models/user.js, tests/acceptance/course/leadership-test.js, tests/acceptance/course/session/leadership-test.js, tests/integration/components/course-leadership-expanded-test.js, tests/integration/components/leadership-list-test.js, tests/integration/components/leadership-manager-test.js, tests/integration/components/session-leadership-expanded-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
This new leadership role will have expanded privileges in the course and
session and will be able to see events and materials as if they were a
student in the course.
Requires https://github.com/ilios/ilios/pull/2978
=> Add Student Advisor manager to course and sessions

addon/components/detail-learner-list.hbs, addon/components/detail-learners-and-learner-groups.js, tests/integration/components/detail-learners-and-learnergroups-test.js
The metadata hasMany property we're reading from the model isn't
autotracked so we have to add a computed tag to ensure this recomputes
when the values change. For some reason this only presents itself in a production build, but I was able to create a test that duplicates the issue within the single component so I believe this fixes #1550
=> Track the count of learners and groups

addon/decorators/validation/is-url.js, package-lock.json, package.json, tests/integration/components/offering-form-test.js
This is a more maintained validation system (and we're already using it
on the frontend). Unfortunately it still doesn't catch a bad slash in the
query param so I've added a test that is allowed to fail and will
attempt a PR upstream to fix.
Refs ilios/ilios#3050
=> Replace our URL validation library

addon/components/single-event-learningmaterial-list.hbs, tests/integration/components/single-event-learningmaterial-list-test.js, tests/integration/components/single-event-test.js
no idea what we were originally thinking here, the commit logs are not clear on it.
btw, the timed release info (start/end date) is listed for un-blanked materials further down in this component's template, so removing this altogether seems like the best approach to me.
fixes #1589
=> remove timed release indicator from blanked LMs

lib/set-transform.js
`path` will always be undefined. I believe `node.params[0]` was intended
instead.
=> fix: change undefined identifier in error message

addon/models/session-objective.js, addon/models/session.js, tests/unit/models/session-objective-test.js, tests/unit/models/session-test.js
Sessions with no description where failing because the undefined check
wasn't catching null values. Instead of using our own regex this change
uses the strip tags library we're already using elsewhere. Since that
library handles null values this fixes the issue.
Refs ilios/ilios#3097
=> Fix tag stripping in sessions and session objectives

addon-mirage-support/factories/learner-group.js, addon-test-support/ilios-common/page-objects/session.js, addon/components/offering-form.js, addon/models/learner-group.js, tests/acceptance/course/session/offerings-test.js
companion PR to https://github.com/ilios/ilios/pull/3098
this also adds the functionality to populate offering urls from learner group default urls during small group offering creation.
it does not do anything with the needs-accommodation flag yet.
=> adds url and needsAttribution atts to learnergroup model.

app/styles/ilios-common/components/body.scss
This was inheriting our default Nunito font which is a serif font,
instead styling this like our headers which are sans-serif and changing
the color to match our text color so it isn't stark black.
Fixes ilios/ilios#3112
=> Style select a bit

addon-test-support/ilios-common/page-objects/components/detail-learnergroups-list.js, addon-test-support/ilios-common/page-objects/components/learnergroup-selection-manager.js, addon/components/detail-learnergroups-list.hbs, addon/components/learnergroup-tree.hbs, addon/components/offering-manager.hbs
=> correctly pass title to icon.

addon/adapters/ilios.js
This ensures it will react to changes that happen after this adapter is
constructed.
=> Use a getter to built headers

tests/dummy/config/dependency-lint.js
No API difference between these versions, while we await a 1.0 release
we can just accept them both.
=> Allow multiple ember-get-config versions

tests/acceptance/course/session/overview-test.js
Differences in single/double digit days and months between these two
which make this test flakey.
=> Format test date correctly

addon/components/new-offering.hbs, addon/components/new-offering.js, addon/components/offering-form.hbs, addon/components/offering-form.js
@dartajax i moved the scroll-into-view functionality out of the offering form component itself and into the wrapper component for new offerings. the new scroll target is the "New Offering" label.
=> moves scroll-into-view into wrapper component.

addon/components/sessions-grid-offering-table.hbs, addon/components/sessions-grid-offering.hbs, app/styles/ilios-common/components/sessions-grid-offering-table.scss
turns out these were out of whack.
fixes #1763
=> Corrects column counts in offerings grid

app/styles/ilios-common/components/detail-learnergroups-list.scss
this is a space-saving measure.
fixes #1776
=> re-styles selected learner groups as removable tag list mixin.

addon/components/single-event-objective-list.hbs
=> markup fix for displaying no linked objectives.

addon/decorators/validation.js, addon/decorators/validation/is-hex-color.js
needed for validating component props that are wired to `<input type="color">` input fields.
Most (modern) browsers will not let the users type into an actual input box, for example Chrome and Firefox bring up native color-picker dialogues. However, Safari renders an input box that can be typed in, so we have to validate user input in this fashion.
For reference see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color
=> adds IsHexColor validator.

addon/components/course-rollover.hbs, addon/components/session-copy.hbs, app/styles/ilios-common/components/body.scss, app/styles/ilios-common/components/course-visualizations.scss
=> restyles "backto" links for course rollover and session copying.

addon/components/date-picker.hbs, addon/components/date-picker.js
it was making the date picker too trigger happy.
turns out it is not necessary in order to close the picker.
tested with latest FF and Chrome on Linux.
fixes https://github.com/ilios/common/issues/1838
=> removes click-event handler

addon/components/ilios-course-details.hbs, addon/components/ilios-course-details.js
This is confusing as users may believe they're modifying the rollover
process and not the source course. Fixes #1883
=> Prevent editing course when rolling over

tests/integration/components/weekly-calendar-test.js
lastest FF differs from latest Chrome by adding a dot to the abbreviated
month in the french translation.
=> re-established cross-browser compat of this test.

ember-cli-build.js
was seeing 
```
$ SKIP_A11Y=true npm start
> ilios-common@53.0.0 start /home/stefan/dev/projects/common
> ember serve
WARNING: [ember-cli-terser] Passing options as `ember-cli-uglify` in `ember-cli-build.js` is deprecated, please update to passing `ember-cli-terser` (with a `terser` property) instead.
Build successful (55605ms) – Serving on http://localhost:4200/
```
this fixes it.
=> fixes deprecation warning with code uglifier plugin.

tests/dummy/config/deprecation-workflow.js
We've fixed this here, but it is still present in some upstream
dependencies.
=> Silence noisy htmlSafe deprecation

addon/classes/resolve-async-value.js
This allows passing an array or null in to ensure some expected value
will exist when this is `@use`ed in another component and alleviating the
need for an interim getter.
Wip:
=> Add a default value to resolve async helper

addon-mirage-support/post-all.js, addon-mirage-support/serializers/application.js, addon-mirage-support/setup.js, addon/components/course-rollover.js, addon/services/fetch.js
Along with the new method to fetch mirage will now handle these types of
requests for all types.
Breaking change here as I modified the API for the fetch service to be clearer about what each method does. We're only using this in one place in the frontend (CI rollover).
=> [breaking] Add tools for saving multiple records

addon/components/detail-learning-materials.hbs, addon/components/detail-learning-materials.js
This speeds up sorting significantly in a large list and hopefully makes
the wait-saving indicator unnecessary.
Refs https://github.com/ilios/frontend/issues/5900
=> Only save materials where sort order has changed

.lint-todo/5077b9a88e353e88925c9ff5f4845cb86c7f0d9e/05e0a66d.json, .lint-todo/5077b9a88e353e88925c9ff5f4845cb86c7f0d9e/ae7a667d.json, .lint-todo/5077b9a88e353e88925c9ff5f4845cb86c7f0d9e/c6115fd4.json, .lint-todo/66a80d717c842239644183ea863f951b9c273ebd/7bfd7a55.json, .lint-todo/735d2bc4ad1637ea8a3dcdd63ec79d80db222fa3/45dc51ca.json, .lint-todo/735d2bc4ad1637ea8a3dcdd63ec79d80db222fa3/c19b1c5d.json, .lint-todo/735d2bc4ad1637ea8a3dcdd63ec79d80db222fa3/d301ab54.json, .lint-todo/7599b5483bab23dcde74e801176076e0698f2271/db7d632a.json, .lint-todo/8c7b240729f8862a4652bb3ffa0812d67a4aa0da/d02f2b67.json, .lint-todo/8fdb7cc4aaf78b1f73b74bd54959b28524be891a/3b4e99a9.json, .lint-todo/98d5b0d8912173857f36c09ba2254b035dfcfd99/2529eae6.json, .lint-todo/98d5b0d8912173857f36c09ba2254b035dfcfd99/9627f171.json, .lint-todo/98d5b0d8912173857f36c09ba2254b035dfcfd99/dc01ff5d.json, .lint-todo/98d5b0d8912173857f36c09ba2254b035dfcfd99/fdc81133.json, .lint-todo/a2ae7dbd9aaa86f08aba7ffcca14d9a21bf45aae/2529eae6.json, .lint-todo/a2ae7dbd9aaa86f08aba7ffcca14d9a21bf45aae/9627f171.json, .lint-todo/a2ae7dbd9aaa86f08aba7ffcca14d9a21bf45aae/dc01ff5d.json, .lint-todo/a2ae7dbd9aaa86f08aba7ffcca14d9a21bf45aae/fdc81133.json, .lint-todo/c56202826c74d57c20e26940ff39afa0d9a5c80c/5be4b85b.json, .lint-todo/c7a194150adcec846996944a64c77350b4386dec/4980f4aa.json, .lint-todo/c982cb6ee21291ba845aef4b21ee9ecae77c20eb/28a8be72.json, .lint-todo/c982cb6ee21291ba845aef4b21ee9ecae77c20eb/31178565.json, .lint-todo/c982cb6ee21291ba845aef4b21ee9ecae77c20eb/616b9994.json, .lint-todo/c982cb6ee21291ba845aef4b21ee9ecae77c20eb/6336000f.json, .lint-todo/c982cb6ee21291ba845aef4b21ee9ecae77c20eb/9ca5b97b.json, .lint-todo/c982cb6ee21291ba845aef4b21ee9ecae77c20eb/ffdf2df3.json, .lint-todo/d0a0bf4b65e30f84ac68d61498d19916a1a937c0/9ec0f267.json, .lint-todo/e7e21d78976746a29fc6ff7a8bf55bc9d6880222/4f64a450.json, .lint-todo/f25f18aea175f7423cdb65dd174bd66d56ba3d0f/edfcde31.json, package-lock.json
Removed old linting issues that are no longer relevant with the latest
version of ember-template-lint
=> Update Transitive Dependencies

addon/services/api-version.js, addon/services/current-user.js, addon/services/ilios-config.js, addon/services/permission-matrix.js, tests/dummy/config/deprecation-workflow.js
We needed to add some required attributes to our deprecation notices to
avoid throwing a second notice.  Also added more context info to help
with tracking these down.
=> Fix deprecation deprecations

addon/modifiers/autofocus.js, app/modifiers/autofocus.js, tests/integration/modifiers/autofocus-test.js
This allows us to place focus easily within an element as soon as it is
inserted.
=> Add autofocus modifier

addon/components/not-found.hbs
something i noticed while click-testing the LTI dashboard app, where the "dashboard" route doesn't exist (it's the application route there).
=> check if dashboard route exists before linking to it.

addon/decorators/validation/length.js
needed in frontend for validating user passwords since they don't have an upper boundary for length.
this turned into a more substantial rewrite, of note are:
- checking the length of the constraints array turned out to be pointless. it is always 2. instead, check if the values in that array are `undefined` to verify that actual parameters were provided.
- use the [`isBlank`](https://api.emberjs.com/ember/release/functions/@ember%2Futils/isBlank) utility function to check whether the given value is empty or not.
- input processing in the `validate()` and `defaultMessage()` methods was slightly different and have been realigned.
=> rework Length validation decorator to work on minimum-only input.

app/styles/ilios-common/components/daily-calendar.scss, app/styles/ilios-common/components/progress-bar.scss, app/styles/ilios-common/components/weekly-calendar.scss, app/styles/ilios-common/mixins/ilios-table.scss
This is required due to the deprecation of / for division in SASS.
Fixes #2151
=> Replace slash with math.div

app/styles/ilios-common/components/daily-calendar.scss, app/styles/ilios-common/components/weekly-calendar.scss
We use span 50 and fractions of that to place events on the calendar
along side other events at the same time. This mostly worked, but
without specifying the number of columns in the grid sometimes it
overflows on mobile. This fix uses 50 evenly spaced columns to fill out
each day of the calendar.
Fixes #2157
=> Give the events grid some columns

.github/workflows/auto-merge.yml
Using the github provided dependabot metadata action we can now
introspect pull requests to determine if they meet our criteria for
auto-merging. For now I've enable only those that where test coverage is
assured or that are part of the build.
=> Automerge some PRs

addon/components/course-editing.hbs, addon/components/course-leadership-expanded.hbs, addon/components/course-leadership-expanded.js, addon/components/session-leadership-expanded.hbs, addon/components/session-leadership-expanded.js, tests/integration/components/course-leadership-expanded-test.js, tests/integration/components/session-leadership-expanded-test.js
the `isCollapsed` getters did not correctly recompute on leadership changes, among other things.
i threw this logic and other related state-management code out altogether in favor of a a less convoluted solution that _always_ let's the user expand/collapse the leadership components 
fixes #2188
=> always allow toggling of session/course leadership expanded/collapsed view

tests/dummy/app/index.html, tests/dummy/app/templates/application.hbs, tests/index.html
In order for this addon to work in the dummy app the title can't be in
index.html and we need to specify a root title for the application.
Fixes #2169
Supersedes #2170
=> Configure page-title

config/ember-try.js
for reference: https://emberjs.com/releases/lts/
=> drop older LTS in favour of current one.

addon-test-support/ilios-common/page-objects/components/course-visualize-session-types.js, addon/components/course-visualize-instructors.js, addon/components/course-visualize-session-type.js, addon/components/course-visualize-session-types.hbs, addon/components/visualizer-course-instructors.js, addon/components/visualizer-course-session-types.hbs, addon/components/visualizer-course-session-types.js, app/styles/ilios-common/components/course-visualize-session-types.scss, tests/integration/components/course-visualize-session-types-test.js, tests/integration/components/visualizer-course-session-types-test.js
fixes #2227 
this adds the filter box to the course/session-type visualizations that already exists for course/instructors.
=> Session type filter visualizations

app/styles/ilios-common/components.scss, app/styles/ilios-common/components/dashboard-materials.scss, app/styles/ilios-common/components/learningmaterial-manager.scss, app/styles/ilios-common/components/my-materials.scss, app/styles/ilios-common/components/single-event-learningmaterial-list.scss, app/styles/ilios-common/components/timed-release-schedule.scss, app/styles/ilios-common/components/week-glance.scss
fixes #2252 
affects:
- my materials
- week at a glance
- dashboard materials
- single event details
=> de-emphasize timed-release information on dashboard-related screens

package-lock.json, tests/unit/services/fetch-test.js
This aligns with reality.
This fixes issues with out tests, but I'm not sure why it is necessary and what dependency update is making it necessary. I'm going to leave this in draft while I figure that out, otherwise we might have to repeat this exercise in a few days.
Ugh... and of course now the original test is failing. Something annoying here... investigating....
OK, cause is `pretender` and I've upgraded it here as well.
=> Fix capitalization of header in test

addon/components/learning-material-uploader.hbs
This should be camel cased as of v4.0 of this library.
=> Fix file upload event

tests/integration/components/sessions-grid-test.js
Otherwise we get a console error that helper:sortBy can't be looked up.
=> Use explicit sortBy

addon-test-support/ilios-common/page-objects/components/user-name-info.js, addon/components/user-name-info.hbs, tests/integration/components/user-name-info-test.js
This allows passing id in particular so the component can be used as an
arial-labeledby property.
=> Add attributes to UserNameInfo component

.github/workflows/ci.yaml, .github/workflows/future-ci.yaml, .github/workflows/release.yaml, .github/workflows/update-transitive-dependenies.yaml
12 and 14 are the two current node LTS versions, 10 is no longer
supported. Update our CI strategy to match.
=> Update CI to current node versions

.github/dependabot.yml, package-lock.json, package.json
Going back to v1 as v2 doesn't work with our frontend configuration.
Also locked this in on dependabot as we can wait for an ember-cli
version which includes this update and may handle more issues.
=> Back out of ember-auto-import update

addon/controllers/mymaterials.js, addon/templates/mymaterials.hbs
Instead of empty strings this uses null for the defaults making it
easier to work with the public router service and to migrate later when
ember makes changes.
=> Improve Query Params on MyMaterials Controller

addon-test-support/ilios-common/page-objects/components/single-event.js, addon/components/single-event.hbs, addon/components/single-event.js, tests/integration/components/single-event-test.js
This allows those with elevated privileges to navigate directly to the
session for an event from the single event details page.
Fixes #2362
=> Add link to session to single event details

addon/components/session-copy.js, tests/integration/components/session-copy-test.js
This won't work because on the other side of the relationship a session
can't have more than one postrequisite.
Fixes #2368
=> Don't copy prerequisites when copying session

addon/components/ilios-calendar-multiday-events.hbs, addon/components/ilios-calendar-pre-work-event.hbs, addon/components/ilios-calendar-pre-work-events.hbs, addon/components/week-glance-pre-work.hbs, app/styles/ilios-common/components/ilios-calendar-multiday-events.scss, app/styles/ilios-common/components/ilios-calendar-pre-work-events.scss, app/styles/ilios-common/components/week-glance-pre-work.scss
Align the heading number and position so headings fall in order. Also
removed headings from several places where we were using them mainly for
styling and not content.
=> Rework dashboard headings

.github/workflows/update-transitive-dependenies.yaml
It was incorrect, just use the job name.
=> Remove test name

addon/routes/course-materials.js, addon/routes/course-visualizations.js, addon/routes/course-visualize-instructors.js, addon/routes/course-visualize-objectives.js, addon/routes/course-visualize-session-types.js, addon/routes/course-visualize-vocabularies.js
We were relying on the automatic model hook here, but that will soon be
deprecated.
=> Add explicit model hooks to course routes

addon/components/timed-release-schedule.hbs, addon/components/timed-release-schedule.js, app/styles/ilios-common/mixins/font-size.scss, tests/integration/components/daily-calendar-event-test.js, tests/integration/components/single-event-learningmaterial-list-test.js, tests/integration/components/timed-release-schedule-test.js, tests/integration/components/weekly-calendar-event-test.js
Instead of scaling from phone to desktop this keeps us at 16px until we
gt up to laptop size and then scales up to the 20x for larger screens.
=> Scale fonts in a smaller range

addon/services/ilios-config.js, tests/unit/services/ilios-config-test.js
Couple of gotchas with this value, the main one is I didn't want to bump
the API version so we can't guarantee the value, but that's OK because
depending on the build config it could be missing anyway so we gotta
account for that in any case.
=> Add appVersion to config service

tests/dummy/config/deprecation-workflow.js
This finally has an id and can be silenced! Yay! We'll still need to fix
it, but at least our tests are more readable now.
=> Silence super noisy ember global deprecation

addon/routes/course.js
This is needed here and we're relying on default injection which is
going away in ember-data v4.
=> Inject a missing store

addon-test-support/ilios-common/helpers/has-focus.js, addon-test-support/ilios-common/index.js, addon-test-support/ilios-common/page-objects/components/search-box.js, tests/dummy/config/deprecation-workflow.js
Ember page object deprecated the "is" helper. In our case, finding
focus, we need a custom helper to replace it.
=> Replace usage of is helper in EPO tests

addon-test-support/ilios-common/page-objects/components/ilios-calendar-month.js, addon-test-support/ilios-common/page-objects/components/ilios-calendar-multiday-event.js, addon-test-support/ilios-common/page-objects/components/ilios-calendar-multiday-events.js, addon-test-support/ilios-common/page-objects/components/ilios-calendar-pre-work-events.js, addon-test-support/ilios-common/page-objects/components/monthly-calendar.js, addon/components/ilios-calendar-month.hbs, addon/components/ilios-calendar-month.js, addon/components/ilios-calendar-multiday-events.hbs, addon/components/ilios-calendar-pre-work-events.hbs, addon/components/monthly-calendar.hbs, tests/integration/components/ilios-calendar-month-test.js, tests/integration/components/ilios-calendar-multiday-event-test.js, tests/integration/components/ilios-calendar-multiday-events-test.js, tests/integration/components/ilios-calendar-pre-work-event-test.js, tests/integration/components/ilios-calendar-pre-work-events-test.js
this is the quick- and easy fix getting multi-day events on the display, it's also consistent on how it's handled on other calendar displays (month and day view).
refs #2524
todo:
=> adds multiday events display to monthly calendar view.

addon/components/detail-learning-materials.hbs
=> applies correct "link button" style.

addon/components/copy-button.hbs, addon/components/copy-button.js, app/components/copy-button.js, package-lock.json, package.json, tests/integration/components/copy-button-test.js
Since we're only copying text that we know about and we don't need to
read it from another element it looks like all of our targeted browsers
support this simple method of getting the data onto the clipboard. Thus
allowing us to remove this seldom updated addon.
=> Replace clipboard addon with component

package-lock.json, package.json
This version will be compatible with mirage releases and since we've
cleared all deprecations we can move forward with it a bit early.
=> Upgrade to ember-file-upload v5-beta

app/helpers/-set.js, app/helpers/has-many-ids.js, app/helpers/has-route.js, app/helpers/sort-by-position.js, app/helpers/split.js, app/utils/query-utils.js
Seems like the ember blueprints have change a few times here and we've
been left with a couple of places where we're exporting something that didn't
actually exist.
=> Fix exports

.github/workflows/ci.yaml
Removing this line will start failing our builds when these tests fail.
Getting close, want to have a place to see build status officially as we close the last few gaps.
=> Require embroider tests to pass

.github/workflows/ci.yaml, .github/workflows/future-ci.yaml, .github/workflows/release.yaml, package-lock.json, package.json
Now that embroider is better up to date across our dependencies we no
longer need the override option in package.json and can relax our
required node version.
=> Restore node 14.x support

.github/dependabot.yml
This will ensure our actions are running on the latest versions.
=> Add github actions to dependabot updates

app/styles/ilios-common/mixins/ilios-table.scss
Otherwise long names with underscores break the layout.
Fixes https://github.com/ilios/frontend/issues/3415
=> Break table columns with no spaces

app/styles/ilios-common/mixins/ilios-table.scss
the problem was introduced with https://github.com/ilios/common/pull/2676
using `overflow-wrap` seems to be a better way to break text. 
see https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
=> use a different CSS property to break text in tables.

tests/integration/components/course-visualize-instructors-test.js
This get's held up being resized and we need to wait for the bars to
load before checking on them.
=> Wait for bars in flakey test

addon/models/learner-group.js, tests/unit/models/learner-group-test.js
Our API always represents this as a set with users in subgroups also
existing in the parent. When we fetch this tree for all users in
subgroups we also have to call unique to avoid a lot of duplicates.
Fixes ilios/ilios#3936
=> Fix learner group descendant users

addon/controllers/course/index.js, tests/acceptance/course/sessionlist-test.js
As this is consumed by a getter now and not by the template it doesn't
get autotracked.
Fixes ilios/ilios#3941
=> Track session sorting param

addon/components/pagedlist-controls.hbs, tests/integration/components/pagedlist-controls-test.js
limitless really means data loading callbacks get fired when pagination
is used. so while fast-backwards would work, fast-forward won't (we
don't know the total number of records in advance).
this fixes a regression that was introduced with release v66.0.1 and manifested itself in the frontend's user admin view.
=> removes fast-forward/backwards controls if pagination runs in "limitless" mode

addon/components/editable-field.hbs, addon/components/truncate-text.hbs, addon/components/truncate-text.js, config/icons.js, tests/integration/components/editable-field-test.js, tests/integration/components/truncate-text-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
fixes https://github.com/ilios/common/issues/2748
should also be tested with edit-in-place components that can receive "overlong" text, like the session description editor.
=> adds collapser to truncated text

addon/components/week-glance-event.hbs
links in paragraph are styled as underlined, changing the container
gets rid of that.
fixes #2795
=> converts paragraph to link.

app/styles/ilios-common/mixins/font-size.scss
a11y rules require 9px to be the smallest size, our original step was
calculating to 8px, on most displays where we have a 16px body font
size. Using max ensures that we keep a minimum of 9px while allowing it
to grow at larger base size values.
=> Set a 9px minimum font size

addon/routes/dashboard.js
replaceWith changes to the new route without adding an entry in the
browser history, since this redirect happens without any interim content
it's the right API to use here.
=> Improve dashboard router transition

addon-test-support/ilios-common/page-objects/components/user-name-info.js, addon/components/user-name-info.hbs, addon/components/user-name-info.js, addon/models/user.js, config/api-version.js, tests/integration/components/user-name-info-test.js
Pronouns will be available in the API and should be reflected in both
the user model and the component we use to display detailed name
information.
Refs ilios/ilios#4020
=> Add pronouns to user model and component

index.js, tests/dummy/app/index.html, tests/index.html
This is included in the ember blueprints now for index.html and pushing
our own title into the app causes issues with ember page title.
Also got rid of the old IE compatible tag as this was a lie! We don't support IE 😀
=> Don't push <title> in the build

addon-test-support/ilios-common/page-objects/components/mesh-manager.js, addon/components/mesh-manager.hbs, addon/components/mesh-manager.js, app/styles/ilios-common/components/mesh-manager.scss, tests/acceptance/course/learningmaterials-test.js, tests/acceptance/course/mesh-test.js, tests/acceptance/course/objectivemesh-test.js, tests/acceptance/course/session/learningmaterials-test.js, tests/acceptance/course/session/mesh-test.js, tests/acceptance/course/session/objectivemesh-test.js, tests/integration/components/course/manage-objective-descriptors-test.js, tests/integration/components/mesh-manager-test.js, tests/integration/components/session/manage-objective-descriptors-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
- close search results and reset search value if user clicks outside of
search results
- enables live search, our backend can handle it.
- rm obsolete submit search button
- adds text label
- corrects styles of loading indicator and no search results found.
fixes #1907
=> MeSH search refactoring.

addon-test-support/ilios-common/page-objects/components/session-details.js, addon/components/session-offerings-list.hbs, app/styles/ilios-common/components/offering-manager.scss, app/styles/ilios-common/components/session-offerings-list.scss, tests/acceptance/course/session/offerings-test.js
brings details and timing info up to the same vertical level rather than
stacking
puts more emphasis onto start/end of multiday events and drops
"multiday" label since this seems kinda redundant.
fixes https://github.com/ilios/common/issues/2842
=> re-layouts offering list items grid.

addon-test-support/ilios-common/page-objects/components/dashboard/materials.js, addon/components/dashboard/materials.hbs, app/styles/ilios-common/components/dashboard/materials.scss, tests/acceptance/dashboard/materials-test.js, tests/integration/components/dashboard/materials-test.js
For a11y we need continuity in our titles from h1,h2,h3 without the h2
in this component we lose that on the dashboard.
=> Add title to dashboard materials

app/styles/ilios-common/components/dashboard/view-picker.scss, tests/dummy/app/styles/app.scss
Removed the global margin on main so we can move closer to the top or
the page and then set the space under the buttons to be a pleasing ratio
to the space above them.
Fixes ilios/ilios#4150
=> Balance whitespace at the top of the dashboard

addon-test-support/ilios-common/page-objects/components/new-learningmaterial.js, addon/components/new-learningmaterial.hbs, addon/components/new-learningmaterial.js, tests/integration/components/new-learningmaterial-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
since the class-validator library still doesn't jive with ember-intl, our options are to either inject a lang-key override into the `NotBlank()` validator, create yet another custom validator class, or use our golden hammer `Custom()` validator class.
I opted for the third option since it seems to be the most reasonable out of the three kludges. :shrug: 
fixes https://github.com/ilios/common/issues/2894
=> customize validation and error message for LM file upload.

app/styles/ilios-common/components/course-details.scss, app/styles/ilios-common/components/course-session.scss
fixes #2906 
that's as much as i can squeeze here.
=> reduce space between course details and session details

app/styles/ilios-common/mixins/ilios-table.scss
Bad math here, was lightening all the way to white. This moves it back
to a very light grey.
Fixes ilios/ilios#4185
=> Fix zebra stripe color

app/styles/ilios-common/mixins/ilios-table.scss
This lowers the total visual space of a table compacting rows together.
Fixes ilios/ilios#4161
=> Reduce Padding in Tables

app/styles/ilios-common/mixins/ilios-table.scss
Padding both the right side of all tables as well as interior columns to
ensure they don't bump up on the border.
=> Pad a bit more in table items

addon/components/detail-learning-materials.hbs, app/styles/ilios-common/components/session-details.scss, app/styles/ilios-common/mixins/collapsed-container.scss, app/styles/ilios-common/mixins/ilios-table.scss
For reasons that are very web you can't apply the sticky to a thead
element, you have to apply it to the th. Since our colors were on the
thead and once they rolled down it disappeared I had to add the color to
the th and make some adjustments elsewhere. We don't really need this
anywhere in common, but possibly on a very long list of LMs so I added
the style there.
=> Add a class to create sticky table headers

addon/services/loading-opacity-tracker.js
`delete` does not work on return values from functions.
`Map.prototype.clear()` does not take an argument. (Perhaps
`Map.prototype.delete()` was intended instead?)
=> chore: remove superfluous complexity in clear()

addon/routes/course.js
The implicit model behavior of ember now causes some deprecation
warnings from ember-data so let's ensure we have a hook.
=> Add Explicit Model Hook for Course

addon-test-support/ilios-common/page-objects/components/single-event-learningmaterial-list.js, addon/components/single-event-learningmaterial-list.hbs, app/styles/ilios-common/components/single-event-learningmaterial-list.scss, tests/integration/components/single-event-learningmaterial-list-test.js, tests/integration/components/single-event-test.js
Adding some space and a border to the prework events makes it clearer
where one starts and the other ends.
Fixes #2959
=> Restructure prework materials for single events

addon-test-support/ilios-common/page-objects/components/course-visualize-instructors.js, addon-test-support/ilios-common/page-objects/components/visualizer-course-instructors.js, addon-test-support/ilios-common/page-objects/course-visualizations-instructors.js, addon/components/visualizer-course-instructors.hbs, addon/components/visualizer-course-instructors.js, tests/acceptance/dashboard/course-visualizations-instructors-test.js, tests/integration/components/course-visualize-instructors-test.js, tests/integration/components/visualizer-course-instructors-test.js
this corrects:
- the display number of instructional minutes across the entire course per instructor,
- the calculation of percentage of how much instructional time each instructor, compared against the total sum of instructional time in the given course
it improves:
- the labeling of chart bars: show minutes instead of the less meaningful percentage value
=> Use resources for course instructors visualizations

addon-test-support/ilios-common/page-objects/components/course-visualize-vocabularies.js, addon-test-support/ilios-common/page-objects/components/course-visualize-vocabulary.js, addon-test-support/ilios-common/page-objects/components/visualizer-course-vocabularies.js, addon-test-support/ilios-common/page-objects/components/visualizer-course-vocabulary.js, addon-test-support/ilios-common/page-objects/course-visualizations-vocabularies.js, addon-test-support/ilios-common/page-objects/course-visualizations-vocabulary.js, addon/components/course-visualize-vocabularies.hbs, addon/components/course-visualize-vocabularies.js, addon/components/course-visualize-vocabulary.hbs, addon/components/course-visualize-vocabulary.js, addon/components/visualizer-course-vocabularies.hbs, addon/components/visualizer-course-vocabularies.js, addon/components/visualizer-course-vocabulary.hbs, addon/components/visualizer-course-vocabulary.js, addon/routes/course-visualize-vocabularies.js, addon/routes/course-visualize-vocabulary.js, tests/acceptance/course-visualizations-vocabularies-test.js, tests/acceptance/course-visualizations-vocabulary-test.js, tests/integration/components/course-visualize-vocabularies-test.js, tests/integration/components/course-visualize-vocabulary-test.js, tests/integration/components/visualizer-course-vocabularies-test.js, tests/integration/components/visualizer-course-vocabulary-test.js
- use async methods instead of resources as applicable
- relabels bars and tooltips on vocabulary terms chart to show total minutes instead of the less meaningful percentage numbers
- improves test coverage
=> reworks course visualizations vocabularies/terms

addon-test-support/ilios-common/page-objects/components/course-visualize-session-type.js, addon-test-support/ilios-common/page-objects/components/course-visualize-session-types.js, addon-test-support/ilios-common/page-objects/components/visualizer-course-session-type.js, addon-test-support/ilios-common/page-objects/components/visualizer-course-session-types.js, addon-test-support/ilios-common/page-objects/course-visualizations-session-type.js, addon-test-support/ilios-common/page-objects/course-visualizations-session-types.js, addon/components/course-visualize-session-types.hbs, addon/components/course-visualize-session-types.js, addon/components/visualizer-course-session-type.hbs, addon/components/visualizer-course-session-type.js, addon/components/visualizer-course-session-types.hbs, addon/components/visualizer-course-session-types.js, addon/routes/course-visualize-session-types.js, tests/acceptance/course-visualizations-session-type-test.js, tests/acceptance/course-visualizations-session-types-test.js, tests/integration/components/course-visualize-session-types-test.js, tests/integration/components/visualizer-course-session-type-test.js, tests/integration/components/visualizer-course-session-types-test.js
- replace any invocations of Resources outside of `@use` with async methods
- improves chart labeling by dropping meaningless percentage from the bars
- fleshes out test coverage
=> reworks course session-types/session-type visualizations

addon/components/detail-learning-materials.hbs, addon/components/detail-learning-materials.js
this scrolls back up to the top of the learning materials list.
fixes https://github.com/ilios/common/issues/3003
=> scroll LM details title back into view after saving or canceling edits/additions of LMs.

addon-test-support/ilios-common/page-objects/components/dashboard/materials.js, addon/components/dashboard/materials.hbs
Now that the checkbox is over on the left side it makes more sense to
have the material title join it on that side of the table.
Fixes ilios/ilios#4280
=> Move material title to the left on dashboard materials

addon/components/single-event.hbs, app/styles/ilios-common/components/single-event.scss
this results in consistent left-hand vertical alignment of all page
elements, at the expense of losing the left hand grey border.
seems worth it to me.
fixes #3023
=> eliminate fieldset elements from single event details page.

addon/components/single-event-learningmaterial-list.hbs, package-lock.json
Empty containers are bad for accessibility.
=> Remove empty container when empty

addon/utils/load-polyfills.js
Both the PluralRules and RelativeTime polyfills require the intlLocale
to be already loading. This mostly worked, but sporadic network delays
could cause them to process out of order and break. Load them
sequentially for the best experience.
Fixes ilios/ilios#4363
=> Load polyfills in order

addon/components/user-search-result-user.hbs
fixes https://github.com/ilios/ilios/issues/4372
(will need a common release in order to take affect in the frontend UI that the linked ticket is referencing)
=> adds icon to user search results to indicate disabled accounts.

app/styles/ilios-common/components/course-visualizations.scss, app/styles/ilios-common/components/course-visualize-instructor.scss, app/styles/ilios-common/components/course-visualize-instructors.scss, app/styles/ilios-common/components/course-visualize-objectives.scss, app/styles/ilios-common/components/course-visualize-session-type.scss, app/styles/ilios-common/components/course-visualize-session-types.scss, app/styles/ilios-common/components/course-visualize-term.scss, app/styles/ilios-common/components/course-visualize-vocabularies.scss, app/styles/ilios-common/components/course-visualize-vocabulary.scss, app/styles/ilios-common/mixins.scss, app/styles/ilios-common/mixins/data-visualization.scss
we're re-using those styles for non-course related visualizations, so
let's make sure this is correctly reflected in the name of the mixin.
refs https://github.com/ilios/frontend/pull/6842
=> gives visualization mixin a more generic name.

app/styles/ilios-common/components/dashboard/materials.scss, app/styles/ilios-common/components/dashboard/week.scss
Now that we've dropped the reports and courses blocks from the dashboard we should use the entire space.
=> Expand dashboard waag and materials to fill space

addon/utils/offering-date-block.js
the first element of an EmberData collection cannot be accessed via array index, b/c it's not an array (yet).
reverting the change introduced in b7b791.
fixes https://github.com/ilios/ilios/issues/4437
=> fixes regression in sorting of offerings in list.

addon/services/locale-days.js, tests/acceptance/dashboard/calendar-test.js, tests/unit/services/locale-days-test.js
Bad original implementation here would get confused on Sunday and move into the prior week.
=> Fix Detection of Start and End of Week

.github/workflows/release.yaml
All of our commits get tested as they get merged having this extra step was a nice bit of additional checking, but it's slowing down releases and if we have a flaky test it is a real problem. So, I'm switching off test tests, we'll only worry about deploying.
=> Stop Testing Before Releasing

addon/components/date-picker.js, tests/acceptance/course/learningmaterials-test.js, tests/acceptance/course/session/learningmaterials-test.js, tests/acceptance/course/sessionlist-test.js
This helps with cross browser support for these tests.
=> Use our internationalization library to format dates

tests/dummy/app/controllers/login.js, tests/dummy/config/environment.js
I've aligned our configuration with the frontend to remove token refresh and updated the login itself to use the token we pass and not a refreshed version. We still attempt to use the token to get a new token to ensure the passed token is valid and when there are errors in that process they will now display correctly.
=> Improve Login Experience

package-lock.json
`npm install` left an updated lock file behind, here it is.
=> update lock file.

addon/components/mesh-manager.hbs
reclaims this space if no terms are selected
refs https://github.com/ilios/ilios/issues/4430
=> don't render selected terms list if none exist.

addon/components/course/objective-list.hbs, addon/components/session/objective-list.hbs
removing the array check from the conditional and just checking is-sorting state fixes the issue of the order manager component not closing after saving.
refs https://github.com/ilios/ilios/issues/4502
=> fixes save-and-close objective sort manager bug.

config/api-version.js
No changes are required in common, this version bump is for GraphQL reporting in the frontend.
=> Bump API to v3.8

app/styles/ilios-common/components/breadcrumbs.scss
the breadcrumb styles were initially defined under the assumption that every crumb contains a clickable link, except for the last element.
that turns out to be too narrow in scope - we need the ability to have non-clickable/non-linked crumbs at arbitrary points in the hierarchy, and _don't_ want them to styled as something actionable (e.g. on  hover). 
the changes proposed here re-apply some of the these hover/focus styles onto anchor tags and remove them from their container elements. 
the rest is cleanup.
for visual regression review, i recommend having a look at course visualizations.
=> breadcrumb style improvements

addon/controllers/dashboard/calendar.js
fixes https://github.com/ilios/ilios/issues/4654
=> resets filters to "Course/Session Type" when filters are hidden.

tests/unit/models/session-type-test.js, tests/unit/utils/calendar-event-tooltip-test.js
These are the results of htmlSafe(ing) a string and the API for accessing the string itself has changed in the latest versions of ember.
=> Replace access to string with toString in tests

addon/components/editable-field.hbs, tests/integration/components/editable-field-test.js
we'll need this in at least one place (namely, the subject report header) to visually indicate edit-in-place fields better - to set them apart from "regular" links.
the span to button conversion is unrelated to this (aka "while i was in there").
=> adds option for showing an edit-icon edit-in-place component

.github/workflows/create_release.yaml
Github has deprecated set-output and requires this new syntax to pass data between steps.
The only way to test this is to run it... so 🤞
=> Replace deprecated set-output in actions

addon/components/course/rollover-date-picker.js
Using luxon here to compare dates in the hopes of clearing up some issues in Safari and also following a recommendation from my IDE to not attempt to optional chain on a private property and instead check the existence the old fashioned way.
=> Small tweaks to course rollover date picker

addon/modifiers/autofocus.js, addon/modifiers/mouse-hover-toggle.js, addon/modifiers/scroll-into-view.js, tests/dummy/config/deprecation-workflow.js
Ember Modifiers v4 has changed the way arguments are evaluated in a modifier, for us this doesn't have much effect because we were consuming all the arguments passed to the modifier anyway.
=> Mark modifiers as non eager for v4

app/styles/ilios-common/components/detail-learningmaterials.scss, app/styles/ilios-common/components/monthly-calendar.scss, app/styles/ilios-common/components/offering-manager.scss, app/styles/ilios-common/components/weekly-calendar.scss, app/styles/ilios-common/mixins/ilios-button.scss, app/styles/ilios-common/mixins/objectives.scss
Just like links, link-buttons should default to a left alignment. I removed any duplicate left-align styles and added center alignment where it seemed warranted. I also removed a double style assignment for the copy button on offering url.
=> Left Align Link Buttons

addon-test-support/ilios-common/page-objects/components/daily-calendar.js, addon-test-support/ilios-common/page-objects/components/monthly-calendar.js, addon-test-support/ilios-common/page-objects/components/weekly-calendar.js, addon/components/daily-calendar.hbs, addon/components/monthly-calendar.hbs, addon/components/weekly-calendar.hbs, app/styles/ilios-common/components/daily-calendar.scss, app/styles/ilios-common/components/monthly-calendar.scss, app/styles/ilios-common/components/weekly-calendar.scss, tests/integration/components/daily-calendar-test.js, tests/integration/components/monthly-calendar-test.js, tests/integration/components/weekly-calendar-test.js, translations/en-us.yaml, translations/es.yaml, translations/fr.yaml
For users of assistive technology it can be confusing to view our calendar which contains a list of days, but may not contain any events. They may no know if there is truly nothing on the calendar or if we've coded our site poorly. This a11y fix ensures that days without events contain a "no events" marker along with being visually empty.
=> Be Explicit About Days With No Events

.github/workflows/auto-merge.yml
We were using the special pull_request_target event here to be able to merge, but now that we're using the github CLI we may be able to do this with a normal pull request event and a checkout.
This might not work, giving it a try.
=> Convert automerge to be a pull request action

.github/dependabot.yml
This is provided by ember-cli blueprints and we don't need to keep it up to date ourselves.
=> Add concurrently to ignored dependencies

.github/dependabot.yml
Since common is a library dependabot tried to only update the lock version. That doesn't work for us, we want to push new things up to frontend so this version should be increased
=> Bump package version when needed

package-lock.json, package.json, tests/dummy/config/ember-try.js
We pinned these at v1 because v2 of embroider had issues with our usage of await in templates. That has been resolved in embroider v3 and we can unlock these now and test with the latest version.
=> Unlock embroider tests

package-lock.json, package.json, tests/dummy/config/dependency-lint.js
This release candidate has improved support for ember beta and canary releases.
=> Update Ember Simple Auth to v6 RC 1

addon/components/course/objective-list-item.hbs, addon/components/taxonomy-manager.js, addon/models/course-objective.js, addon/models/course.js, addon/models/learner-group.js, addon/models/offering.js, addon/models/program-year.js, addon/models/program.js, addon/models/session-type.js, addon/models/session.js, addon/models/user.js, tests/integration/components/course/objective-list-item-test.js, tests/integration/components/session/objective-list-item-test.js, tests/unit/models/learner-group-test.js, tests/unit/models/program-test.js, tests/unit/models/user-test.js
The TrackedAsyncData provides a better way to manage asynchronous state, however it is more verbose and in order to be auto tracked it requires each step in an async getter chain to be explicitly coded. I focused on the testable output of the non-private getters for this change and I think I've replaced our original resources with these new getters. Long term we probably need to remove many of the public getters on models because doing things this way where we can't know exactly where in an async chain a change may happen makes for some verbose and difficult to read code.
=> Replace ResolveAsyncValue in models

addon/models/course-objective.js, tests/unit/models/session-type-test.js
The removeObject method on ember data arrays is deprecated and will be removed.
=> Replace removeObject with splice

addon/components/detail-instructors.js, addon/components/detail-learners-and-learner-groups.js, addon/helpers/sort-by.js
This method is still present on ember-data relationships, but is deprecated and we shouldn't call it.
=> Limit or remove calls to toArray

addon-mirage-support/factories/authentication.js
Username is a string, sending an integer here resolves to null in ember data 4.12+ and breaks some tests in frontend. Making it a full string instead.
=> Fix authentication factory

tests/dummy/config/ember-try.js
Because of an issue with ember data we've had to pin this in frontend so we can do the same here and tests will pass again.
=> Pin embroider test version

.github/dependabot.yml
I synced this with the Ember 4.12 addon blueprint package.json file so we're ignoring everything that ember-cli provides us.
=> Cleanup our dependabot ignore list

addon-mirage-support/factories/course.js, addon-mirage-support/factories/session.js, tests/acceptance/course/session/offerings-test.js, tests/acceptance/course/session/publish-test.js, tests/acceptance/course/sessionlist-test.js, tests/acceptance/dashboard/calendar-test.js, tests/acceptance/dashboard/materials-test.js
In order to make our percy tests more stable I'm freezing several dates and providing default dates to the course and session factories.
=> Freeze some test dates

addon/components/collapsed-competencies.js, tests/integration/components/collapsed-competencies-test.js
This wasn't working for program years because competencies is a direct relationship on that model. Calling reduce on that relationship without loading it first isn't allowed by ember data anymore.
=> Load competencies before working with them

app/styles/ilios-common/components/sessions-grid-header.scss
fixes https://github.com/ilios/ilios/issues/4119
=> prevent overlap by giving sticky header a higher z-index.

app/styles/ilios-common/components/sessions-grid-row.scss
fixes https://github.com/ilios/ilios/issues/4733
=> add some space between title and session type in session grid.

addon/components/daily-calendar.hbs, addon/components/daily-calendar.js, addon/components/weekly-calendar.hbs, addon/components/weekly-calendar.js
in the current implementation, the top navigation is pushed out of view when the daily or weekly calendar is loaded on the dashboard. this violates the first principle of Dave-Driven Design (TM) - "Don't confuse the user".
Since we don't have the level of control over the scrolling behaviour that would allow us to correct this issue, or at least i can't figure out how to do this, our only other option is to remove scroll-into-view functionality from the calendars altogether.
fixes https://github.com/ilios/ilios/issues/4867
=> rm scrolling feature from calendar views.

tests/dummy/config/ember-intl.js, translations/en-us.yaml, translations/fr.yaml
This was skipped, I also configured the build to correctly fail tests when any translation is missing.
=> Add missing navigation translation

package-lock.json
something that popped up after running `npm install` on `master`.
=> updates peer dep in lock file.

addon/components/daily-calendar.hbs, addon/components/daily-calendar.js, addon/components/weekly-calendar.hbs, addon/components/weekly-calendar.js
this reverts commit 8c81eba3b3aaf2eea50160ce8d461f340548cb4d
refs https://github.com/ilios/ilios/issues/4867 and https://github.com/ilios/common/pull/3460
side-note: i tried the native [`element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) method as suggested by @jrjohnson, in various configurations. these work just as well as the [`scroll-into-view`](https://www.npmjs.com/package/scroll-into-view) package that we're using throughout the frontend. however, it doesn't solve the general problem of the viewport shifting downwards, so this ends up being a straight-up reversal of https://github.com/ilios/common/pull/3460
=> bring back scroll-into-view for calendars.

addon-test-support/ilios-common/page-objects/components/course-details.js, addon/components/ilios-course-details.hbs, app/styles/ilios-common/components/course-details.scss
fixes https://github.com/ilios/ilios/issues/4921
=> reduce visual surface that the expand/collapse course details button claims on screen.

tests/acceptance/course/cohorts-test.js, tests/acceptance/course/learningmaterials-test.js, tests/acceptance/course/mesh-test.js, tests/acceptance/course/objectivecreate-test.js, tests/acceptance/course/objectiveparents-test.js, tests/acceptance/course/objectiveterms-test.js, tests/acceptance/course/overview-test.js, tests/acceptance/course/publicationcheck-test.js, tests/acceptance/course/session/ilm-test.js, tests/acceptance/course/session/learner-groups-test.js, tests/acceptance/course/session/learningmaterials-test.js, tests/acceptance/course/session/mesh-test.js, tests/acceptance/course/session/objectiveparents-test.js, tests/acceptance/course/session/objectiveterms-test.js, tests/acceptance/course/session/overview-test.js, tests/acceptance/course/session/publish-test.js, tests/acceptance/course/session/terms-test.js, tests/acceptance/course/sessionlist-test.js, tests/acceptance/course/terms-test.js, tests/acceptance/dashboard/calendar-test.js, tests/acceptance/dashboard/week-test.js
I locked a few dates to lower the number of false positive failure rates we have as well as removing some tests that were very close to or identical with other tests.
=> Adjust Percy Tests

addon-test-support/ilios-common/page-objects/components/back-link.js, addon-test-support/ilios-common/page-objects/events.js, addon-test-support/ilios-common/page-objects/weeklyevents.js, addon/components/back-link.hbs, addon/controllers/events.js, addon/controllers/weeklyevents.js, addon/templates/events.hbs, addon/templates/weeklyevents.hbs, app/controllers/events.js, config/environment.js, tests/acceptance/events-test.js, tests/acceptance/weeklyevents-test.js, tests/integration/components/back-link-test.js, tests/unit/controllers/events-test.js
another attempt at fixing https://github.com/ilios/ilios/issues/4774
this time, we check the environment for the application "name" (`modulePrefix` key). 
note: we can't get to it using `getConfig` from `@ember/macros`, so i'm using the tried/true approach instead.
=> check app env and suppress back-to link in the frontend app.

addon/components/session-publicationcheck.hbs
previously, the scroll-to effect was targeting the container element, which includes the read-only session details above the publication check results table. that wasn't quite cutting it - we want to scroll the results table into view.
fixes https://github.com/ilios/ilios/issues/4922
=> sets the publication check target as scroll target.

addon/components/detail-taxonomies.hbs, addon/components/detail-taxonomies.js
this affects all the places where we're using the taxonomy manager - sessions, courses, and program-years.
fixes https://github.com/ilios/ilios/issues/3839
=> scrolls taxonomy manager into view when edit-mode is activated.

.github/dependabot.yml
These are in the ember blueprint, we'll let them drift naturally when we update our package lock file, but otherwise leave them alone.
=> Skip updating blueprint provided packages

addon/serializers/school-config.js, app/serializers/school-config.js
Before sending this value to the API it needs to be a string, however ember-data takes the boolean false and converts it into a null so we need to do a bit of special handling in this case.
Refs ilios/ilios#4953
=> Serialize false in school config

addon/models/learner-group.js, tests/unit/models/learner-group-test.js
This method was designed to only modify, and only return, groupss which were modified which is nice because it limits network requests when modifying groups trees with lots of subgroups. This turns out to be a bad idea however because users may open multiple tabs and modify the group tree in each tab. Any user errors in this process can lead to changes not being reflected back to the API because the data store in the tab they have open does not realize a change to other groups is necessary. I've removed that optimization here. It's less network efficient, however it should result in consistent data being sent to the API.
Refs ilios/ilios#4953
=> Remove optimization for saving learner groups

tests/dummy/config/ember-try.js
When this is fixed upstream we won't need this anymore. Not sure if that's true yet, but would like to have this dependency canary to keep track of. 🐦 
Reverts #3433
=> Unpin embroider test versions

.github/workflows/ci.yml, .github/workflows/percy.yml, .github/workflows/update-transitive-dependencies.yaml
We keep running out of screen shots, this limits the number of percy runs we have by requiring a label or manual run.
=> Reduce Percy Runs

addon/components/session-offerings-list.hbs, addon/components/sessions-grid-offering-table-offerings.hbs, addon/components/sessions-grid-offering-table.hbs, addon/utils/offering-date-block.js, tests/acceptance/course/session/offerings-test.js, tests/unit/utils/offering-date-block-test.js
These toFormat calls were not localized and are not needed anymore, let's replace them with the helper that makes everything much nicer.
=> Deprecate and replace date formatting getters

.github/workflows/percy.yml
Otherwise this cancels the CI run because they have the same identifier.
=> Fix group of percy tests

package.json
We no longer even bundle npm-run-all so this hasn't worked in a while. Our CI job for browserstack just does these steps inline.
=> Remove unused browserstack npm script

tests/integration/components/ilios-calendar-event-month-test.js
This test doesn't work on android chrome because the high resolution screen causes the browser there to make border adjustments unpredictably. Thanks google, aren't you sweet.
=> Remove flaky test

app/styles/ilios-common/components/single-event-learningmaterial-list.scss
This spacing got dropped at some point in the distant past when fa-icon stopped being applied to all icons.
=> Fix spacing in lm list notes icon

addon/components/fa-icon.hbs
Missed this one in the transition to sprites, adding it back.
=> Restore fixed-width to icons

.github/workflows/percy.yml
This is better than only running it when the label is applied, once the label is on the PR it should run on each change.
=> Re-run the percy job anytime the PR is changed

addon/components/pagedlist-controls.hbs, app/styles/ilios-common/components/pagedlist-controls.scss
This was getting auto-translated by fontawesome for us, but we need the right name now that we've dropped the FA javascript helpers. Also fixes a bug where the fast forward was always blue, even when it should have been disabled.
=> Fix icon name

app/styles/ilios-common/fonts.scss, app/styles/ilios-common/mixins/font-size.scss
Having this in the mixin meant it was included hundreds of times. CSS is fast so this wasn't a huge deal performance wise, but it makes looking at the dev panel annoying and made me feel like a bad developer. Fixed!
=> Consolidate font size information

.github/workflows/release.yaml
Pnpm, in the publish workflow, checks to be sure it is on master. This doesn't work with our workflow because we use a tag. This issue has been open for more than a year ([pnpm](https://github.com/pnpm/pnpm) number 5894) and the only way to get around it is to ignore the git checks here. That's not a big deal as we're in a fresh checkout.
=> Skip some pnpm publish checks

.eslintrc.js, .npmignore, index.js, package.json, pnpm-lock.yaml, tests/dummy/mirage/config.js, tests/test-helper.js
check it out
https://github.com/ember-cli-code-coverage/ember-cli-code-coverage
to run:
`pnpm run coverage`
the output will be generated in a `coverage` directory in the project's root.
sample output
=> Ember CLI code coverage

packages/ilios-common/index.js
Leaving this on results in a browser warning that we didn't use the assets we pre-loaded. Let's turn it off instead.
=> Turn off asset pre-loading in tests

packages/test-app/tests/test-helper.js
This file doesn't exist and as we don't use the a11y tools outside of tests doesn't have any value for us. It was, however, throwing a bazillion errors into the console for every invocation of a11yAudit so I'm turning it off.
=> Disable preloading axe test-support.css

packages/test-app/tests/unit/services/timezone-test.js
adding a kludge to deal with environments that serve up a timezone offset instead of an IANA timezone name.
=> work around test environments that don't know their timezone.

.github/workflows/tag_version.yaml
We've always used this, let's keep doing that.
=> Add v prefix back into tags

packages/test-app/package.json, pnpm-lock.yaml
This is no longer needed in an embroider and pnpm world, plus it was throwing a weird build error.
=> Remove dependency lint addon

packages/test-app/ember-cli-build.js
We're not using dotenv anymore for managing environmental variables.
=> Remove dotenv config

.github/workflows/tag_version.yaml
Because we're not actually doing anything with pnpm this breaks in the cleanup step. Remove this unneeded stuff.
=> Remove pnpm and cache from tag workflow

packages/ilios-common/app/styles/ilios-common/components/lm-icons.scss
The start for required learning material icons got slightly displaced when I updated the way we import and style icons. This puts it back into a visible spot.
=> Restore required icon styling

packages/ilios-common/addon/controllers/events.js, packages/ilios-common/addon/controllers/weeklyevents.js
We're changing the name of the frontend app from ilios to frontend as part of migrating to a monorepo setup. For now, hide the back link from both application names.
=> Hide back link for frontend

package.json, packages/ilios-common/package.json, pnpm-lock.yaml
This isn't working with pnpm as it builds node_modules in a different way. We may replace it. Or just remember to run lint before each commit.
=> Remove pre-commit
