- addon/templates/components/week-glance.hbs
- app/styles/ilios-common/components/big-text.scss
- app/styles/ilios-common/components/week-glance.scss
- app/styles/ilios-common/mixins/ilios-list.scss
- app/styles/ilios-common/styles.scss
- tests/integration/components/week-glance-test.js
Fixes requested at https://github.com/ilios/frontend/issues/3041
> Updates to week at a glance

- addon/components/ics-feed.js
- addon/locales/en/translations.js
- addon/locales/es/translations.js
- addon/locales/fr/translations.js
- addon/templates/components/dashboard-calendar.hbs
- addon/templates/components/ics-feed.hbs
- app/components/ics-feed.js
- package.json
- tests/integration/components/ics-feed-test.js
fixes #7 
this requires a new version of this add-on to be published to npm.
> Bring back ics feed component

- addon/components/single-event.js
- tests/integration/components/single-event-test.js
> show public notes in event details

- package-lock.json
- package.json
> chore(package): update ember-cli to version 2.14.2

- addon/components/week-glance.js
- addon/templates/components/week-glance.hbs
frontend acceptance test were failing, need to be more defensive in dealing with NULL values for attributes.
refs #17.
refs ilios/frontend#3136.
to illustrate the problem:
> deal with NULL input better

- README.md
> fixed typo.

- addon/components/ilios-calendar-week.js
- addon/templates/components/ilios-calendar-week.hbs
- tests/integration/components/ilios-calendar-week-test.js
When we want to display the calendar, but not make anything live we can
use these options.
Refs ilios/frontend#2061
> Display weekly calendar with no interaction

- addon/components/dashboard-calendar.js
- addon/locales/en/translations.js
- addon/locales/es/translations.js
- addon/locales/fr/translations.js
- addon/mixins/tooltip-content.js
- addon/templates/components/ilios-calendar-day.hbs
- addon/templates/components/ilios-calendar-month.hbs
- addon/templates/components/ilios-calendar-week.hbs
> added missing "Due This Day" verbiage to event tooltip

- addon/locales/en/translations.js
- addon/locales/es/translations.js
- addon/locales/fr/translations.js
- addon/templates/components/dashboard-materials.hbs
- addon/templates/components/single-event-learningmaterial-list.hbs
- addon/templates/components/week-glance.hbs
- tests/integration/components/dashboard-materials-test.js
- tests/integration/components/dashboard-week-test.js
- tests/integration/components/lm-type-icon-test.js
- tests/integration/components/single-event-learningmaterial-list-test.js
- tests/integration/components/week-glance-test.js
refs ilios/frontend#3038
week-at-a-glance/weekly events:
dashboard materials:
single event:
> Inline and Download links for PDF learning materials

- addon/models/program-year.js
- tests/unit/models/program-year-test.js
> deprecate program-year::domains() in favour of program-year::competencyDomains()

- addon/models/cohort.js
- tests/unit/models/cohort-test.js
> deprecated topLevelLearnerGroups in favour of rootLevelLearnerGroups.

- addon/models/ilm-session.js
- tests/unit/models/ilm-session-test.js
refs #33
i couldn't find any usage of this CP, neither in common nor in frontend. so i yanked it. please double-check, thanks!
> remove unused allInstructors CP from ILM session model

- addon/models/mesh-descriptor.js
> added deleted attr to mesh descriptor model.

- addon/models/program-year.js
- tests/unit/models/program-year-test.js
> removed unused and deprecated methods.

- addon/models/cohort.js
- tests/unit/models/cohort-test.js
> remove obsolete topLevelLearnerGroups CP.

- addon/models/course-learning-material.js
- addon/models/session-learning-material.js
Corresponds to API updates to allow for the timed release of learning
materials.
Requires ilios/ilios#1908
> Add start / end to learning materials

- addon/models/mesh-concept.js
- addon/models/mesh-term.js
> removed obsolete model properties.

- addon/models/session-description.js
- tests/unit/models/session-description-test.js
> fixed textDescription CP.

- tests/integration/components/week-glance-test.js
> Fixed week at a glance test.

- addon/components/single-event-learningmaterial-list.js
- addon/components/single-event.js
- addon/locales/en/translations.js
- addon/locales/es/translations.js
- addon/locales/fr/translations.js
- addon/templates/components/dashboard-materials.hbs
- addon/templates/components/single-event-learningmaterial-list.hbs
- addon/templates/components/single-event.hbs
- app/styles/ilios-common/components/dashboard-materials.scss
- app/styles/ilios-common/components/single-event-learningmaterial-list.scss
- tests/integration/components/dashboard-materials-test.js
- tests/integration/components/single-event-learningmaterial-list-test.js
- tests/integration/components/single-event-test.js
refs ilios/frontend#3261. 
affects the display of materials in the following areas:
- dashboard materials
- single event details course/session learning materials
> Display blanked user materials as such.

- addon/models/course.js
- addon/models/objective.js
- tests/unit/models/objective-test.js
> Cleaned up offering::treeCompetencies() CP

- addon/models/learner-group.js
> Cleaned up learner-group::courses() CP

- addon/models/learner-group.js
> Cleaned up learner-group::allDescendants CP

- addon/models/learner-group.js
- tests/unit/models/learner-group-test.js
> refactored subgroupNumberingOffset CP as async function w/o using DS promises.

- addon/models/learner-group.js
- tests/unit/models/learner-group-test.js
refs #33.
i'm somewhat stumped that the previously written tests did not withstand the conversion to async and had to be smashed up.
> refactored allDescendantUsers CP as async function 

- addon/models/objective.js
- tests/unit/models/objective-test.js
> refactored topParents as async function w/o using DS promises.

- addon/models/user.js
- tests/unit/models/user-test.js
this includes _the mother of all computed properties_ - `allRelatedCourses`. 
refs #33.
> refactored CPs in User model w/o using DS promises

- addon/mixins/events.js
- tests/unit/mixins/events-test.js
added a new method for retrieving course from event.
added test coverage.
refs #75
> re-wrote all methods in events mixin as async functions.

- addon/services/school-events.js
- addon/services/user-events.js
- tests/integration/services/school-events-test.js
- tests/integration/services/user-events-test.js
- tests/unit/services/school-events-test.js
- tests/unit/services/user-events-test.js
> cleaned up user-events service. use async functions as applicable.

- .travis.yml
- package.json
- testem.js
- tests/dummy/app/app.js
- tests/dummy/app/router.js
- tests/dummy/config/environment.js
- tests/helpers/destroy-app.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
- yarn.lock
> Greenkeeper/ember cli 2.16.2

- addon/models/learner-group.js
- addon/models/session.js
- addon/models/term.js
- addon/models/vocabulary.js
- tests/unit/models/learner-group-test.js
- tests/unit/models/session-test.js
- tests/unit/models/term-test.js
- tests/unit/models/vocabulary-test.js
> use comp properties correctly.

- addon/components/dashboard-calendar.js
- addon/components/dashboard-materials.js
- addon/components/ilios-calendar.js
- addon/components/single-event.js
- addon/templates/components/dashboard-calendar.hbs
- tests/integration/components/ilios-calendar-test.js
- tests/integration/components/single-event-test.js
> use async/await over explicit promises in components 

- addon/models/user.js
- tests/unit/models/user-test.js
> use async/await syntax in User model.

- addon/models/program-year.js
> Use async/await syntax in Program-year model

- addon/models/cohort.js
> Use async/await syntax in Cohort model.

- addon/models/program.js
- tests/unit/models/program-test.js
> Async/Await syntax and new CPs in the Program model

- addon/mixins/categorizable-model.js
- tests/unit/models/session-test.js
> adopt async/await syntax in categorizable model mixin.

- addon/models/cohort.js
- tests/unit/models/cohort-test.js
> Cohort model fixes

- addon/models/curriculum-inventory-report.js
- tests/unit/models/curriculum-inventory-report-test.js
> Use async/await syntax in Curriculum Inventory Report model

- addon/components/dashboard-calendar.js
> fixed return value in CP.

- addon/models/term.js
- tests/unit/models/term-test.js
> Use async/await syntax in Term model.

- addon/models/instructor-group.js
- tests/unit/models/instructor-group-test.js
> Use async/await syntax in Instructor-group model

- yarn.lock
This update bumps dependencies and hopefully resolves some conflicts.
> Update ember-moment to the latest version

- tests/unit/models/instructor-group-test.js
just something that popped up during testing.
refs #80.
> replaced calls to deprecated includes() method with contains().

- app/models/alert-change-type.js
- app/models/alert.js
> removed last remnants of alert and alert-change-type models.

- addon/models/aamc-pcrs.js
- addon/models/competency.js
- addon/models/vocabulary.js
> rewrote code to fix inflector deprecation.

- addon/models/objective.js
- tests/unit/models/objective-test.js
> async/await for Objective model

- addon/models/school.js
- tests/unit/models/school-test.js
> async/await for School model

- addon/models/offering.js
- tests/unit/models/offering-test.js
> async/await for Offering model

- addon/models/curriculum-inventory-sequence-block.js
- tests/unit/models/curriculum-inventory-sequence-block-test.js
> async/await syntax for Curriculum Inventory Sequence Block model.

- addon/models/curriculum-inventory-report.js
- addon/models/user.js
This is now available in v1.27 of the API and should be reflected in the
models.
Refs ilios/ilios#2013
> Add administrator relationship to CI report

- addon/authenticators/ilios-jwt.js
> switched to async/await notation in ilios/jwt authenticator.

- addon/components/dashboard-calendar.js
Tests are going to be on the frontend
> Clear term filter correctly

- .travis.yml
- addon/templates/components/toggle-buttons.hbs
- addon/templates/components/toggle-icons.hbs
> replaced deprecated one-way-components with pure HTML equivalents.

- addon/components/dashboard-calendar.js
- addon/models/user.js
- addon/templates/components/dashboard-calendar.hbs
This is where the feed is, getting it from the current host was never a
good idea.
> Use the API server to access the ICS feed

- package.json
- yarn.lock
> chore(package): update ember-cli to version 2.18.0

- tests/dummy/app/templates/login.hbs
Replace with plain input element.
Refs #152
> Remove one-way-input

- addon/models/cohort.js
- addon/models/term.js
- addon/models/vocabulary.js
> added "active" attribute to models.

- addon/models/term.js
- tests/unit/models/term-test.js
> added isActiveInTree CP to term model.

- package.json
- yarn.lock
> updated ember promise helper dependency.

- addon/components/toggle-buttons.js
- addon/templates/components/common-dashboard.hbs
- addon/templates/components/dashboard-week.hbs
- app/styles/ilios-common/components/body.scss
- app/styles/ilios-common/components/common-dashboard.scss
- app/styles/ilios-common/components/dashboard-agenda.scss
- app/styles/ilios-common/components/dashboard-calendar.scss
- app/styles/ilios-common/components/dashboard-materials.scss
- app/styles/ilios-common/components/dashboard-view-picker.scss
- app/styles/ilios-common/components/dashboard-week.scss
- app/styles/ilios-common/components/single-event.scss
- app/styles/ilios-common/components/toggle-buttons.scss
- app/styles/ilios-common/components/week-glance.scss
- app/styles/ilios-common/mixins.scss
- app/styles/ilios-common/mixins/ilios-button.scss
- app/styles/ilios-common/mixins/ilios-fieldset.scss
- app/styles/ilios-common/mixins/ilios-heading.scss
- app/styles/ilios-common/mixins/ilios-input.scss
- app/styles/ilios-common/mixins/ilios-link.scss
- app/styles/ilios-common/mixins/ilios-list.scss
- app/styles/ilios-common/mixins/ilios-select.scss
- app/styles/ilios-common/mixins/ilios-table.scss
- app/styles/ilios-common/mixins/ilios-textarea.scss
- app/styles/ilios-common/mixins/media.scss
- app/styles/ilios-common/mixins/visually-hidden.scss
- app/styles/ilios-common/variables.scss
- config/environment.js
- index.js
- package.json
- yarn.lock
This is the companion to https://github.com/ilios/frontend/pull/3578 and refs ilios/frontend#3495
> Switch to CSS Grids

- addon/models/learner-group.js
This is the other half of https://github.com/ilios/ilios/pull/2090 and should be merged when that is.
> Add ancestor relationship to learner groups

- config/ember-try.js
- ember-cli-build.js
- package.json
- tests/dummy/config/targets.js
- yarn.lock
> Greenkeeper/ember cli 3.0.2

- addon/models/session.js
- tests/unit/models/session-test.js
Count the duration of of a session by combining max offering duration
and the ILM hours.
> Add totalSumDuration for session model

- addon/locales/en/translations.js
- addon/locales/es/translations.js
- addon/locales/fr/translations.js
- addon/templates/components/single-event.hbs
- addon/templates/components/week-glance.hbs
- tests/integration/components/dashboard-week-test.js
- tests/integration/components/week-glance-test.js
When a session is 'supplemental' flag it as such on the week at a glance and single event views.
Fixes ilios/frontend#3084
> Add supplemental flag

- addon/models/term.js
- tests/unit/models/term-test.js
We need the list of titles so we can do good filtering on the frontend
> Add methods to get descendant data from term model

- addon/models/user.js
- addon/services/current-user.js
- addon/services/permission-checker.js
- addon/services/permission-matrix.js
- app/services/permission-checker.js
- app/services/permission-matrix.js
- tests/unit/models/user-test.js
- tests/unit/services/permission-checker-test.js
- tests/unit/services/permission-matrix-test.js
Just enough to get canCreateCourse working. Builds a default matrix for
each school and calculates the needed roles on it's own.
> Scaffold new permissions system

- addon/models/learner-group.js
- tests/unit/models/learner-group-test.js
I made these while trying to fix ilios/frontend#3573 they didn't fix that, but still seem valid to keep.
> Some small improvements to learner groups computed properties

- .eslintrc.js
- config/ember-try.js
- package.json
- yarn.lock
> Update Ember and Ember CLI

- addon/services/current-user.js
These are arrays of ids not arrays of objects with an id property.
> Fix relationship filters

- addon/services/permission-checker.js
- addon/services/permission-matrix.js
A few changes were made to the matrix and capabilities on the API in:
ilios/ilios#2118
ilios/ilios#2119
ilios/ilios#2122
And are matched here.
> Unify Permissions with the API

- addon/services/permission-checker.js
These are convenient ways to check what are actually school based permissions.
> Add canUpdate*InSchool permissions checkers

- addon/services/current-user.js
We're calling this in permission-checker, but didn't have it
implemented.
> Add missing methods for program year roles

- addon/components/dashboard-calendar.js
- addon/mixins/dashboard-route.js
- addon/services/current-user.js
- addon/templates/components/dashboard-calendar.hbs
- tests/integration/services/current-user-test.js
This property no longer exists on a user as we no longer user
permissions to determine school affiliation.
> Remove references to a users schools

- addon/services/permission-checker.js
> Enforce report finalization for permissions

- addon/models/user.js
- tests/unit/models/user-test.js
Users administering schools should be included in this property.
Fixes ilios/frontend#3747
> Fix isPerformingNonLearnerFunction to include administeredSchools

- addon/services/permission-checker.js
> prevent updating and deletion of locked/archived program years.

- addon/services/current-user.js
This is no longer provided in the token.
> Remove canCreateCIReportInAnySchool property

- addon/services/current-user.js
We need this to determine if someone can create a new program in a
school.
Fixes ilios/frontend#3783
> Add PROGRAM_DIRECTOR to school roles

- addon/services/permission-matrix.js
> grants update permissions on instructor groups to school- and program-directors.

- package.json
- yarn.lock
> Greenkeeper/ember tether 1.0.0 beta.2

- addon/services/permission-checker.js
> Check the correct course level editing capability

- addon/templates/components/ilios-calendar-event-month.hbs
- addon/templates/components/ilios-calendar-event.hbs
- app/styles/ilios-common/components/ilios-calendar.scss
> Left alight event tooltip content

- addon/models/curriculum-inventory-sequence-block.js
> link ci sequence blocks to excluded sessions.

- addon/models/offering.js
- tests/unit/models/offering-test.js
This has been a property on the frontend which we now need in other places so I moved it to the model.
> Add duration to offering

- addon/components/single-event.js
- tests/integration/components/single-event-test.js
companion ticket to ilios/ilios#2173
> eliminate callbacks for objectives/competencies in single event component

- addon/components/single-event.js
We're not using these anymore now that everything we need is in the
event.
> Remove old computed properties

- addon/models/user.js
> updated code comment.

- package.json
- yarn.lock
> Greenkeeper/eslint plugin node 7.0.1

- addon/models/session.js
This is provided by the API for this endpoint now
Refs https://github.com/ilios/ilios/pull/2133
> Add instructionalNotes to session

- addon/models/program-year.js
- addon/models/school.js
- tests/unit/models/program-year-test.js
This always should have been async since we have to traverse the program
relationship. Now it is.
> Make classOfYear correctly async

- .npmrc
- addon/components/lm-type-icon.js
- addon/templates/components/dashboard-agenda.hbs
- addon/templates/components/dashboard-calendar.hbs
- addon/templates/components/dashboard-materials.hbs
- addon/templates/components/ilios-calendar-event.hbs
- addon/templates/components/ilios-calendar-month.hbs
- addon/templates/components/ilios-calendar.hbs
- addon/templates/components/single-event-learningmaterial-list.hbs
- addon/templates/components/single-event.hbs
- addon/templates/components/week-glance.hbs
- ember-cli-build.js
- package.json
- tests/dummy/config/environment.js
- tests/integration/components/dashboard-agenda-test.js
- tests/integration/components/dashboard-materials-test.js
- tests/integration/components/dashboard-week-test.js
- tests/integration/components/lm-type-icon-test.js
- tests/integration/components/single-event-learningmaterial-list-test.js
- tests/integration/components/single-event-test.js
- tests/integration/components/toggle-icons-test.js
- tests/integration/components/week-glance-test.js
- tests/integration/components/weekly-events-test.js
- yarn.lock
FA5 provides a new set of icons and an official ember addon.  Plus it's SVG instead of an icon font. 💯
> Update to Fontawesome 5

- package.json
- yarn.lock
> Greenkeeper/ember source 3.3.2

- addon/authenticators/ilios-jwt.js
- yarn.lock
ember-simple-auth-token v4 simplified the API and we needed to make some
changes to our custom authenticator to handle them.
> Update ilios-jwt authenticator for ESA-token v4

- addon/mixins/course-controller.js
- addon/mixins/course-materials-controller.js
- addon/mixins/course-visualize-instructors-controller.js
- addon/mixins/course/index-controller.js
- addon/mixins/course/rollover-controller.js
- addon/mixins/print-course-controller.js
- addon/mixins/session-controller.js
- addon/mixins/session/copy-controller.js
- addon/mixins/session/index-controller.js
- tests/unit/mixins/course-controller-test.js
- tests/unit/mixins/course-materials-controller-test.js
- tests/unit/mixins/course-visualize-instructors-controller-test.js
- tests/unit/mixins/course/index-controller-test.js
- tests/unit/mixins/course/rollover-controller-test.js
- tests/unit/mixins/print-course-controller-test.js
- tests/unit/mixins/session-controller-test.js
- tests/unit/mixins/session/copy-controller-test.js
- tests/unit/mixins/session/index-controller-test.js
> Re-implement course admin related controllers as mixins

- addon/templates/components/back-link.hbs
- addon/templates/components/big-text.hbs
- addon/templates/components/common-dashboard.hbs
- addon/templates/components/dashboard-agenda.hbs
- addon/templates/components/dashboard-calendar.hbs
- addon/templates/components/dashboard-materials.hbs
- addon/templates/components/dashboard-view-picker.hbs
- addon/templates/components/dashboard-week.hbs
- addon/templates/components/ics-feed.hbs
- addon/templates/components/ilios-calendar-day.hbs
- addon/templates/components/ilios-calendar-event-month.hbs
- addon/templates/components/ilios-calendar-event.hbs
- addon/templates/components/ilios-calendar-month.hbs
- addon/templates/components/ilios-calendar-multiday-event.hbs
- addon/templates/components/ilios-calendar-multiday-events.hbs
- addon/templates/components/ilios-calendar-week.hbs
- addon/templates/components/ilios-calendar.hbs
- addon/templates/components/lm-type-icon.hbs
- addon/templates/components/pulse-loader.hbs
- addon/templates/components/selected-term-tree.hbs
- addon/templates/components/single-event-learningmaterial-list.hbs
- addon/templates/components/single-event-objective-list.hbs
- addon/templates/components/single-event.hbs
- addon/templates/components/timed-release-schedule.hbs
- addon/templates/components/toggle-buttons.hbs
- addon/templates/components/toggle-icons.hbs
- addon/templates/components/toggle-wide.hbs
- addon/templates/components/week-glance.hbs
- addon/templates/components/weekly-events.hbs
- addon/templates/weeklyevents.hbs
> Fix template linting issues

- addon/serializers/course.js
- addon/serializers/ilm-session.js
- addon/serializers/learning-material.js
- addon/serializers/offering.js
- addon/serializers/session.js
- app/serializers/course.js
- app/serializers/ilm-session.js
- app/serializers/learning-material.js
- app/serializers/offering.js
- app/serializers/session.js
- tests/unit/serializers/course-test.js
- tests/unit/serializers/ilm-session-test.js
- tests/unit/serializers/learning-material-test.js
- tests/unit/serializers/offering-test.js
- tests/unit/serializers/session-test.js
> moved serializers from frontend.

- addon/authenticators/ilios-jwt.js
> merge() is deprecated, using assign() instead.

- addon/templates/components/timed-release-schedule.hbs
> indentation fix.

- tests/integration/components/toggle-icons-test.js
> provide missing component args to tests.

- addon/components/sessions-grid-offering-table.js
- addon/components/sessions-grid-offering.js
- addon/components/sessions-grid-offerings-table.js
- app/components/sessions-grid-offerings-table.js
- package.json
- yarn.lock
> fixes various, component migration related, bugs.

- addon/templates/components/objective-manage-competency.hbs
domains and competencies must be clickable. these changes restore this functionality.
> restore objective competency manager clickability

- package.json
- yarn.lock
Closes #304 
Closes #306 
Closes #307
> Update ember cli 3.4.3

- app/styles/ilios-common/components.scss
> wired up omitted component styles.

- addon/models/competency.js
- addon/models/learner-group.js
- addon/models/session.js
- package.json
- tests/unit/models/competency-test.js
- tests/unit/models/curriculum-inventory-report-test.js
- tests/unit/models/learner-group-test.js
- tests/unit/models/program-test.js
- tests/unit/models/session-test.js
- tests/unit/models/user-test.js
- yarn.lock
Updated ember data and fixup some tests.
Fixes #338 
Fixes #339 
Fixes #340
> Update ember data 3.5

- addon/mixins/objective-list-item.js
> clear error message earlier.

- addon/breakpoints.js
- addon/components/removable-row.js
- app/components/removable-row.js
- package.json
- yarn.lock
Found some stuff while working on tests and am adding it here.
> Add missing dependencies and component

- index.js
- package.json
When published to NPM these files were being ignored, but we want to
send them.
> Include test files in package

- addon/helpers/has-route.js
- addon/templates/components/course-loading.hbs
- addon/templates/components/ilios-course-details.hbs
- app/helpers/has-route.js
- tests/integration/components/course-loading-test.js
- tests/integration/helpers/has-route-test.js
> Conditional link back to courses

- package.json
- tests/integration/components/collapsed-competencies-test.js
- tests/integration/components/collapsed-learnergroups-test.js
- tests/integration/components/course-objective-list-test.js
- tests/integration/components/course-overview-test.js
- tests/integration/components/course-rollover-test.js
- tests/integration/components/html-editor-test.js
- tests/integration/components/leadership-manager-test.js
- tests/integration/components/leadership-search-test.js
- tests/integration/components/learning-materials-sort-manager-test.js
- tests/integration/components/objective-sort-manager-test.js
- tests/integration/components/offering-form-test.js
- tests/integration/components/session-copy-test.js
- tests/integration/components/sessions-grid-offering-table-test.js
- tests/integration/components/user-search-test.js
- tests/integration/components/wait-saving-test.js
- yarn.lock
> Move component tests

- tests/unit/components/boolean-check-test.js
> moved boolean check component test from frontend.

- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> moved lang strings into common.

- addon/services/permission-checker.js
- addon/services/permission-matrix.js
> add perm checks for locking program years to matrix.

- addon/components/html-editor.js
- ember-cli-build.js
- package.json
- tests/integration/components/html-editor-test.js
- yarn.lock
Update fixes error message when the addon is started.
> Update froala editor version

- addon-test-support/ilios-common/page-objects/dashboard.js
> target button instead of its wrapper element.

- addon/mixins/course-visualize-instructor-route.js
> correctly calculate ilm minutes for each session.

- .travis.yml
remove additional test stages from travis build.
> yanked additional test stages.

- package.json
- tests/integration/components/course-rollover-test.js
- tests/integration/components/week-glance-test.js
- yarn.lock
refs https://github.com/ilios/frontend/pull/4192
> bumped ember cli mirage dependency.

- package.json
- yarn.lock
> bumped up math helpers dependency.

- addon/components/session-overview.js
- addon/mixins/session-route.js
- addon/models/session.js
- addon/templates/components/session-overview.hbs
- app/styles/ilios-common/components/session-overview.scss
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
refs ilios/frontend#1323
No postrequisite is selected, Due-date can be set if this is an ILM
Postrequisite is selected, ILM due date cannot be set. The "Due Prior To" label links to the postrequisite session.
Inline editing 
List of linked/clickable prerequisites on the other end
> Session linking in the Admin UI

- addon-test-support/ilios-common/page-objects/session.js
- tests/acceptance/course/session/ilm-test.js
- tests/acceptance/course/session/overview-test.js
> Test coverage session linking admin ui

- addon/services/current-user.js
> consider changes to administered courses when calculating "my courses"

- addon/components/html-editor.js
fixes #445 
needs click-testing.
> guard against method invocation with empty element as input

- .stylelintrc
- .travis.yml
- app/styles/ilios-common/components/ilios-calendar.scss
- app/styles/ilios-common/components/single-event-objective-list.scss
- package.json
- yarn.lock
Catch up with what we're doing on the frontend as well as the direction of the ember community.
> Improved Linting

- addon/components/offering-calendar.js
- tests/integration/components/offering-calendar-test.js
As we work on the UI here we just need to fake data so things don't
break.
Fixes ilios/frontend#4287
> Add pre and post requisite dummy data to offering calendar events

- addon-test-support/ilios-common/page-objects/components/ilios-calendar-pre-work-event.js
- addon/components/ilios-calendar-day.js
- addon/components/ilios-calendar-month.js
- addon/templates/components/ilios-calendar-day.hbs
- addon/templates/components/ilios-calendar-month.hbs
- addon/templates/components/ilios-calendar-pre-work-event.hbs
- addon/templates/components/ilios-calendar-pre-work-events.hbs
- addon/templates/components/ilios-calendar-week.hbs
- addon/templates/components/single-event.hbs
- addon/templates/components/week-glance-pre-work.hbs
- tests/integration/components/ilios-calendar-pre-work-event-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> config for rendering pre-work as clickable links or plain text

- addon/utils/query-utils.js
- tests/integration/components/leadership-search-test.js
cleanQuery() only replaces the first special character. Fix it to
replace all special characters.
> fix cleanQuery() bug

- addon/templates/components/offering-calendar.hbs
> render lang string with embedded markup.

- translations/en-us.yaml
> kebap-casing pre-work.

- addon/mixins/session/index-route.js
- addon/templates/components/session-overview.hbs
- tests/acceptance/course/session/overview-test.js
Wip:
Fixes ilios/frontend#4318
Looks like:
> Add first offering date to postrequisite dropdown

- package.json
- yarn.lock
This fixes a bug with tether and tooltips
Refs ilios/frontend#4284
> Upgrade our version of ember-simple-charts

- addon/components/user-search.js
> re-implements instructor-group search in user-search component

- .eslintrc.js
- addon/components/weekly-events.js
- addon/helpers/is-in.js
- addon/models/academic-year.js
- addon/models/course.js
- addon/models/school.js
- package.json
- yarn.lock
Updated a few places where there were linting error
> Use shared ilios addon eslint config

- .eslintrc.js
- package.json
- yarn.lock
Ignore most of the new rules, but fixup the order in component rule
> Use the latest ilios eslint config

- addon-test-support/ilios-common/page-objects/components/week-glance-pre-work.js
- addon/components/week-glance-pre-work.js
- addon/components/week-glance.js
- addon/templates/components/week-glance-pre-work.hbs
- addon/templates/components/week-glance.hbs
- tests/integration/components/week-glance-pre-work-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> Dedupe pre post requisites

- addon/templates/components/course-objective-list-item.hbs
- addon/templates/components/detail-learning-materials.hbs
- addon/templates/components/editable-field.hbs
- addon/templates/components/offering-manager.hbs
- addon/templates/components/session-objective-list-item.hbs
- addon/templates/components/sessions-grid.hbs
- app/styles/ilios-common/components/detail-learningmaterials.scss
- app/styles/ilios-common/components/editinplace.scss
- app/styles/ilios-common/components/learningmaterial-manager.scss
- app/styles/ilios-common/components/objective-list-item.scss
- app/styles/ilios-common/components/offering-manager.scss
- app/styles/ilios-common/components/session-overview.scss
- app/styles/ilios-common/components/sessions-grid.scss
- app/styles/ilios-common/mixins.scss
- app/styles/ilios-common/mixins/icon.scss
> Icon consistency

- addon/components/session-copy.js
- tests/integration/components/session-copy-test.js
> Copy notes with the session

- addon/serializers/authentication.js
- addon/serializers/curriculum-inventory-export.js
- addon/serializers/curriculum-inventory-report.js
- addon/serializers/curriculum-inventory-sequence-block.js
- addon/serializers/report.js
- app/serializers/authentication.js
- app/serializers/curriculum-inventory-export.js
- app/serializers/curriculum-inventory-report.js
- app/serializers/curriculum-inventory-sequence-block.js
- app/serializers/report.js
- tests/unit/serializers/authentication-test.js
- tests/unit/serializers/curriculum-inventory-export-test.js
- tests/unit/serializers/curriculum-inventory-report-test.js
- tests/unit/serializers/curriculum-inventory-sequence-block-test.js
- tests/unit/serializers/report-test.js
all serializers should be where the models are - in common.
> move remaining serializers into common

- app/styles/ilios-common/components/single-event-learningmaterial-list.scss
> no top/bottom-margins on lm descriptions in single event view.

- addon/models/user.js
refs ilios/frontend#4376
follows ilios/ilios#2372
> adds preferred email as user attribute.

- addon/models/objective.js
> Add active property to objectives

- addon/components/week-glance.js
> sort ilm pre-work.

- package-lock.json
- package.json
> bumped validations lib to next major version.

- addon/components/single-event.js
- addon/templates/components/single-event.hbs
- tests/integration/components/single-event-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
**Summary:**
Minor cosmetic wording updates as defined in the issue.
**UI:**
Fixes https://github.com/ilios/frontend/issues/1378
> cosmetic changes to event details

- app/styles/ilios-common/mixins/ilios-table.scss
> complementary rule to hide-from-small-screen.

- translations/fr.yaml
> corrected variable name.

- package-lock.json
zorgbort doesn't do this for us (yet)
> updates lock file with correct common version.

- addon/components/sessions-grid.js
- addon/mixins/course/index-route.js
- addon/services/preserve-scroll.js
- app/services/preserve-scroll.js
- package-lock.json
- package.json
**Summary:**
Utilized vanilla JS and `preserve-scroll` service to preserve window position while scrolling the session list. If users are returning to session list from session details, their scroll position is preserved.
**UI:**
Accompanies https://github.com/ilios/frontend/pull/4491
Fixes https://github.com/ilios/frontend/issues/3813
> preserve session-list scroll

- translations/fr.yaml
> corrects french translation of learning material(s)

- translations/fr.yaml
> corrects french translation of "(learning) material"

- addon/templates/components/publish-all-sessions.hbs
- tests/acceptance/course/publicationcheck-test.js
- tests/acceptance/course/session/publicationcheck-test.js
- tests/integration/components/course-publicationcheck-test.js
- tests/integration/components/publish-all-sessions-test.js
- tests/integration/components/session-publicationcheck-test.js
**Summary:**
Added tests to support code from this [PR](https://github.com/ilios/common/pull/656).
> added tests for issue 3933 PR code

- addon/components/dashboard-agenda.js
- addon/templates/components/dashboard-agenda.hbs
- app/styles/ilios-common/components/dashboard-agenda.scss
- tests/integration/components/dashboard-agenda-test.js
> pulls pre-work ILMs out of activities list into own display.

- addon/models/user.js
- tests/unit/models/user-test.js
This is part of the API in v1.37
Requires https://github.com/ilios/ilios/pull/2440
> Add displayName to user model

- addon/components/my-materials.js
- addon/components/single-event.js
- addon/controllers/mymaterials.js
- addon/routes/mymaterials.js
- addon/templates/components/my-materials.hbs
- addon/templates/components/single-event.hbs
- addon/templates/mymaterials.hbs
- app/components/my-materials.js
- app/controllers/mymaterials.js
- app/routes/mymaterials.js
- app/styles/ilios-common/components.scss
- app/styles/ilios-common/components/my-materials.scss
- app/styles/ilios-common/components/single-event.scss
- app/templates/mymaterials.js
- package-lock.json
- package.json
- tests/dummy/app/router.js
- tests/integration/components/my-materials-test.js
- tests/unit/routes/mymaterials-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
**Summary:**
Added archive linked icon (tooltip included) next to "Session Learning Materials" header, which transitions them to the my materials page. Only students can see this icon.
**UI:**
Accompanies https://github.com/ilios/frontend/pull/4540
Fixes https://github.com/ilios/frontend/issues/2301
> archive icon links to access learning materials

- addon/components/course-rollover.js
- addon/templates/components/course-rollover.hbs
- app/styles/ilios-common/components/course-rollover.scss
- tests/integration/components/course-rollover-test.js
> rm advanced options toggle.

- addon-test-support/ilios-common/page-objects/course.js
- addon/components/course-overview.js
- addon/templates/components/course-overview.hbs
- app/styles/ilios-common/components/course-overview.scss
- tests/acceptance/course/overview-test.js
- tests/dummy/app/templates/course/rollover.hbs
**Summary:**
Clicking rollover icon will now scroll to the correct UI.
Fixes https://github.com/ilios/common/issues/696
> rollover icon triggers transition and scroll

- addon/models/aamc-method.js
fixes #722 
follows ilios/ilios#2540
> adds active flag to model.

- addon/services/search.js
- app/services/search.js
- tests/unit/services/search-test.js
Search is part of the API and probably belongs here in common with the other models. Since the odds are pretty strong that we'll want to provide some search functionality from the dashboard putting it here makes sense for that as well.
> Consolidate search operations into a service

- addon/services/permission-checker.js
- tests/dummy/mirage/config.js
- tests/unit/services/permission-checker-test.js
When the API version is wrong don't allow anything that would write a
change.
> Add API version check to permissions check

- addon/services/search.js
- package-lock.json
- package.json
Ember fetch wraps ember's runloop better ensuring that test waiters wait
correctly on the async fetch.
> Use Ember Fetch in search service

- addon/components/collapsed-competencies.js
- addon/components/course-header.js
- addon/components/course-objective-manager.js
- addon/components/course-overview.js
- addon/components/course-summary-header.js
- addon/components/detail-competencies.js
- addon/components/detail-instructors.js
- addon/components/detail-learnergroups-list.js
- addon/components/detail-learning-materials.js
- addon/components/detail-objectives.js
- addon/components/detail-terms-list.js
- addon/components/learnergroup-tree.js
- addon/components/new-session.js
- addon/components/session-overview.js
- addon/mixins/objective-list-item.js
- addon/templates/components/course-summary-header.hbs
- tests/integration/components/course-summary-header-test.js
**Summary:**
Promise refactor to `async/await`.
> promise refactors to async/await

- addon-test-support/ilios-common/page-objects/components/sessions-grid.js
- addon-test-support/ilios-common/page-objects/session.js
- addon/components/session-overview.js
- addon/components/sessions-grid-last-updated.js
- addon/templates/components/session-overview.hbs
- addon/templates/components/sessions-grid-last-updated.hbs
- addon/templates/components/sessions-grid.hbs
- app/components/sessions-grid-last-updated.js
- app/styles/ilios-common/components.scss
- app/styles/ilios-common/components/session-overview.scss
- app/styles/ilios-common/components/sessions-grid-last-updated.scss
- app/styles/ilios-common/components/sessions-grid.scss
- config/icons.js
- tests/acceptance/course/session/overview-test.js
- tests/acceptance/course/sessionlist-test.js
- tests/integration/components/sessions-grid-last-updated-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> last update indicator on sessions and offerings.

- addon/models/cohort.js
- addon/templates/components/detail-cohort-list.hbs
- tests/integration/components/detail-cohort-list-test.js
- tests/unit/models/cohort-test.js
> rm current level CP from model and display.

- addon/components/single-event.js
> space after commas in list of instructors.

- addon/templates/components/api-version-notice.hbs
see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role
> it's just role, not aria-role.

- config/api-version.js
This is an additive change that adds school to search results so we can
increment without any changes here.
Refs ilios/ilios#2595
> Bump api to v1.39

- addon-test-support/ilios-common/page-objects/components/learning-materials.js
- addon/components/learningmaterial-manager.js
- addon/templates/components/learningmaterial-manager.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> make lm description editable if it has been linked only once.

- addon/services/search.js
- tests/unit/services/search-test.js
> Use new search API endpoint

- app/styles/ilios-common/components/course-overview.scss
- app/styles/ilios-common/components/course-summary-header.scss
- app/styles/ilios-common/components/dashboard-view-picker.scss
- app/styles/ilios-common/components/session-overview.scss
- app/styles/ilios-common/components/session-publicationcheck.scss
- app/styles/ilios-common/components/sessions-grid-header.scss
- app/styles/ilios-common/components/sessions-grid-offering-table.scss
- app/styles/ilios-common/mixins/collapsed-container.scss
- app/styles/ilios-common/mixins/ilios-button.scss
- app/styles/ilios-common/mixins/ilios-heading.scss
- app/styles/ilios-common/mixins/ilios-link.scss
- app/styles/ilios-common/variables.scss
More contrast was required between links and the background as well as
links and text they are embedded within. By making the standard text
slightly darker and modifying the shade of blue the contrast is
sufficient. When links are within text it is required that some visual
indication of focus be present, I've added underlines for that purpose.
> Improve accessibility of links

- addon/components/loading-part.js
- addon/templates/components/loading-part.hbs
- app/components/loading-part.js
We use this in two places here so it should be here.
> Import loading-part component from frontend

- README.md
Brought this over from the frontend section with the same name.
> Add open source heroes list

- addon/components/editable-field.js
- addon/components/search-box.js
- addon/components/session-details.js
- addon/utils/scroll-to.js
- tests/integration/components/editable-field-test.js
- tests/integration/components/search-box-test.js
Last spots that aren't Froala, focus and scroll. Now Replaced.
> Remove some jquery

- addon/helpers/remove-html-tags.js
- addon/models/school.js
- addon/utils/query-utils.js
- tests/unit/models/school-test.js
A few more instances where we didn't need jQuery, but were using it for convenience.
> Remove more jquery

- config/icons.js
We need this on the calendar and it was not bundled here.
> Add missing university icon

- addon/components/objective-manage-competency.js
Async/await FTW!
I cleaned this up while bug hunting, not needed to fix the bug, but worth keeping I think.
> Better async functions in component

- addon/components/learningmaterial-manager.js
- addon/components/new-learningmaterial.js
- config/api-version.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
fixes #932 
follows https://github.com/ilios/ilios/issues/2692
> increase acceptable size of learning material title.

- addon/components/choose-material-type.js
- addon/components/publish-menu.js
- addon/templates/components/publish-menu.hbs
- app/styles/ilios-common/components/publish-menu.scss
- package-lock.json
- package.json
- tests/acceptance/course/publish-test.js
- tests/acceptance/course/session/publish-test.js
- tests/integration/components/publish-menu-test.js
We were using a jQuery based dropdown library for this menu. I've
replaced it here with a more idiomatic ember version.
> Replace Publish Menu Component

- package-lock.json
- package.json
We use this here so we shouldn't rely on getting it from somewhere else.
> Add modal dialog directly

- tests/integration/components/week-glance-test.js
Fixes an issue where tests would break on Sunday.
> Fix issue with US and ISO weeks

- addon/components/detail-cohort-manager.hbs
- tests/acceptance/course/cohorts-test.js
> rm trailing pipe from cohort tag.

- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> adds translation for "expand"

- addon/components/week-glance-event.hbs
- addon/components/week-glance-event.js
- addon/components/week-glance-pre-work.js
- addon/components/weekly-events.hbs
- addon/components/weekly-events.js
converts components to glimmer/octane syntax.
> i'd rather be glimmering

- tests/integration/components/offering-form-test.js
> flesh out test coverage for timezone picker.

- addon/components/offering-form.hbs
- app/styles/ilios-common/components/offering-form.scss
desktop mode:
small screen mode:
fixes #990
> prettifies current timezone display.

- addon/components/week-glance.js
> calculate start/end of the week relative to thursday.

- addon-test-support/ilios-common/page-objects/components/course-leadership-expanded.js
- addon-test-support/ilios-common/page-objects/course.js
- addon/components/collapsed-competencies.js
- addon/components/course-leadership-expanded.hbs
- addon/components/course-leadership-expanded.js
- addon/components/course-loading.hbs
- addon/components/course-loading.js
- addon/components/course-publicationcheck.hbs
- addon/components/course-publicationcheck.js
- tests/acceptance/course/publicationcheck-test.js
- tests/integration/components/course-leadership-expanded-test.js
- tests/integration/components/course-publicationcheck-test.js
Converting more components into glimmer / octane syntax
> Just another Glimmer Monday

- package-lock.json
- package.json
Avoids merging a dependency conflict that has to be dealt with in our
apps.
> Add dependency linting

- addon/components/collapsed-taxonomies.hbs
Allows us to remove this helper and the observer it contains.
> Replace intersection-count helper

- addon/components/course-header.hbs
- addon/components/course-objective-list-item.hbs
- addon/components/course-objective-list.hbs
- addon/components/course-overview.hbs
- addon/components/course-rollover.hbs
- addon/components/learningmaterial-manager.hbs
- addon/components/new-learningmaterial.hbs
- addon/components/new-objective.hbs
- addon/components/new-session.hbs
- addon/components/offering-form.hbs
- addon/components/publish-all-sessions.hbs
- addon/components/session-copy.hbs
- addon/components/session-objective-list-item.hbs
- addon/components/session-objective-list.hbs
- addon/components/session-overview.hbs
- addon/components/sessions-grid-offering.hbs
- tests/integration/helpers/is-in-test.js
Contains is provided by ember-composable-helpers, we don't need our own
version.
> Use contains instead of is-in

- addon-test-support/ilios-common/page-objects/components/course-materials.js
- addon/components/course-materials.hbs
- addon/components/course-materials.js
- tests/dummy/app/templates/course-materials.hbs
- tests/integration/components/course-materials-test.js
Also added dummy app infrastructure to use it here.
> Convert <CourseMaterials> into a glimmer component

- addon-test-support/ilios-common/page-objects/components/course-overview.js
- addon-test-support/ilios-common/page-objects/course.js
- addon/components/course-overview.hbs
- addon/components/course-overview.js
- addon/decorators/validation.js
- addon/decorators/validation/after-date.js
- addon/decorators/validation/before-date.js
- addon/decorators/validation/length.js
- addon/decorators/validation/validatable.js
- package-lock.json
- package.json
- tests/acceptance/course/overview-test.js
- tests/integration/components/course-overview-test.js
> Course Overview Glimmer Conversion

- addon/services/ilios-config.js
- tests/unit/services/ilios-config-test.js
Was calling the wrong method to get its value. Added some tests to catch
future issues.
> Fix authentication type computed property

- addon/components/user-search.hbs
- addon/components/user-search.js
- tests/integration/components/user-search-test.js
> Fixes user search with promises

- addon/components/course-publicationcheck.js
- addon/components/course-summary-header.hbs
- addon/components/course-summary-header.js
- addon/components/dashboard-agenda.hbs
- addon/components/dashboard-agenda.js
- addon/components/dashboard-materials.hbs
- addon/components/dashboard-materials.js
- addon/components/dashboard-view-picker.hbs
- addon/components/dashboard-view-picker.js
- addon/components/dashboard-week.hbs
- addon/components/dashboard-week.js
- addon/components/detail-cohort-list.hbs
- addon/components/detail-cohort-list.js
- addon/components/detail-cohort-manager.hbs
- addon/components/detail-cohort-manager.js
- tests/acceptance/course/publicationcheck-test.js
- tests/integration/components/course-summary-header-test.js
- tests/integration/components/dashboard-agenda-test.js
- tests/integration/components/detail-cohort-list-test.js
Several components updated to Octane patterns.
Fixes #1045
> December to Glimmer

- app/styles/ilios-common/fonts.scss
- app/styles/ilios-common/fonts/nunito-sans.scss
- app/styles/ilios-common/fonts/nunito.scss
- app/styles/ilios-common/styles.scss
- config/environment.js
- index.js
- package-lock.json
- package.json
Load fonts ourselves from our own domain.
Fixes ilios/frontend#5000
WIP:
> Improve font loading

- addon/components/detail-taxonomies.hbs
- addon/components/selectable-terms-list-item.hbs
- addon/components/selectable-terms-list-item.js
- addon/components/selectable-terms-list.hbs
- addon/components/selectable-terms-list.js
- addon/components/taxonomy-manager.hbs
- addon/components/taxonomy-manager.js
- tests/integration/components/selectable-terms-list-item-test.js
- tests/integration/components/selectable-terms-list-test.js
- tests/integration/components/taxonomy-manager-test.js
better/modernized test coverage is WIP, i'm dealing with it as a separate issue.
> glimmerizes TaxonomyManager and subcomponents

- config/api-version.js
> supports backend v1.42

- addon/components/detail-instructors.js
- addon/components/learning-material-uploader.js
- addon/components/new-learningmaterial.js
- addon/components/session-overview.js
- addon/routes/mymaterials.js
- addon/services/api-version.js
- addon/services/user-events.js
- tests/integration/components/learning-material-uploader-test.js
- tests/integration/services/user-events-test.js
- tests/unit/services/api-version-test.js
These methods return a promise and are the preferred way to get at this
date.
> Use service methods to access promise based properties

- addon/components/single-event.hbs
- addon/components/week-glance.hbs
- app/styles/ilios-common/components/single-event.scss
- app/styles/ilios-common/components/week-glance.scss
- tests/integration/components/week-glance-test.js
Headers should flow hierarchically, ours were missing some levels in
between which is an a11y violation.
> Fix header levels

- addon/components/week-glance-event.hbs
- addon/components/week-glance.hbs
- app/styles/ilios-common/components/week-glance.scss
Causes them to go in order and avoid an a11y issue.
> Align header levels

- index.js
- package-lock.json
- package.json
This is provided by the default babel config now as it has moved to
stage 4.
> Remove nullish coalescing plugin

- translations/en-us.yaml
> Fixed Course Rollover Msg

- addon-mirage-support/get-all.js
- addon-test-support/ilios-common/page-objects/components/mesh-manager.js
- addon/components/detail-mesh.hbs
- addon/components/detail-mesh.js
- addon/components/mesh-manager.hbs
- addon/components/mesh-manager.js
- tests/integration/components/mesh-manager-test.js
Had to do both <DetailMesh> and <MeshManager> at the same time as they
were too interrelated not to.
> Octaneify MeSH

- addon-test-support/ilios-common/page-objects/components/session/publication-menu.js
- addon/components/session-overview.hbs
- addon/components/session-overview.js
- addon/components/session-publicationcheck.hbs
- addon/components/session/publication-menu.hbs
- addon/components/session/publication-menu.js
- addon/decorators/validation.js
- addon/decorators/validation/gte.js
- app/components/session/publication-menu.js
- app/styles/ilios-common/components/session-overview.scss
- tests/integration/components/session-publicationcheck-test.js
- tests/integration/components/session/publication-menu-test.js
refactors publication menu out into its own subcomponent.
adds Gte (Greater Than or Equal) validator.
> glimmerize SessionOverview component.

- addon/components/learnergroup-tree.hbs
- addon/components/learnergroup-tree.js
- tests/integration/components/learnergroup-tree-test.js
> Glimmerizes LearnergroupTree component.

- addon/components/learnergroup-selection-manager.hbs
- addon/components/learnergroup-selection-manager.js
sub-component of OfferingForm, refs ilios/frontend#4809
> octanifies LearnergroupSelectionManager component.

- addon/components/offering-form.js
geez, this code is old. 
step 0 on our path to getting OfferingForm octaneified and improved.
> replace RSVP promise with async/await

- addon/components/sessions-grid-header.hbs
- addon/components/sortable-heading.hbs
- tests/integration/components/sortable-heading-test.js
fixes https://github.com/ilios/common/issues/1158
> correctly pass and apply custom css classes to component.

- addon/components/search-box.hbs
- addon/components/search-box.js
- addon/components/user-search.js
needed as sub-sub component of offering form (and many others).
> octanifies search box. 

- .dependabot/config.yaml
When fontawesome updates with new icons we can just auto merge that.
> Auto merge icon updates

- addon/components/ilios-calendar-event-month.hbs
- addon/components/ilios-calendar-event-month.js
- addon/utils/calendar-event-tooltip.js
- app/utils/calendar-event-tooltip.js
- tests/integration/components/ilios-calendar-event-month-test.js
- tests/unit/utils/calendar-event-tooltip-test.js
Remove reliance on the elemental calendar event since we're not relying
on the styles there anymore and convert to octane patterns.
> Octaneify Ilios Calendar Event Month

- addon/components/timed-release-schedule.hbs
- addon/components/timed-release-schedule.js
- tests/integration/components/timed-release-schedule-test.js
> always show timed release info if end date is given.

- addon-test-support/ilios-common/page-objects/components/learning-materials.js
- addon/components/detail-learning-materials.hbs
- tests/integration/components/detail-learning-materials-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> adds title to eye-icon.

- addon/components/course-leadership-expanded.hbs
- addon/components/course-leadership-expanded.js
> prevent course leadership manager interaction until all data has loaded.

- addon/components/course-overview.js
- addon/components/detail-learning-materials.hbs
- addon/components/leadership-search.hbs
- addon/components/leadership-search.js
- addon/components/learningmaterial-manager.hbs
- addon/components/learningmaterial-manager.js
- addon/components/learningmaterial-search.hbs
- addon/components/learningmaterial-search.js
- addon/components/lm-type-icon.hbs
- addon/components/lm-type-icon.js
- addon/components/loading-part.js
- addon/components/loading-spinner.hbs
- addon/components/loading-spinner.js
- addon/decorators/validation/after-date.js
- addon/decorators/validation/before-date.js
- package-lock.json
- package.json
- tests/integration/components/leadership-search-test.js
- tests/integration/components/lm-type-icon-test.js
Breaking removal of `ember-one-way-select` will need to be re-added to the frontend.
> [breaking] My Oh My Octane!

- addon-test-support/ilios-common/page-objects/components/session/postrequisite-editor.js
- addon/components/session/postrequisite-editor.hbs
- tests/integration/components/session/postrequisite-editor-test.js
just saw that in passing, no big deal...
> corrects passing of title attribute to the icon.

- addon/components/mesh-manager.js
- tests/integration/components/mesh-manager-test.js
> prevent selected terms from being added.

- app/components/publish-menu.js
- app/locales/en/translations.js
- app/locales/es/translations.js
- app/locales/fr/translations.js
Getting rid of a component that was removed as well as the old
translation exports from pre-ember-intl days when we were using
ember-i18n.
> Remove Unused Exports

- addon/components/course-header.hbs
- addon/components/course-summary-header.hbs
- addon/components/new-learningmaterial.hbs
- addon/components/new-learningmaterial.js
- addon/components/new-objective.hbs
- addon/components/new-objective.js
- addon/components/new-offering.hbs
- addon/components/new-offering.js
- addon/components/new-session.hbs
- addon/components/new-session.js
- addon/components/not-found.hbs
- addon/components/not-found.js
- addon/components/offering-manager.hbs
- addon/components/offering-manager.js
- addon/components/print-course.hbs
- addon/components/print-course.js
- addon/components/progress-bar.hbs
- addon/components/progress-bar.js
- addon/components/publication-status.hbs
- addon/components/publication-status.js
- addon/components/session-overview.hbs
- addon/components/sessions-grid.hbs
- addon/decorators/validation/validatable.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/integration/components/publication-status-test.js
More components on the Octane Train.  Breaking change as `<PublicationStatus>` now requires that the `showText` and `showIcon` values be passed in.
> [breaking] Here's looking at you Octane

- addon/components/pulse-loader.hbs
- addon/components/pulse-loader.js
- addon/components/selected-term-tree.hbs
- addon/components/selected-term-tree.js
Remove some unneeded backing classes.
> Flash of Octane

- addon/components/new-offering.hbs
- addon/components/offering-form.hbs
- addon/components/offering-form.js
- addon/components/offering-manager.hbs
- addon/components/sessions-grid-offering.hbs
> scroll bottom of offering form into view when it gets opened up.

- addon/components/learningmaterial-manager.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
> Track required correctly

- addon-test-support/ilios-common/page-objects/components/detail-learner-list.js
- addon-test-support/ilios-common/page-objects/components/learner-selection-manager.js
- addon/components/detail-learner-list.hbs
- addon/components/learner-selection-manager.hbs
- addon/components/new-offering.js
- addon/components/offering-form.hbs
- addon/components/offering-form.js
- addon/components/offering-manager.js
- addon/components/sessions-grid-offering.js
- app/components/detail-learner-list.js
- app/components/learner-selection-manager.js
- app/styles/ilios-common/components.scss
- app/styles/ilios-common/components/detail-learner-list.scss
- app/styles/ilios-common/components/offering-form.scss
- tests/integration/components/detail-learner-list-test.js
- tests/integration/components/learner-selection-manager-test.js
- tests/integration/components/offering-form-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> link learners to offerings.

- addon-test-support/ilios-common/page-objects/components/offering-form.js
- addon/components/offering-form.hbs
- tests/acceptance/course/session/offerings-management-test.js
- tests/acceptance/course/session/offerings-test.js
- tests/acceptance/course/sessionlist-test.js
- tests/integration/components/offering-form-test.js
> modernizes offering form integration test

- addon/components/publish-all-sessions.hbs
- addon/components/publish-all-sessions.js
- tests/dummy/app/templates/course/publishall.hbs
- tests/integration/components/publish-all-sessions-test.js
Breaking: `<PublishAllSessions>` now requires `@course` to be passed in.
> [breaking] Octaneify <PublishAllSessions> component

- addon-test-support/ilios-common/page-objects/components/dashboard/cohort-calendar-filter.js
- addon-test-support/ilios-common/page-objects/components/dashboard/courses-calendar-filter.js
- addon/components/common-dashboard.hbs
- addon/components/dashboard-calendar.hbs
- addon/components/dashboard-calendar.js
- addon/components/dashboard/cohort-calendar-filter.hbs
- addon/components/dashboard/courses-calendar-filter.hbs
- addon/components/dashboard/courses-calendar-filter.js
- addon/components/dashboard/filter-tags.js
- addon/controllers/dashboard.js
- app/components/dashboard/cohort-calendar-filter.js
- app/components/dashboard/courses-calendar-filter.js
- app/styles/ilios-common/components.scss
- app/styles/ilios-common/components/dashboard-calendar.scss
- app/styles/ilios-common/components/dashboard/cohort-calendar-filter.scss
- app/styles/ilios-common/components/dashboard/courses-calendar-filter.scss
- package-lock.json
- package.json
- tests/acceptance/dashboard/calendar-test.js
- tests/dummy/app/templates/dashboard.hbs
- tests/integration/components/dashboard/cohort-calendar-filter-test.js
- tests/integration/components/dashboard/courses-calendar-filter-test.js
Updated both the course and cohort filters to contain or not need the year anymore.
Fixes ilios/frontend#1830
> Improved year based filters

- package-lock.json
- package.json
> fixes ember-modal-dialog at latest beta.

- addon/components/offering-manager.hbs
- addon/components/week-glance.hbs
- package-lock.json
- package.json
This is the last place we're using this and it's not all that
interesting, let's remove it and remove a source of weird issues.
Refs ilios/frontend#5276
> Remove remaining liquid-fire usage

- addon/components/session-copy.hbs
- addon/components/session-copy.js
- app/styles/ilios-common/components/session-copy.scss
- tests/integration/components/session-copy-test.js
I removed the validations here because they would never fire. Since the
save button is disabled when course or year isn't selected it wasn't
possible to ever be in an invalid state other than when there are no
courses in the year and that is represented in the UI bay "None" courses
and a disabled save button.
> Octaniefy <SessionCopy> component

- addon/components/session-copy.js
- tests/integration/components/session-copy-test.js
just something i noticed missing when reviewing the session-copy octanification PR.
refs #1340
> bring over attendanceRequired flag when copying session.

- app/styles/ilios-common/components/session/objective-list.scss
- app/styles/ilios-common/mixins/objectives.scss
> centers text deletion dialog.

- .github/workflows/ci.yaml
- .github/workflows/future-ci.yaml
- .github/workflows/release.yaml
This should fix failures like https://github.com/ilios/common/runs/631149302
> Update actions/checkout version

- app/styles/ilios-common/components/print-course.scss
> un-bullet lists in course print view.

- addon-test-support/ilios-common/page-objects/components/taxonomy-manager.js
- addon/components/selectable-terms-list-item.hbs
- addon/components/selectable-terms-list.hbs
- addon/components/selectable-terms-list.js
- tests/integration/components/taxonomy-manager-test.js
> filters sub-terms against given text.

- .github/workflows/update-transitive-dependenies.yaml
Moves the time up 7 hours to account for it being in UTC
Makes zorgbort the author of the PR
> Improvements to auto update workflow

- addon/components/dashboard-agenda.js
- addon/components/ilios-calendar-day.js
- addon/components/ilios-calendar-month.js
- addon/components/ilios-calendar-week.js
- tests/integration/components/dashboard-agenda-test.js
- tests/integration/components/ilios-calendar-day-test.js
- tests/integration/components/ilios-calendar-month-test.js
- tests/integration/components/ilios-calendar-week-test.js
fixes ilios/frontend#5356
fixes ilios/frontend#5354
> filter out scheduled/unpublished/blanked target events of pre-work ilms.

- package-lock.json
- package.json
New releases across the board, all things fixed now.
> Revert package lock kludge

- addon/components/dashboard-materials.hbs
- tests/integration/components/dashboard-materials-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> relabels my-materials link as all materials.

- .github/workflows/asset-size-check.yml
Will be easier to spot any mistakes that add massively to the total size
of our apps.
> Calculate asset size changes on PRs

- addon/components/detail-instructors-list.hbs
- tests/acceptance/dashboard/calendar-test.js
- tests/integration/components/dashboard/cohort-calendar-filter-test.js
Couple more things cherry-picked from #1433.
> Some minor sort fixes

- .github/workflows/automerge.yml
- .github/workflows/update-transitive-dependenies.yaml
Two changes:
1) Run as Zorgbort so that other actions will still run after the PR is created
2) Automatically merges itself once checks pass.
> Update Automatic Dependency Action

- .github/workflows/update-transitive-dependenies.yaml
Revert this testing change and do updates on Monday Morning
> Run updates on Monday Mornings

- addon/components/offering-form.js
- tests/integration/components/offering-form-test.js
This makes it easier to paste into the form and pass validation.
Fixes #1500
> Trim whitespace from URL input

- .eslintrc.js
- package-lock.json
Also ignored some new eslint rules temporarily.
> Update Transitive Dependencies

- addon/models/program-year.js
- addon/models/program.js
> rm published/publishedAsTbd from program and program-year models

- addon/components/sortable-th.js
- tests/integration/components/sortable-th-test.js
> respect sort order input if its value is false.

- addon/helpers/-set.js
- app/helpers/-set.js
- index.js
- lib/set-transform.js
- package-lock.json
- package.json
- tests/integration/helpers/-set-test.js
The simple-set-helper we were using doesn't play nicely with embroider
and efforts to add this feature haven't been merged. For now we can
provide this transform and helper ourselves as it is fairly
straightforward.
> Provide our own {{set}} helper and transform

- addon/components/leadership-list.hbs
- addon/components/leadership-manager.hbs
- addon/components/print-course.hbs
- addon/models/offering.js
- tests/integration/components/leadership-list-test.js
- tests/integration/components/leadership-manager-test.js
- tests/unit/models/offering-test.js
companion ticket to ilios/frontend#5510
> sort users by full name instead of first/last name.

- addon-test-support/ilios-common/page-objects/components/week-glance.js
- addon-test-support/ilios-common/page-objects/dashboard.js
- addon/components/week-glance-event.hbs
- addon/components/week-glance-pre-work.hbs
- addon/components/week-glance.hbs
- addon/components/week-glance.js
- app/styles/ilios-common/components/week-glance-pre-work.scss
- app/styles/ilios-common/components/week-glance.scss
- tests/acceptance/dashboard/waag-test.js
- tests/integration/components/week-glance-test.js
Get the font sizes under control, mostly this was a problem of applying
the .title class way to many times. Restructuring the HTML I also added
some a11y tests.
Fixes #1614
> Improve style and accessibility of week at a glance

- config/api-version.js
refs https://github.com/ilios/ilios/pull/3119
> bumps API version.

- addon/components/course-materials.hbs
- addon/components/course-rollover.hbs
- addon/components/course/manage-objective-parents.hbs
- addon/components/dashboard-calendar.hbs
- addon/components/dashboard/cohort-calendar-filter.hbs
- addon/components/dashboard/courses-calendar-filter.hbs
- addon/components/dashboard/selected-term-tree.hbs
- addon/components/detail-learnergroups-list.hbs
- addon/components/leadership-search.hbs
- addon/components/learningmaterial-search.hbs
- addon/components/mesh-manager.hbs
- addon/components/offering-form.hbs
- addon/components/offering-manager.hbs
- addon/components/publish-all-sessions.hbs
- addon/components/session/manage-objective-parents.hbs
- addon/components/sessions-grid.hbs
- addon/components/weekly-events.hbs
companion PR to https://github.com/ilios/frontend/pull/5566
fixes https://github.com/ilios/common/issues/1624
> replaces deprecated "contains" helper with "includes" substitute.

- addon/models/learner-group.js
- tests/unit/models/learner-group-test.js
refs https://github.com/ilios/frontend/issues/5577
> adds CP for checking if learnergroup subgroups need accommodations.

- addon-test-support/ilios-common/page-objects/components/detail-learnergroups-list.js
- addon-test-support/ilios-common/page-objects/components/learnergroup-tree.js
- addon/components/detail-learnergroups-list.hbs
- addon/components/learnergroup-tree.hbs
- addon/components/offering-manager.hbs
- config/icons.js
- tests/integration/components/learnergroup-selection-manager-test.js
- tests/integration/components/learnergroup-tree-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
refs https://github.com/ilios/frontend/issues/5563
> Adds "Needs accommodation" iconography to learner group titles as applicable

- CONTRIBUTING.md
- docker-compose.yml
This will make developing with common easier as the API server can be
provided to work against.
> Add docker compose and docs

- addon/components/offering-form.hbs
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> relabels Url form field as Virtual Learning Link.

- addon-test-support/ilios-common/page-objects/components/course/collapsed-objectives.js
- addon-test-support/ilios-common/page-objects/components/session/collapsed-objectives.js
- addon/components/course/collapsed-objectives.hbs
- addon/components/course/collapsed-objectives.js
- addon/components/session/collapsed-objectives.hbs
- addon/components/session/collapsed-objectives.js
- tests/integration/components/course/collapsed-objectives-test.js
- tests/integration/components/session/collapsed-objectives-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
refs https://github.com/ilios/frontend/issues/5371
> shows linked vocabulary term totals.

- addon-test-support/ilios-common/page-objects/session.js
- addon/components/session-details.hbs
- tests/acceptance/course/session/overview-test.js
> do not show collapser if session has no objectives.

- addon-test-support/ilios-common/page-objects/components/click-choice-buttons.js
- addon/components/click-choice-buttons.hbs
- tests/integration/components/click-choice-button-test.js
> replaced deprecated helper with up-to-date equivalent.

- addon-test-support/ilios-common/page-objects/components/single-event.js
- addon/classes/events-base.js
- addon/components/single-event.hbs
- tests/integration/components/single-event-test.js
> only link to all materials if user is student AND event is user event

- addon-test-support/ilios-common/page-objects/components/user-name-info.js
- addon/components/user-name-info.hbs
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/acceptance/course/session/offerings-management-test.js
- tests/integration/components/detail-instructors-list-test.js
- tests/integration/components/detail-learner-list-test.js
- tests/integration/components/detail-learning-materials-test.js
- tests/integration/components/instructor-selection-manager-test.js
- tests/integration/components/leadership-list-test.js
- tests/integration/components/leadership-manager-test.js
- tests/integration/components/learner-selection-manager-test.js
- tests/integration/components/new-learningmaterial-test.js
- tests/integration/components/user-name-info-test.js
fixes https://github.com/ilios/common/issues/1658
> Adds "Campus name of record" prefix to tooltip

- addon-test-support/ilios-common/page-objects/session.js
- addon/components/offering-manager.hbs
- tests/acceptance/course/session/offerings-management-test.js
> fixes regression that was preventing tooltip from showing ever.

- addon/components/offering-manager.hbs
- tests/acceptance/course/session/offerings-management-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/common/issues/1355
> Improved learnergroups tooltip

- addon/components/detail-terms-list-item.hbs
- app/styles/ilios-common/components/detail-terms-list.scss
- tests/integration/components/detail-terms-list-item-test.js
> give nested vocab terms a bit mor spacing in tag

- addon-test-support/ilios-common/page-objects/components/weekly-events.js
- addon/components/weekly-events.hbs
- tests/integration/components/weekly-events-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/common/issues/1296
> Properly styles and titles navigational elements

- addon/components/ilios-calendar.hbs
fixes https://github.com/ilios/common/issues/1681
> show spinner in dashboard calendar on consecutive data reloads.

- addon/components/choose-material-type.js
can't reproduce it locally, but throwing up some extra check won't hurt.
hopefully fixes https://github.com/ilios/common/issues/1236
> puts some guard rails up before interacting with menu element.

- app/styles/ilios-common/components/offering-form.scss
desktop: 
mobile:
fixes  #1684
> rm unneccessary hardwired element widths, they were squishing things.

- addon/components/publish-all-sessions.hbs
- addon/components/publish-all-sessions.js
- addon/templates/course/publishall.hbs
- tests/integration/components/publish-all-sessions-test.js
this maintains the current publication state and should prevent accidental change of publication state to "scheduled".
fixes #1292
> pre-select fully published but incomplete sessions as "publish as-is"

- addon/classes/events-base.js
- package-lock.json
- package.json
This is the recommended replacement for the now-deprecated moment
library.
> Replace moment formater with luxon in event base

- addon/decorators/validation.js
- addon/decorators/validation/gte-prop.js
I need this in Frontend for octanifying the curriculum inventory management components,
In particular, the `<CurriculumInventorySequenceBlockMinMaxEditor>` component needs to check if the value of one component property (`maximum`) is greater than or equal to another property (`minimum`).
> adds "greater than or equal to another property" validator.

- addon-test-support/ilios-common/page-objects/components/offering-form.js
- addon/components/offering-form.hbs
- addon/components/offering-form.js
- app/styles/ilios-common/components/offering-form.scss
- app/styles/ilios-common/mixins/ilios-form.scss
- tests/acceptance/course/session/offerings-management-test.js
- tests/acceptance/course/session/offerings-test.js
- tests/integration/components/offering-form-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
refs https://github.com/ilios/frontend/issues/3402#issuecomment-682202928
> re-layout date-time/recurrence info in offering form.

- addon/components/new-learningmaterial.hbs
- addon/components/new-learningmaterial.js
> improves URL validation.

- addon/models/learner-group.js
- tests/unit/models/learner-group-test.js
i noticed duplication of instructors listed while working on the learnergroup instructor manager in frontend. this fixes this issue.
refs https://github.com/ilios/frontend/pull/5693
> de-dupe all instructors.

- app/styles/ilios-common/components/offering-manager.scss
fixes https://github.com/ilios/frontend/issues/5109
refs https://github.com/ilios/frontend/issues/1703
> adds border between offerings in list for better visual separation.

- addon/components/learnergroup-selection-manager.hbs
- addon/components/learnergroup-selection-manager.js
- addon/components/learnergroup-tree.hbs
- addon/components/learnergroup-tree.js
- addon/components/offering-form.hbs
- addon/components/offering-form.js
- tests/integration/components/learnergroup-selection-manager-test.js
- tests/integration/components/learnergroup-tree-test.js
- tests/integration/components/offering-form-test.js
fixes https://github.com/ilios/frontend/issues/1776
> Sort learnergroups in picker

- app/styles/ilios-common/components/session-overview.scss
> claims more space for session title.

- addon/components/sessions-grid-offering-table.hbs
- addon/components/sessions-grid-offering.hbs
- tests/acceptance/course/sessionlist-test.js
> show learners and totals in session/offerings grid

- addon/components/course-header.hbs
- addon/components/course-header.js
- addon/components/editable-field.hbs
- app/styles/ilios-common/components/course-header.scss
> Give course title input field more space

- app/styles/ilios-common/components/sessions-grid-offering-table.scss
> removes unnecessary padding and border styles from offering table grid.

- addon/components/back-link.hbs
> give it a bit of space between text and icon.

- app/styles/ilios-common/components/offering-form.scss
> give the location field some more room.

- addon-test-support/ilios-common/page-objects/components/offering-form.js
- addon/components/offering-form.hbs
- addon/components/offering-form.js
- tests/integration/components/offering-form-test.js
> submit edited offering by pressing enter in input field.

- addon/components/offering-form.js
- config/api-version.js
- tests/integration/components/offering-form-test.js
refs https://github.com/ilios/ilios/issues/3140
follows: https://github.com/ilios/ilios/pull/3193
> changes offering for to accept empty input for room.

- addon/utils/load-polyfills.js
- package-lock.json
- package.json
New versions of our plural rules and relative time format polyfills
require the locale one as well.
> If needed import the Intl.locale polyfil

- addon-test-support/ilios-common/page-objects/components/new-session.js
- addon-test-support/ilios-common/page-objects/sessions.js
- addon/components/new-session.hbs
- addon/components/new-session.js
- tests/acceptance/course/sessionlist-test.js
- tests/integration/components/new-session-test.js
> fixes various issues with the new session title input.

- addon/decorators/validation.js
- addon/decorators/validation/is-email.js
we needs this in the frontend for octanifying user management components.
> adds IsEmail validation decorator.

- app/styles/ilios-common/components/offering-manager.scss
> give deletion confirmation message more room to breathe.

- addon/components/sessions-grid.hbs
- tests/integration/components/sessions-grid-test.js
> prevent deletion of session if it has prerequisites.

- addon/controllers/dashboard.js
Switch back to `@tracked` to be more Octane Idiomatic.
Requires https://github.com/emberjs/ember.js/issues/18715 to be fixed. This is a reproduction for checking in on that issue.
> Use tracked for query params

- tests/dummy/app/controllers/login.js
- tests/dummy/app/templates/login.hbs
copy your token, press Enter, done!
the rest is just cleanup.
> Submit login form on Enter

- addon-test-support/ilios-common/page-objects/components/course-overview.js
- addon/components/course-overview.hbs
- addon/components/course-overview.js
- addon/components/course-rollover.hbs
> simplifies the scrolling of course rollover dialog into view.

- addon/decorators/validation.js
- addon/decorators/validation/custom.js
this is step 1 - copy the decorator over from frontend.
step 2 will be to remove it from frontend and rewire things there.
> adds Custom validation decorator.

- addon/models/term.js
- tests/unit/models/term-test.js
refs https://github.com/ilios/frontend/issues/5752
> adds CP for counting up child terms.

- addon/components/course-overview.js
> increases number of available course level options.

- app/styles/ilios-common/components/daily-calendar-event.scss
- app/styles/ilios-common/components/monthly-calendar.scss
- app/styles/ilios-common/components/weekly-calendar-event.scss
fixes #1894 
needs a visual review.
> show pointer cursor on calendar event only if event is clickable.

- addon/components/ilios-calendar-multiday-event.hbs
- app/styles/ilios-common/components/ilios-calendar-multiday-events.scss
- tests/integration/components/ilios-calendar-multiday-event-test.js
fixes https://github.com/ilios/common/issues/1909
> Multiday-events list style and layout update.

- addon-test-support/ilios-common/page-objects/components/new-learningmaterial.js
- addon/components/learningmaterial-manager.js
- addon/components/new-learningmaterial.hbs
- addon/components/new-learningmaterial.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/integration/components/new-learningmaterial-test.js
> improves LM input validation

- app/styles/ilios-common/components/learningmaterial-manager.scss
- app/styles/ilios-common/mixins.scss
- app/styles/ilios-common/mixins/text-wrap.scss
> wraps overlong lm links.

- addon/routes/course-materials.js
- addon/routes/course-visualizations.js
- addon/routes/course-visualize-instructor.js
- addon/routes/course-visualize-instructors.js
- addon/routes/course-visualize-objectives.js
- addon/routes/course-visualize-session-type.js
- addon/routes/course-visualize-session-types.js
- addon/routes/course-visualize-term.js
- addon/routes/course-visualize-vocabularies.js
- addon/routes/course-visualize-vocabulary.js
- addon/routes/course.js
- addon/routes/course/index.js
- addon/routes/course/publication-check.js
- addon/routes/course/publishall.js
- addon/routes/course/rollover.js
- addon/routes/events.js
- addon/routes/mymaterials.js
- addon/routes/print-course.js
- addon/routes/session.js
- addon/routes/session/copy.js
- addon/routes/session/index.js
- addon/routes/session/publication-check.js
- addon/routes/weeklyevents.js
- tests/dummy/app/routes/application.js
- tests/dummy/app/routes/dashboard.js
- tests/dummy/app/routes/index.js
- tests/dummy/app/routes/login.js
- tests/dummy/app/routes/logout.js
fixes #1915 
Updated following [these steps](https://github.com/simplabs/ember-simple-auth#walkthrough), please review thoroughly.
> replaces deprecated auth mixins.

- package-lock.json
- package.json
One of the new versions has an issue with strings that we don't want to
handle. Will track down and report, but for now this is a fix.
> Lock ember version

- addon-mirage-support/factories/academic-year.js
- addon/models/academic-year.js
- config/api-version.js
- tests/acceptance/dashboard/calendar-test.js
- tests/integration/components/session-copy-test.js
> removes obsolete "academicYearTitle" property from academic-year model

- addon/models/program-year.js
- tests/unit/models/program-year-test.js
refs https://github.com/ilios/ilios/issues/3272
> rm obsolete academic-year CP.

- addon/models/curriculum-inventory-report.js
- tests/unit/models/curriculum-inventory-report-test.js
> rm obsolete yearLabel CP.

- addon/components/course-rollover.hbs
- addon/components/course-rollover.js
- tests/integration/components/course-rollover-test.js
refs https://github.com/ilios/ilios/issues/3272
refs https://github.com/ilios/frontend/issues/5866
> show year range or single year in academic year dropdown in course rollover dialog

- addon-test-support/ilios-common/page-objects/course-visualizations.js
- addon/routes/course-visualizations.js
- addon/templates/course-visualizations.hbs
- tests/acceptance/course-visualizations-test.js
With some new tests to ensure this route is loading.
Fixes ilios/frontend#5879
> Add missing session import for course visualizations route

- addon/components/user-search-result-instructor-group.hbs
- addon/components/user-search-result-user.hbs
- addon/components/user-search.hbs
- addon/components/user-search.js
- app/components/user-search-result-instructor-group.js
- app/components/user-search-result-user.js
- tests/integration/components/user-search-result-instructor-group-test.js
- tests/integration/components/user-search-result-user-test.js
- tests/integration/components/user-search-test.js
Pulling out the proxy objects and restructuring into several components
makes this usable with resources and other async data strategies.
> Refactor user search

- addon/classes/permission-checker.js
refs https://github.com/ilios/frontend/pull/5903
> adds permission checker resource.

- .github/workflows/ci.yaml
- addon/components/ilios-calendar.hbs
- addon/components/ilios-calendar.js
- config/ember-try.js
- ember-cli-build.js
- package-lock.json
- package.json
This is the upcoming build system for ember apps and we'd like to start
using it in the frontend, we should test here to ensure we are
compatible.
> Build and test with embroiderer

- addon/services/ilios-config.js
- tests/dummy/config/deprecation-workflow.js
For and Since are now required so I've added them as well as updated the
until version to our next major release.
> Add required deprecation options

- .lint-todo/3122f077362b2d87a90256ae45b548a2fe675b4d/22e75efc.json
- .lint-todo/735d2bc4ad1637ea8a3dcdd63ec79d80db222fa3/20b05c1e.json
- .lint-todo/7f2da4e582ce08339b9a51e0a3793517026d36a8/0257a624.json
- .lint-todo/7f2da4e582ce08339b9a51e0a3793517026d36a8/16f6d0ed.json
- .lint-todo/7f2da4e582ce08339b9a51e0a3793517026d36a8/d4e74065.json
- .lint-todo/7f2da4e582ce08339b9a51e0a3793517026d36a8/eaee75f3.json
- .lint-todo/c0a9c954a1a1453d5df21149e8a72fe9490aee84/d618fcaa.json
- .lint-todo/c0a9c954a1a1453d5df21149e8a72fe9490aee84/f9180fb7.json
- .lint-todo/cadaa64f200dee955cf83447989ebee768ca8350/88d38467.json
- .lint-todo/cadaa64f200dee955cf83447989ebee768ca8350/e2698d69.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/0074626f.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/1436dff6.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/40808268.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/47950e7b.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/8d47d35b.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/96efe17a.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/9b14e997.json
- .lint-todo/ee5d6d24887adfb9a43fa2abd1f2b49fd2588482/c6828136.json
- addon/components/course-materials.hbs
- addon/components/course-overview.hbs
- addon/components/date-picker.js
- addon/components/learningmaterial-manager.hbs
- addon/components/my-materials.hbs
- addon/components/offering-form.hbs
- addon/components/session-overview.hbs
- addon/components/sortable-heading.js
- addon/components/sortable-th.js
- tests/integration/components/date-picker-test.js
- tests/integration/components/sortable-heading-test.js
- tests/integration/components/sortable-th-test.js
refs #2041 
_this constitutes a breaking change and warrants a major version bump_
> [breaking] change attr name for passing in a click or change event handler.

- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/14424c22.json
- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/3e51c571.json
- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/471e16bf.json
- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/6c5760ee.json
- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/9df53b9f.json
- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/a4c12ddd.json
- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/c710a9f2.json
- .lint-todo/1181ad156954d20ab0f576b1beb8d1fe16f4bf58/c84b6650.json
- addon-test-support/ilios-common/page-objects/components/sessions-grid-header.js
- addon/components/sessions-grid-header.hbs
- tests/integration/components/sessions-grid-header-test.js
rewires click handlers in sortable session grid header.
this corrects a regression introduced in #2044
> fixes sessions list sorting.

- addon-test-support/ilios-common/page-objects/components/course-overview.js
- addon/components/course-overview.hbs
- tests/acceptance/course/overview-test.js
- tests/integration/components/course-overview-test.js
this addresses an regression introduced via https://github.com/ilios/common/pull/2048
test coverage has been updated accordingly while at it.
fixes https://github.com/ilios/common/issues/2061
> course overview: corrects populating form control for external course id.

- app/styles/ilios-common/mixins/ilios-overview.scss
fixes #2055 
since this is a global style change, i  reviewed and included screenshots of affected components/areas in both common and frontend
> give grid columns more room to breathe.

- addon-test-support/ilios-common/page-objects/components/publish-all-sessions.js
- addon/components/publish-all-sessions.hbs
- tests/integration/components/publish-all-sessions-test.js
> corrects name of session objectives attribute.

- addon/components/single-event.hbs
> simplifies check of session description length.

- package-lock.json
- package.json
Reverts ilios/common#2102
"too soon".
> Revert "Bump @embroider/util from 0.39.1 to 0.40.0"

- addon/utils/calendar-event-tooltip.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/common/issues/2171
> show start time for ILMs in calendar event tooltip.

- addon/components/session/manage-objective-parents.hbs
- addon/components/session/objective-list-item-parents.hbs
- addon/helpers/sort-by-position.js
- app/helpers/sort-by-position.js
- tests/integration/components/session/manage-objective-parents-test.js
- tests/integration/components/session/objective-list-item-parents-test.js
- tests/integration/helpers/sort-by-position-test.js
> preserve sort order of parent course objectives when managing session objectives

- .github/workflows/auto-merge.yml
This wasn't valid syntax, gotta try again.
> Fix automerge action

- .github/workflows/auto-merge.yml
Github provided example was wrong here... correcting this permission setting.
> Fix workflow syntax

- addon/utils/calendar-event-tooltip.js
- tests/unit/utils/calendar-event-tooltip-test.js
> adds session type to calendar event tooltip.

- addon/components/dashboard-week.hbs
- addon/components/week-glance.js
- addon/components/weekly-events.hbs
- addon/components/weekly-events.js
- addon/controllers/weeklyevents.js
- addon/routes/weeklyevents.js
- addon/templates/weeklyevents.hbs
fixes https://github.com/ilios/common/issues/2203
this will pass the current week from the Dashboard to All Weeks when clicking the "All Weeks" link, and the scrolls down to the given week.
> scroll the current week into view.

- addon-test-support/ilios-common/page-objects/components/course-visualize-instructors.js
- addon/components/course-visualize-instructors.hbs
- tests/integration/components/course-visualize-instructors-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
this improves placeholder text on filter input while at it. 
fixes #2219
> repairs filter on instructors chart.

- addon/components/single-event-learningmaterial-list.hbs
- tests/integration/components/single-event-learningmaterial-list-test.js
> show timing window on blanked materials as well.

- tests/dummy/config/deprecation-workflow.js
These are no longer relevant for us and can be removed.
> Cleanup some deprecations

- addon/services/current-user.js
- addon/services/ilios-config.js
- tests/unit/services/ilios-config-test.js
These have been deprecated for quite a while and can finally be removed.
> [breaking] Remove async computed properties

- package-lock.json
- package.json
- tests/integration/components/visualizer-course-instructors-test.js
- tests/integration/components/visualizer-course-session-types-test.js
- tests/integration/components/visualizer-course-vocabulary-test.js
closes https://github.com/ilios/common/issues/2294
> update ember-simple-chart dependency.

- addon-test-support/ilios-common/page-objects/components/course-visualize-instructor.js
- addon-test-support/ilios-common/page-objects/components/course-visualize-instructors.js
- addon-test-support/ilios-common/page-objects/components/course-visualize-objectives.js
- addon-test-support/ilios-common/page-objects/components/course-visualize-session-type.js
- addon-test-support/ilios-common/page-objects/components/course-visualize-session-types.js
- addon-test-support/ilios-common/page-objects/components/course-visualize-term.js
- addon-test-support/ilios-common/page-objects/components/course-visualize-vocabularies.js
- addon-test-support/ilios-common/page-objects/components/course-visualize-vocabulary.js
- addon/components/course-visualize-instructor.hbs
- addon/components/course-visualize-instructors.hbs
- addon/components/course-visualize-objectives.hbs
- addon/components/course-visualize-session-type.hbs
- addon/components/course-visualize-session-types.hbs
- addon/components/course-visualize-term.hbs
- addon/components/course-visualize-vocabularies.hbs
- addon/components/course-visualize-vocabulary.hbs
- app/styles/ilios-common/components.scss
- app/styles/ilios-common/components/breadcrumbs.scss
- tests/integration/components/course-visualize-instructor-test.js
- tests/integration/components/course-visualize-instructors-test.js
- tests/integration/components/course-visualize-objectives-test.js
- tests/integration/components/course-visualize-session-type-test.js
- tests/integration/components/course-visualize-session-types-test.js
- tests/integration/components/course-visualize-term-test.js
- tests/integration/components/course-visualize-vocabularies-test.js
- tests/integration/components/course-visualize-vocabulary-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/common/issues/2226
> Add breadcrumbs to course visualizations

- addon/templates/print-course.hbs
- app/styles/ilios-common/components/body.scss
fixes https://github.com/ilios/common/issues/2302
> adds back-to-course link to print page.

- addon/components/course-materials.hbs
- addon/components/course-materials.js
- tests/integration/components/course-materials-test.js
> corrects display of "no materials available" message when applicable.

- addon-test-support/ilios-common/page-objects/components/single-event-objective-list.js
- addon-test-support/ilios-common/page-objects/components/single-event.js
- addon/components/single-event-objective-list.hbs
- addon/components/single-event-objective-list.js
- addon/components/single-event.hbs
- addon/components/single-event.js
- app/styles/ilios-common/components/single-event-objective-list.scss
- app/styles/ilios-common/components/single-event.scss
- tests/integration/components/single-event-objective-list-test.js
- tests/integration/components/single-event-test.js
> reorganize event details page

- addon/models/instructor-group.js
- tests/unit/models/instructor-group-test.js
refs https://github.com/ilios/frontend/issues/6188
> adds CP for retrieving users-totals.

- addon-mirage-support/factories/aamc-pcrs.js
- addon-mirage-support/get-all.js
- addon-mirage-support/setup.js
typo fix, and adds kludge for retrieving all PCRS.
> fixes various issues with PCRS and mirage.

- app/styles/ilios-common/components/body.scss
- app/styles/ilios-common/components/course-materials.scss
> adds left-hand padding to course materials lists.

- addon-test-support/ilios-common/page-objects/components/course-sessions.js
- addon-test-support/ilios-common/page-objects/components/sessions-grid-header.js
- addon-test-support/ilios-common/page-objects/components/sessions-grid.js
- addon-test-support/ilios-common/page-objects/sessions.js
- addon/components/course-sessions.hbs
- addon/components/course-sessions.js
- addon/components/sessions-grid-header.hbs
- tests/acceptance/course/sessionlist-test.js
- tests/integration/components/course-sessions-test.js
- tests/integration/components/sessions-grid-header-test.js
fixes #2030 
this required a bit of rewiring and markup wrangling.
improves test coverage while at it.
> suppress expand all sessions toggle if none of the sessions have offerings

- .github/workflows/auto-merge.yml
A few more things on the list to automerge when tests pass.
> Automerge moar stuffs

- addon-test-support/ilios-common/page-objects/components/publish-all-sessions.js
- addon-test-support/ilios-common/page-objects/course-publish-all.js
- tests/acceptance/course/publishall-test.js
Updated to page objects to make it easier to work with.
> Modernize the Publish All Sessions Test

- app/styles/ilios-common/components/back-link.scss
- app/styles/ilios-common/components/dashboard-agenda.scss
- app/styles/ilios-common/components/dashboard-materials.scss
- app/styles/ilios-common/components/dashboard-week.scss
- app/styles/ilios-common/components/offering-url-display.scss
- app/styles/ilios-common/components/single-event-learningmaterial-list.scss
- app/styles/ilios-common/components/week-glance.scss
- app/styles/ilios-common/mixins/ilios-link.scss
- index.js
By adding a little bit of bold to our links we can improve the
experience for users who don't perceive color well.
> Improved default link style

- addon/components/ilios-calendar-multiday-event.hbs
- addon/components/ilios-calendar-multiday-event.js
- addon/components/ilios-calendar-multiday-events.hbs
- tests/integration/components/ilios-calendar-multiday-event-test.js
- tests/integration/components/ilios-calendar-multiday-events-test.js
Switched to a real button inside the list instead of a list item
pretending to be a button.
> Fix a11y on multiday calendar events

- app/styles/ilios-common/components/single-event-learningmaterial-list.scss
Having an entire paragraph in italics isn't accessible.
> Remove italics from LM note

- addon/common-routes.js
- tests/dummy/app/router.js
This will allow importing in our apps and remove duplication as well as
ensuring that changes sync correctly.
> Extract routes into an export

- addon/components/learning-materials-sort-manager.hbs
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
Reverts [d9cef043b17b045664fec3e1025fdf8920e84d8e] as this is now fixed
upstream and will no longer fail on the initial undefined value.
> Use parts of translation again

- package.json
see https://github.com/advisories/GHSA-fj58-h2fr-3pp2
> updates class-validator package dependency.

- addon/components/course-publicationcheck.js
We can also use the length value of the relationship to check if there
are parents which engages auto tracking.
> Resolve objectives in course publication check

- addon/components/publish-all-sessions.hbs
- addon/components/publish-all-sessions.js
- tests/integration/components/publish-all-sessions-test.js
The not not array wasn't working, I think this is more explicit and
readable, plus it actually works.
Fixes #2478
> Fix publish all / schedule all buttons

- package-lock.json
- package.json
Requires providing webpack ourselves.
> Update Ember Auto Import to v2

- addon/models/school.js
- tests/unit/models/school-test.js
removed unused methods while at it.
> converts School model to class syntax.

- package-lock.json
- package.json
Dependabot didn't give us this update because the 4.0 series is already being pushed as well.
> Update Ember Data

- addon-test-support/ilios-common/page-objects/components/session-overview.js
- addon/components/session-overview.hbs
- addon/models/session.js
- tests/acceptance/course/session/overview-test.js
> dedupes associated learner groups display

- addon/components/ilios-calendar-day.js
> corrects multi-day output by converting method into getter.

- tests/dummy/config/deprecation-workflow.js
We'll need to solve these, but at least our logs are more readable when
they're quiet.
> Silencing a couple of very loud deprecations

- addon/components/offering-manager.hbs
- addon/components/offering-manager.js
- tests/acceptance/course/session/offerings-management-test.js
> sort learner groups in offerings list by name.

- package-lock.json
> chore: downgrade colors to 1.4.0 in package-lock.json

- index.js
This file name was changed, but this wasn't. Now it is.
> Fix default production route export

- addon/components/detail-learning-materials.hbs
- app/styles/ilios-common/components/detail-learningmaterials.scss
Applied both the link button and a text align style to these to fix
alignment issues.
Fixes #2612
> Fix learning material title buttons

- addon/services/permission-checker.js
- tests/unit/services/permission-checker-test.js
This getter has been deprecated and it's not really suitable for instant
access anymore, instead we can get to school the old fashion way.
> Get school from learner group better

- addon/models/learner-group.js
- tests/unit/models/learner-group-test.js
Resources aren't much help here when we need to know the exact state
right now. Instead I've added some methods to get that state and then
linked the resources to them.
> Add direct methods for pulling some learner group data

- package-lock.json
- package.json
This isn't updated anymore and embroider has better ways of getting at
the same data.
> Remove ember bundle analyzer

- addon/components/learning-materials-sort-manager.hbs
- addon/components/learning-materials-sort-manager.js
- addon/components/objective-sort-manager.hbs
- addon/components/objective-sort-manager.js
- app/styles/ilios-common/mixins/sort-manager.scss
- package-lock.json
- package.json
- tests/acceptance/course/sessionlist-test.js
- tests/integration/components/learning-materials-sort-manager-test.js
- tests/integration/components/objective-sort-manager-test.js
This addon isn't updated anymore and the author doesn't recommend using it as drag/drop is better handled directly in the app. I'm not so sure about that as this was a *huge* pain to figure out, however I think it's working now and mostly OK. I couldn't duplicate the old interface exactly, hopefully this one is OK. Feedback on look/feel very much welcome.
> Replace drag/drop sorting addon with our own implementation

- addon/components/course-visualize-instructors.hbs
- addon/components/course-visualize-session-types.hbs
- addon/components/leadership-search.hbs
- addon/components/search-box.hbs
- addon/components/taxonomy-manager.hbs
refs https://github.com/ilios/ilios/issues/3849
> turn off autocompletion on search inputs.

- .github/workflows/auto-merge.yml
When a major comes in let's take a second look before automerging it
even if all the tests pass.
> Only automerge sermver minor and patch PRs

- .github/workflows/auto-merge.yml
> Remove extra ampersands in automerge workflow

- .github/workflows/ci.yaml
- .github/workflows/future-ci.yaml
- .github/workflows/release.yaml
This is a bit safer, assuming it works for us.
> When installing ignore scripts in CI/CD

- addon/components/dashboard-calendar.hbs
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/frontend/issues/3099
> relabels calendar filter button.

- addon-test-support/ilios-common/page-objects/components/toggle-yesno.js
- addon/components/toggle-yesno.hbs
- app/styles/ilios-common/components/toggle-yesno.scss
- tests/integration/components/toggle-yesno-test.js
Improving the style of this switch.
Refs ilios/frontend#2487
> Replace Yes/No toggle component

- addon/models/curriculum-inventory-academic-level.js
- addon/models/curriculum-inventory-sequence-block.js
- config/api-version.js
refs https://github.com/ilios/ilios/issues/3865
> replaces academic level property with starting/ending academic level.

- app/styles/ilios-common/components/weekly-events.scss
> provide left-hand padding to week glance blocks in all-weeeks view.

- app/styles/ilios-common/components/session-offerings-list.scss
fixes https://github.com/ilios/common/issues/2755
> give it bit more space on the top, remove some at the bottom.

- addon-test-support/ilios-common/page-objects/components/copy-button.js
- addon-test-support/ilios-common/page-objects/components/ics-feed.js
- addon-test-support/ilios-common/page-objects/components/ilios-calendar-day.js
- addon-test-support/ilios-common/page-objects/components/ilios-calendar-pre-work-events.js
- addon-test-support/ilios-common/page-objects/components/ilios-calendar-week.js
- addon-test-support/ilios-common/page-objects/components/ilios-calendar.js
- addon/components/copy-button.hbs
- addon/components/ics-feed.hbs
- addon/components/ilios-calendar-day.hbs
- addon/components/ilios-calendar-month.hbs
- addon/components/ilios-calendar-week.hbs
- addon/components/ilios-calendar.hbs
- tests/integration/components/copy-button-test.js
- tests/integration/components/ics-feed-test.js
- tests/integration/components/ilios-calendar-day-test.js
- tests/integration/components/ilios-calendar-month-test.js
- tests/integration/components/ilios-calendar-test.js
- tests/integration/components/ilios-calendar-week-test.js
> updates tests to use page objects

- addon/controllers/dashboard/calendar.js
fixes https://github.com/ilios/common/issues/2775
> prevent selected school from resetting when hiding filters.

- app/styles/ilios-common/components/taxonomy-manager.scss
fixes https://github.com/ilios/common/issues/2764
> provide some space between filter controls and selected terms.

- addon/components/week-glance-event.hbs
- addon/components/week-glance.hbs
fixes https://github.com/ilios/frontend/issues/5118
fixes https://github.com/ilios/frontend/issues/5119
> improves ui consistency pertaining to pre-work labeling

- addon/components/course-rollover.hbs
> overlay screen while course rolls over.

- app/styles/ilios-common/components/week-glance.scss
> aligns left-hand margin of virtual link with learning materials.

- addon/components/session-overview-ilm-duedate.hbs
- addon/components/session-overview.hbs
- app/styles/ilios-common/components/session-overview-ilm-duedate.scss
- tests/acceptance/course/session/ilm-test.js
- tests/acceptance/course/session/overview-test.js
- tests/integration/components/session-overview-ilm-duedate-test.js
fixes https://github.com/ilios/common/issues/2799
> hide due-date controls on ILMs that are pre-requisites.

- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
refs https://github.com/ilios/common/issues/2804
> updates lang strings from frontend.

- addon-test-support/ilios-common/page-objects/components/sessions-grid.js
- addon/components/sessions-grid.hbs
- app/styles/ilios-common/components/sessions-grid.scss
- tests/integration/components/sessions-grid-test.js
fixes https://github.com/ilios/common/issues/2801
> show "no search results" message in sessions list.

- .github/workflows/auto-merge.yml
Sometimes this doesn't run, it would be nice to know why.
> Output some debugging info in automerge job

- addon-test-support/ilios-common/page-objects/components/publish-all-sessions.js
- addon-test-support/ilios-common/page-objects/publish-all-sessions.js
- addon/components/publish-all-sessions.hbs
- addon/components/publish-all-sessions.js
- addon/templates/course/publishall.hbs
- tests/acceptance/course/session/publish-all-test.js
A refactor a while back changed the property names and we didn't have
good test coverage for this. Fixed the property name and added tests
for the happy path here.
Fixes #2816
> Fix publishing incomplete sessions

- .github/workflows/auto-merge.yml
Align the name of the step with the expected output. Not sure if the
step name change or this was copypasta.
> Fix dependabot automerge workflow

- addon/components/course-rollover.js
- addon/components/learningmaterial-manager.js
A few at a time... someday no more.
> Remove a couple of moment(s)

- addon/components/week-glance-event.hbs
- app/styles/ilios-common/components/offering-url-display.scss
> corrects style for Virtual Session Links on Week at A Glance

- tests/acceptance/course/session/publicationcheck-test.js
attempts to fix test failures in https://github.com/ilios/common/pull/2837 and https://github.com/ilios/common/pull/2838
> updates test to make it pass across ember versions.

- addon-test-support/ilios-common/page-objects/components/offering-form.js
- addon/components/offering-form.hbs
- addon/components/offering-form.js
- app/styles/ilios-common/components/offering-form.scss
- tests/integration/components/offering-form-test.js
> Zero duration offering

- addon/components/course-header.hbs
- addon/components/editable-field.hbs
- addon/components/editable-field.js
- addon/templates/course/publishall.hbs
- addon/templates/session.hbs
- app/styles/ilios-common/components.scss
- app/styles/ilios-common/components/course-details.scss
- app/styles/ilios-common/components/course-header.scss
- app/styles/ilios-common/components/course-loading.scss
- app/styles/ilios-common/components/course-session.scss
- app/styles/ilios-common/components/course-sessions.scss
- app/styles/ilios-common/components/dashboard/calendar.scss
- app/styles/ilios-common/components/dashboard/view-picker.scss
- app/styles/ilios-common/components/publishall.scss
- app/styles/ilios-common/components/session-postrequisite-editor.scss
- app/styles/ilios-common/components/single-event.scss
- app/styles/ilios-common/components/weekly-events.scss
- app/styles/ilios-common/mixins.scss
- app/styles/ilios-common/mixins/course/header.scss
- app/styles/ilios-common/mixins/dashboard.scss
- app/styles/ilios-common/mixins/font-size.scss
- app/styles/ilios-common/mixins/main-border.scss
- app/styles/ilios-common/mixins/main-section.scss
- app/styles/ilios-common/variables.scss
- tests/dummy/app/controllers/application.js
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/application.hbs
- tests/integration/components/editable-field-test.js
I've added a mixin to apply a main border style to things that touch the
navigation and header so they'll be consistent and pleasing.
> Apply Consistent Style to Top Level Pages

- tests/integration/components/selected-instructor-groups-test.js
- translations/en-us.yaml
> Fixes Typo

- package-lock.json
ran `npm install` on the current master branch, this updated the lock file.
here it is.
> updates lock file.

- app/styles/ilios-common/components/session-details.scss
- app/styles/ilios-common/components/session-overview.scss
- app/styles/ilios-common/mixins/detail-container.scss
- app/styles/ilios-common/mixins/ilios-overview.scss
- app/styles/ilios-common/mixins/ilios-table.scss
Removed the padding defaults so most things are flush left and we can adjust as needed.
> Detail Container Space

- tests/integration/modifiers/animate-loading-test.js
This fails intermittently with a timeout, let's kick it up a bit and see
if that helps.
> Add more timeout for flakey test

- app/styles/ilios-common/components/daily-calendar.scss
- app/styles/ilios-common/components/weekly-calendar.scss
For some reason, that I don't care to investigate, this variable wasn't
passing though into the frontend so I'm just calling culturedGrey
directly now.
> Replace Border Interim Variable

- addon/components/course/back-to-courses.hbs
- addon/components/ilios-course-details.hbs
- app/styles/ilios-common/components.scss
- app/styles/ilios-common/components/course-details.scss
- app/styles/ilios-common/components/course-loading.scss
- app/styles/ilios-common/components/course/back-to-courses.scss
Couple of changes to ensure that when a course is loaded there isn't a weird jump between different states.
> Fix Course Loading Jump

- package-lock.json
running `npm install` on the latest `master` branch adds this plugin as peer dependency.
> adds intl-pluralrules as peer dependency.

- package-lock.json
- package.json
replaces https://github.com/ilios/common/pull/2941
> upgrades to froala editor v4.0.13

- app/styles/ilios-common/mixins/detail-container.scss
fixes https://github.com/ilios/common/issues/2946
> reduce vertical space by removing top margin from container content.

- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/login.hbs
> give some padding to the token login form.

- addon/components/visualizer-course-instructor-session-type.js
- addon/components/visualizer-course-instructor-term.js
- addon/components/visualizer-course-instructors.js
- addon/components/visualizer-course-session-types.js
- addon/components/visualizer-course-vocabulary.js
fixes https://github.com/ilios/common/issues/2974
> adds white spaces after separating comma.

- addon/components/print-course.hbs
- tests/acceptance/course/printcourse-test.js
fixes https://github.com/ilios/common/issues/2971
> print view: adds session lms and vocab terms back to the page

- app/styles/ilios-common/components/week-glance.scss
- app/styles/ilios-common/components/week-glance/learning-materials.scss
> Add some space between events in week-at-a-glance

- addon-test-support/ilios-common/page-objects/components/course-visualize-objectives.js
- addon-test-support/ilios-common/page-objects/components/visualizer-course-objectives.js
- addon-test-support/ilios-common/page-objects/course-visualizations-objectives.js
- addon/components/course-visualize-objectives.hbs
- addon/components/course-visualize-objectives.js
- addon/components/visualizer-course-objectives.hbs
- addon/components/visualizer-course-objectives.js
- addon/routes/course-visualize-objectives.js
- tests/acceptance/course-visualizations-objectives-test.js
- tests/integration/components/course-visualize-objectives-test.js
- tests/integration/components/visualizer-course-objectives-test.js
- data is loaded correctly/reliably
- competency titles are now correctly displayed in the chart tooltips
> fixes up course objectives visualizations

- addon/components/course-visualize-instructors.hbs
- addon/components/course-visualize-objectives.hbs
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
> standardizes visualization titles around a common layout pattern.

- app/styles/ilios-common/components/sessions-grid-offering-table.scss
- app/styles/ilios-common/mixins/ilios-table.scss
fixes https://github.com/ilios/common/issues/2997
> Session grid header background color

- addon/components/learningmaterial-manager.hbs
- addon/components/new-learningmaterial.hbs
> improves input validation for learning material title.

- tests/integration/modifiers/animate-loading-test.js
Hopefully this will eliminate some flakyness here.
> Delay longer before failing in loading test

- addon/components/mesh-manager.hbs
- app/styles/ilios-common/components/learning-material-uploader.scss
- app/styles/ilios-common/components/learningmaterial-manager.scss
- app/styles/ilios-common/components/mesh-manager.scss
> learning material manager layout fixes

- package-lock.json
- package.json
The latest update doesn't work in the current FF ESR release
> Backup to v4.3.0 of ember data

- addon-test-support/ilios-common/page-objects/components/course-visualizations.js
- addon/components/course-visualizations.hbs
- addon/components/course-visualize-instructors.hbs
- addon/components/course-visualize-objectives.hbs
- addon/components/course-visualize-session-type.hbs
- addon/components/course-visualize-session-types.hbs
- addon/components/course-visualize-term.hbs
- addon/components/course-visualize-vocabularies.hbs
- addon/components/course-visualize-vocabulary.hbs
- app/styles/ilios-common/components/breadcrumbs.scss
- app/styles/ilios-common/components/course-visualizations.scss
- app/styles/ilios-common/components/course-visualize-instructor.scss
- app/styles/ilios-common/components/course-visualize-instructors.scss
- app/styles/ilios-common/components/course-visualize-objectives.scss
- app/styles/ilios-common/components/course-visualize-session-type.scss
- app/styles/ilios-common/components/course-visualize-session-types.scss
- app/styles/ilios-common/components/course-visualize-term.scss
- app/styles/ilios-common/components/course-visualize-vocabularies.scss
- app/styles/ilios-common/components/course-visualize-vocabulary.scss
- app/styles/ilios-common/mixins.scss
- app/styles/ilios-common/mixins/course/visualization.scss
- tests/integration/components/course-visualizations-test.js
see commit messages in this PR for details.
the tl;dr - better padding, move common styles into mixin, breadcrumb everwhere, filter input box spans full screen width.
> improve and standardize styles for course visualizations

- .github/workflows/auto-merge.yml
- package-lock.json
- package.json
- tests/dummy/config/deprecation-workflow.js
- tests/integration/components/course-visualize-objectives-test.js
- tests/integration/components/user-material-status-test.js
- tests/integration/components/visualizer-course-objectives-test.js
This got auto merged today, I threw some other cleanup into this as well.
> Revert Ember Data Update (again)

- addon/components/dashboard/materials.hbs
- addon/components/dashboard/materials.js
- tests/acceptance/dashboard/materials-test.js
- tests/integration/components/dashboard/materials-test.js
fixes https://github.com/ilios/common/issues/3025
> adds external id and year to courses dropdown.

- addon-test-support/ilios-common/page-objects/components/single-event-learningmaterial-list.js
- addon/components/single-event-learningmaterial-list.hbs
- app/styles/ilios-common/components/single-event-learningmaterial-list.scss
- tests/integration/components/single-event-learningmaterial-list-test.js
fixes https://github.com/ilios/ilios/issues/4377
> Single event: learning materials list fixes

- addon/models/user.js
- tests/unit/models/user-test.js
fixes https://github.com/ilios/ilios/issues/4294
see Netlify build attached to https://github.com/ilios/frontend/pull/6854 for review purposes
> consider ILM instructors as privileged user

- addon/components/session-overview.hbs
- app/styles/ilios-common/components/session-publicationcheck.scss
fixes https://github.com/ilios/ilios/issues/4393
> Session publication check style fixes

- app/styles/ilios-common/components/course-materials.scss
- app/styles/ilios-common/components/course-summary-header.scss
- app/styles/ilios-common/mixins/ilios-overview.scss
fixes https://github.com/ilios/ilios/issues/4399
refs https://github.com/ilios/ilios/issues/4400
> Course LMs style improvements

- addon/components/week-glance.hbs
- addon/components/week-glance.js
fixes https://github.com/ilios/ilios/issues/4371
fixes https://github.com/ilios/ilios/issues/4392
> corrects loading state indicator.

- addon/components/detail-learning-materials.js
- addon/components/new-learningmaterial.js
fixes https://github.com/ilios/ilios/issues/4412
> converts collections to arrays before accessing them as such.

- addon-test-support/ilios-common/page-objects/components/course-details.js
- addon-test-support/ilios-common/page-objects/components/detail-learning-materials-item.js
- addon-test-support/ilios-common/page-objects/components/detail-learning-materials.js
- addon-test-support/ilios-common/page-objects/components/session-details.js
- addon/components/detail-learning-materials-item.hbs
- addon/components/detail-learning-materials-item.js
- addon/components/detail-learning-materials.hbs
- addon/components/detail-learning-materials.js
- addon/helpers/has-route.js
- app/components/detail-learning-materials-item.js
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/integration/components/detail-learning-materials-item-test.js
- tests/integration/components/detail-learning-materials-test.js
this is hokey, let's replace it.
while at it, convert the `has-route` helper to use class syntax.
> replace ObjectProxy with component

- tests/acceptance/course/session/offerings-management-test.js
follow-up to https://github.com/ilios/common/pull/3102
> adds test coverage for sort order of offerings list.

- addon/components/ilios-calendar-event-month.hbs
- addon/components/weekly-calendar-event.hbs
- addon/utils/calendar-event-tooltip.js
fixes https://github.com/ilios/ilios/issues/4439
> whitespace/linebreak fix for multi-instance calendar events.

- package-lock.json
- tests/acceptance/course/learningmaterials-test.js
- tests/acceptance/course/session/learningmaterials-test.js
- tests/integration/components/single-event-learningmaterial-list-item-test.js
- tests/integration/components/timed-release-schedule-test.js
- translations/en-us.yaml
shortening the timed release message for easier reading
> Updating Timed Release LM Message

- package-lock.json
- package.json
Latest ember-data does not get along with ember-concurrency. Working on this upstream, but for now let's pin it at this working version to ensure we can keep working.
> Pin ember-data at 4.7.3

- addon/components/course-rollover.hbs
- addon/components/dashboard/courses-calendar-filter.hbs
- addon/components/dashboard/selected-term-tree.hbs
- addon/components/session-copy.hbs
drop-in replacement for inc, which we get from a library wer're moving away from (ember-composable-helpers).
refs https://github.com/ilios/ilios/issues/4492
> replaces inc helper with add helper equivalent.

- addon-test-support/ilios-common/page-objects/components/publish-all-sessions.js
- addon/components/publish-all-sessions.hbs
- tests/acceptance/course/session/publish-all-test.js
fixes https://github.com/ilios/ilios/issues/4504
> link to sessions in publish-all dialog.

- app/styles/ilios-common/components/publish-all-sessions.scss
fixes https://github.com/ilios/ilios/issues/4520
> layout fixes for "publish all sessions" dialog

- addon/components/daily-calendar-event.hbs
- addon/components/weekly-calendar-event.hbs
fixes https://github.com/ilios/ilios/issues/4605
(extra icons added for illustration only)
> corrects layout of icons of weekly/daily events in the calendar grid.

- addon/components/dashboard/courses-calendar-filter.js
- tests/integration/components/dashboard/courses-calendar-filter-test.js
fixes https://github.com/ilios/ilios/issues/4621
> reverses sort order of academic years in courses filter.

- addon/components/single-event.hbs
- addon/components/single-event.js
- tests/integration/components/single-event-test.js
while at it, this replaces await with getter + Resource.
fixes https://github.com/ilios/ilios/issues/4656
> corrects check on current user's "student" role.

- addon/components/collapsed-competencies.hbs
- addon/components/collapsed-competencies.js
Remove the template await and loader in favor of resources for tracking this async data.
> Refactor collapsed competencies

- tests/dummy/config/deprecation-workflow.js
These have all been addressed and we no longer need to silence them here.
> Remove unfired deprecations

- addon/components/course/rollover-date-picker.js
- tests/acceptance/course/overview-test.js
These are breaking in Safari, but not every time. Trying some async trickery to maybe help.
> Fix for flaky rollover tests

- addon/components/course-rollover.hbs
- addon/components/detail-cohort-manager.hbs
- addon/components/detail-cohort-manager.js
- addon/components/detail-cohorts.hbs
> replace await in component template with Resource.

- addon/components/detail-cohort-list.hbs
> rm unnecessary await from template.

- addon/components/course-materials.hbs
- addon/components/course-materials.js
- tests/integration/components/course-materials-test.js
fixes https://github.com/ilios/ilios/issues/4679
> corrects sorting in course/session LM tables.

- addon/components/course-leadership-expanded.hbs
- addon/components/course-leadership-expanded.js
- addon/components/session-leadership-expanded.hbs
- addon/components/session-leadership-expanded.js
> replace await in component template with did-insert modifier based load process

- addon/components/detail-cohorts.hbs
- addon/components/detail-cohorts.js
> replace usage of await helper from templates with Resource-based async data loading process.

- addon/components/course/objective-list-item-descriptors.hbs
- addon/components/course/objective-list-item-parents.hbs
- addon/components/course/objective-list-item.hbs
- addon/components/course/objective-list-item.js
- addon/components/session/objective-list-item-descriptors.hbs
- addon/components/session/objective-list-item-parents.hbs
- addon/components/session/objective-list-item.hbs
- addon/components/session/objective-list-item.js
- tests/integration/components/course/objective-list-item-descriptors-test.js
- tests/integration/components/course/objective-list-item-parents-test.js
- tests/integration/components/session/objective-list-item-descriptors-test.js
- tests/integration/components/session/objective-list-item-parents-test.js
> replaces await on promise resolution in component templates with Resources

- addon/components/detail-learning-materials-item.hbs
- addon/components/detail-learning-materials-item.js
- addon/components/detail-learning-materials.hbs
- addon/components/learning-materials-sort-manager.hbs
- addon/components/learningmaterial-manager.hbs
- addon/components/learningmaterial-manager.js
> remove await from templates in learning materials management components

- addon/components/dashboard/calendar-filters.hbs
- addon/components/dashboard/calendar-filters.js
- addon/components/dashboard/calendar.hbs
- addon/components/dashboard/calendar.js
- app/components/dashboard/calendar-filters.js
- tests/integration/components/dashboard/calendar-filters-test.js
Putting all of these in a component while removing the loader pattern. Should make it easier to make more changes in the future.
> Extract Calendar Filters into Component

- addon/utils/json-api-utc-date.js
Removing moment one bit at a time, but also added some docs because I hate this little utility and it makes me cry every time I see it.
> Use luxon from JSON:API date conversion utility

- addon/components/detail-instructors.js
- addon/components/detail-learners-and-learner-groups.hbs
- addon/components/detail-learners-and-learner-groups.js
- addon/components/session-details.hbs
- tests/integration/components/detail-learners-and-learnergroups-test.js
> replace await in templates with Resources in components.

- addon/components/detail-taxonomies.hbs
- addon/components/detail-taxonomies.js
- addon/components/objective-list-item-terms.hbs
- addon/components/objective-list-item-terms.js
> replaces await in templates with Resource backed data loading process.

- addon/components/offering-manager.hbs
- addon/components/offering-manager.js
- addon/components/session-offerings-list.hbs
- addon/components/session-offerings.hbs
- addon/components/session-offerings.js
- addon/components/session-overview.hbs
- addon/components/session-overview.js
- addon/components/session-publicationcheck.hbs
- addon/components/session-publicationcheck.js
- addon/components/session/postrequisite-editor.hbs
- addon/components/sessions-grid-offering.hbs
- addon/components/sessions-grid-offering.js
- addon/components/sessions-grid.hbs
> Replace await from all session/offering-management related component templates

- addon/components/print-course-session.hbs
- addon/components/print-course-session.js
- addon/components/print-course.hbs
- addon/components/print-course.js
- app/components/print-course-session.js
replace it with Resources and use a sub-component for sessions.
> rm await from print course template.

- .github/workflows/auto-merge.yml
- .github/workflows/update-transitive-dependencies.yaml
- package-lock.json
I was wrong in https://github.com/ilios/common/pull/3291#discussion_r1146458774 🍔
> Try using the github token to automerge

- addon-test-support/ilios-common/page-objects/components/selectable-terms-list-item.js
- addon-test-support/ilios-common/page-objects/components/selectable-terms-list.js
- addon/components/selectable-terms-list-item.hbs
- addon/components/selectable-terms-list-item.js
- addon/components/selectable-terms-list.hbs
- addon/components/selectable-terms-list.js
- addon/components/taxonomy-manager.hbs
- addon/components/taxonomy-manager.js
- tests/integration/components/selectable-terms-list-item-test.js
- tests/integration/components/selectable-terms-list-test.js
> refactors await out of taxonomy manager and sub-components.

- addon/models/curriculum-inventory-report.js
- tests/unit/models/curriculum-inventory-report-test.js
follows https://github.com/ilios/frontend/pull/7102
> rm obsolete Resources from Model.

- addon/components/sessions-grid.hbs
- tests/dummy/config/deprecation-workflow.js
- tests/integration/components/leadership-search-test.js
- tests/integration/components/sessions-grid-offering-table-test.js
- tests/integration/components/user-search-test.js
Mainly tests not awaiting, but in one place we were using the promise instead of the resource on SessionObject.
> Clear promise proxy deprecation

- .github/workflows/update-transitive-dependencies.yaml
Take the output of the PR number from creation and add it to the automerge command.
> Add PR number to auto merge

- addon/models/curriculum-inventory-academic-level.js
- addon/models/curriculum-inventory-institution.js
- addon/models/curriculum-inventory-sequence.js
- addon/models/report.js
- tests/unit/models/curriculum-inventory-academic-level-test.js
- tests/unit/models/curriculum-inventory-institution-test.js
- tests/unit/models/curriculum-inventory-sequence-test.js
- tests/unit/models/report-test.js
Some typos and bad data when adding these, I've fixed them and added some tests that will probably never be needed again.
> Fix some issues with inverse relationships

- package-lock.json
- package.json
refs https://github.com/ilios/lti-dashboard/pull/1293
> upgrade to latest ember-simple-charts

- .github/workflows/auto-merge.yml
> Use the pull_request_target event

- addon/components/course-publicationcheck.js
- addon/components/session-publicationcheck.hbs
- addon/components/session-publicationcheck.js
> replace computed property annotation with Resource in component.

- .github/workflows/auto-merge.yml
These are test libs so if the tests pass we can merge them.
> Automerge percy updates

- addon/components/sortable-th.hbs
- tests/integration/components/sortable-th-test.js
fixes https://github.com/ilios/ilios/issues/4766
> indicate sorting state via aria attribute.

- addon/services/permission-checker.js
- tests/unit/services/permission-checker-test.js
I reversed this, added some tests to catch it next time.
> Fix Exported Report Permissions Check

- addon-test-support/ilios-common/page-objects/components/single-event-objective-list.js
- addon-test-support/ilios-common/page-objects/components/single-event.js
- addon/components/single-event-objective-list.hbs
- addon/components/single-event.hbs
- app/styles/ilios-common/components/single-event-objective-list.scss
- app/styles/ilios-common/components/single-event.scss
- tests/integration/components/single-event-objective-list-test.js
- tests/integration/components/single-event-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
adds aria labels and aria expansion state indicators to toggle buttons.
improves icons while at it.
fixes https://github.com/ilios/ilios/issues/4777
> adds aria-expanded attribute to toggle buttons.

- .github/workflows/ci.yml
Fixed spacing in the yaml file too, or my editor did anyway.
> Update Percy Token

- addon/components/single-event-objective-list.hbs
- addon/components/single-event.hbs
- app/styles/ilios-common/components/single-event.scss
fixes https://github.com/ilios/ilios/issues/4775
> downgrades h1 to h2, and h2 to h3 headings.

- addon-test-support/ilios-common/page-objects/components/lm-type-icon.js
- addon/components/lm-type-icon.js
- tests/acceptance/dashboard/materials-test.js
- tests/integration/components/dashboard/material-list-item-test.js
- tests/integration/components/dashboard/materials-test.js
- tests/integration/components/lm-type-icon-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/ilios/issues/4770
> provide filetype-specific titles to LM icons, if applicable.

- addon-test-support/ilios-common/page-objects/components/daily-calendar-event.js
- addon-test-support/ilios-common/page-objects/components/daily-calendar.js
- addon-test-support/ilios-common/page-objects/components/weekly-calendar-event.js
- addon-test-support/ilios-common/page-objects/components/weekly-calendar.js
- addon/components/daily-calendar-event.hbs
- addon/components/weekly-calendar-event.hbs
- tests/integration/components/daily-calendar-event-test.js
- tests/integration/components/weekly-calendar-event-test.js
we currently don't have anything the checks for the various icons in here - scheduled event, draft mode, recently updated.
this fills in the gaps while propelling us into the ~~21st~~ 25th century by using page objects :rocket:
> improve calendar event test coverage

- .github/workflows/create_release.yaml
Needed to take some steps here to store the notes correctly with multiple lines.
> Fix release notes storage

- app/styles/ilios-common/components/dashboard/courses-calendar-filter.scss
fixes https://github.com/ilios/ilios/issues/4806
> removes padding around year filter group title.

- addon/components/dashboard/courses-calendar-filter.js
use a library to handle this, our homegrown approach evidently didn't work out.
fixes https://github.com/ilios/ilios/issues/4804
> corrects "scroll-to-last-year" behaviour.

- addon-test-support/ilios-common/page-objects/components/daily-calendar.js
- addon-test-support/ilios-common/page-objects/components/monthly-calendar.js
- addon-test-support/ilios-common/page-objects/components/weekly-calendar.js
- addon/components/daily-calendar.hbs
- addon/components/ilios-calendar-day.hbs
- addon/components/ilios-calendar-month.hbs
- addon/components/ilios-calendar-week.hbs
- addon/components/ilios-calendar.hbs
- addon/components/monthly-calendar.hbs
- addon/components/weekly-calendar.hbs
- app/styles/ilios-common/components/ilios-calendar.scss
- tests/acceptance/dashboard/calendar-test.js
- tests/integration/components/daily-calendar-test.js
- tests/integration/components/ilios-calendar-day-test.js
- tests/integration/components/ilios-calendar-month-test.js
- tests/integration/components/ilios-calendar-test.js
- tests/integration/components/ilios-calendar-week-test.js
- tests/integration/components/monthly-calendar-test.js
- tests/integration/components/weekly-calendar-test.js
fixes https://github.com/ilios/ilios/issues/4773
> Calendar loading state indicator a11y improvements

- addon-test-support/ilios-common/page-objects/components/dashboard/materials.js
- addon/components/dashboard/material-list-item.hbs
- addon/components/dashboard/materials.hbs
- tests/acceptance/dashboard/materials-test.js
- tests/integration/components/dashboard/materials-test.js
fixes https://github.com/ilios/ilios/issues/4780
> adds title to status table header.

- app/styles/ilios-common/components/single-event.scss
fixes https://github.com/ilios/ilios/issues/4871
> style the event title like an h3, even tho it's a h2.

- addon/components/course/objective-list-item.hbs
- addon/components/html-editor.js
- addon/components/new-objective.hbs
- addon/components/session/objective-list-item.hbs
refs https://github.com/ilios/ilios/issues/4360
> Htmleditor setfocus

- addon/components/dashboard/materials.hbs
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/ilios/issues/4765
> a11y - use <nav> element for pagination.

- addon/models/user.js
- tests/unit/models/user-test.js
fixes https://github.com/ilios/ilios/issues/4857
> fixes display of user name if given display-name is a blank string

- addon/components/single-event.hbs
- addon/components/single-event.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
fixes https://github.com/ilios/ilios/issues/4878
> style label on session type info in single event view.

- addon-test-support/ilios-common/page-objects/components/single-event-learningmaterial-list-item.js
- addon/components/single-event-learningmaterial-list-item.hbs
- addon/components/user-material-status.js
- tests/integration/components/single-event-learningmaterial-list-item-test.js
fixes https://github.com/ilios/ilios/issues/4870
> disabled checkboxes on pre-work LMs in the single event view.

- addon-test-support/ilios-common/page-objects/components/course-publicationcheck.js
- addon-test-support/ilios-common/page-objects/course-publication-check.js
- addon/components/course-publicationcheck.hbs
- addon/templates/course/publication-check.hbs
- app/styles/ilios-common/components/course-publicationcheck.scss
- tests/acceptance/course/publicationcheck-test.js
fixes https://github.com/ilios/ilios/issues/4916
> improves alignment of course publicationcheck component on page.

- addon/components/course-overview.hbs
- app/styles/ilios-common/components/course-overview.scss
- app/styles/ilios-common/mixins/course/overview.scss
fixes https://github.com/ilios/ilios/issues/4092
> Validation error display fix

- addon-mirage-support/get-all.js
- config/api-version.js
This version contains q params on courses and sessions that can be used to search for those items.
> [Breaking] Support the Ilios 3.9 API

- .github/workflows/ci.yml
- .github/workflows/future-ci.yaml
- .github/workflows/release.yaml
- .github/workflows/update-transitive-dependencies.yaml
18.18.0 has some issues with linux and webpack. Pin an old version for
CI for now.
> Pin old node version

- addon/components/session-overview.hbs
- addon/components/session-overview.js
- config/environment.js
- tests/acceptance/course/session/overview-test.js
We've enable this in production (quite a while ago actually) so it can go away here.
> Remove sessionLinkingAdminUi flag

- .github/workflows/percy.yml
Needed to match this up with the one in package.json
> Fix name of percy test command

- addon-test-support/ilios-common/page-objects/components/leadership-collapsed.js
- addon/components/course-editing.hbs
- addon/components/course-leadership-expanded.hbs
- addon/components/course-leadership-expanded.js
- addon/components/leadership-collapsed.hbs
- addon/components/leadership-collapsed.js
- addon/components/session-details.hbs
- addon/components/session-leadership-expanded.hbs
- addon/components/session-leadership-expanded.js
- tests/acceptance/course/leadership-test.js
- tests/acceptance/course/session/leadership-test.js
- tests/integration/components/course-leadership-expanded-test.js
- tests/integration/components/leadership-collapsed-test.js
- tests/integration/components/session-leadership-expanded-test.js
- translations/en-us.yaml
- translations/es.yaml
- translations/fr.yaml
refs https://github.com/ilios/ilios/issues/5063
also refs  https://github.com/ilios/ilios/issues/5062
> adds leadership count to component title.

- addon/services/api-version.js
- addon/services/current-user.js
- addon/services/ilios-config.js
- addon/services/permission-checker.js
- addon/services/permission-matrix.js
- addon/services/search.js
Missed a few of these in #3420
> Replace service injector imports

- addon/services/timezone.js
- tests/unit/services/timezone-test.js
> Timezone cleanup

- packages/test-app/package.json
Adding back this pnpm script so we can use it on netlify.
> Restore build script

- packages/ilios-common/package.json
> resets ilios-common version to 85.0.1

- .github/workflows/percy-test-pr.yml
- .github/workflows/percy.yml
> Fix percy workflow

- package.json
This command wasn't working as we were targeting the wrong type of file. Fixed it. Whoopsie.
> Fix style linting
